// course-pack-p3.js — Phase 3（Day 71–91）
// 依賴 course-pack.js 已宣告的 COURSE_PACK 與 makeLesson。

COURSE_PACK.push(
  // W11：職場進階、簡報、問題回報、談條件
  makeLesson({
    day: 71, phase: 3, week: 11, title: "用數據開場：簡報進度", scene: "週會上，你用已確認的數據向主管說明專案進度。",
    dialogue: [
      ["Mark", "m", "Could you give us a brief progress update?"],
      ["Ben", "m", "Having reviewed the numbers twice, I am confident the estimate is accurate."],
      ["Ben", "m", "Seventy percent of the work has been completed."],
      ["Mark", "m", "What remains to be done?"],
      ["Ben", "m", "The final tests, which begin tomorrow, should take three days."],
      ["Mark", "m", "Is the original deadline still realistic?"],
      ["Ben", "m", "Yes, provided that no critical defects are found."],
      ["Mark", "m", "Please send the updated figures after the meeting."],
    ],
    contractions: [],
    fixed: [{ en: "Having reviewed the numbers twice, I am confident the estimate is accurate.", zh: "在仔細檢查兩次數據後，我確信估算是準確的。", note: "分詞構句先交代完成的動作，再陳述判斷" }],
    drills: [
      { pattern: "___ percent of the work has been completed.", slots: ["Fifty", "Seventy", "Eighty", "Ninety"] },
      { pattern: "The ___, which begins tomorrow, should take three days.", slots: ["final test", "review", "inspection", "installation"] },
    ],
    newWords: [["brief", "簡短的", 0], ["estimate", "估算", 1], ["accurate", "準確的", 1], ["completed", "完成的", 2], ["remains", "剩下", 3], ["provided", "倘若；在某條件下", 6], ["defects", "缺陷", 6], ["figures", "數據", 7]],
    speaking: ["用一個百分比回報進度。", "用關係子句補充測試資訊。", "有條件地確認期限。"],
    passage: { en: "Having reviewed the latest figures, Ben reported that seventy percent of the work had been completed. The final tests, which were scheduled for the following day, were expected to take three days. The deadline remained realistic provided that no critical defects were found.", zh: "Ben 檢查最新數據後，回報工作已完成百分之七十。排定隔天開始的最終測試預計需三天。只要沒有發現重大缺陷，期限仍可達成。" },
  }),
  makeLesson({
    day: 72, phase: 3, week: 11, title: "說明流程與被動語態", scene: "客戶詢問訂單如何接受、檢查與出貨。",
    dialogue: [
      ["Client", "f", "What happens after an order is received?"],
      ["Ben", "m", "The order is checked by our sales team first."],
      ["Ben", "m", "It is then sent to the warehouse, where the items are packed."],
      ["Client", "f", "How is the quality verified?"],
      ["Ben", "m", "Every package is inspected before it is sealed."],
      ["Client", "f", "When will the tracking number be issued?"],
      ["Ben", "m", "It will be issued as soon as the shipment is collected."],
      ["Client", "f", "That process sounds clear."],
    ],
    contractions: [],
    fixed: [{ en: "It will be issued as soon as the shipment is collected.", zh: "貨件一被收走，就會發出追蹤號碼。", note: "用被動語態把重點放在流程與結果" }],
    drills: [
      { pattern: "The ___ is checked before it is sent.", slots: ["order", "document", "invoice", "package"] },
      { pattern: "It will be issued as soon as the ___ is collected.", slots: ["shipment", "package", "sample", "payment"] },
    ],
    newWords: [["received", "收到", 0], ["warehouse", "倉庫", 2], ["packed", "包裝", 2], ["verified", "驗證", 3], ["inspected", "檢查", 4], ["sealed", "封裝", 4], ["tracking", "追蹤", 5], ["issued", "發出", 5], ["collected", "收取", 6]],
    speaking: ["用被動語態說明訂單如何檢查。", "說明包裹何時封裝。", "說明追蹤號碼何時發出。"],
  }),
  makeLesson({
    day: 73, phase: 3, week: 11, title: "回報問題並說明原因", scene: "測試結果異常，你向專案經理說明問題、影響與下一步。",
    dialogue: [
      ["Mark", "m", "I saw the warning in your report. What failed?"],
      ["Ben", "m", "The sensor that controls the pressure stopped responding."],
      ["Mark", "m", "Do we know what caused it?"],
      ["Ben", "m", "The cable was damaged during installation, which caused an unstable signal."],
      ["Mark", "m", "How many units are affected?"],
      ["Ben", "m", "Three units have been identified, but the others are still being checked."],
      ["Mark", "m", "What do you recommend?"],
      ["Ben", "m", "I recommend replacing the cables and repeating the test before production resumes."],
    ],
    contractions: [],
    fixed: [{ en: "The cable was damaged during installation, which caused an unstable signal.", zh: "電纜在安裝期間受損，因而造成訊號不穩。", note: "which 關係子句補充前一件事造成的結果" }],
    drills: [
      { pattern: "The ___ that controls the pressure stopped responding.", slots: ["sensor", "device", "unit", "controller"] },
      { pattern: "I recommend ___ before production resumes.", slots: ["repeating the test", "replacing the cable", "checking every unit"] },
    ],
    newWords: [["warning", "警告", 0], ["sensor", "感測器", 1], ["pressure", "壓力", 1], ["responding", "回應", 1], ["damaged", "受損的", 3], ["installation", "安裝", 3], ["unstable", "不穩定的", 3], ["affected", "受影響的", 4], ["identified", "辨識；確認", 5], ["resumes", "恢復", 7]],
    speaking: ["說明哪個零件故障。", "用 which 說明故障結果。", "提出處理建議。"],
  }),
  makeLesson({
    day: 74, phase: 3, week: 11, title: "談條件與風險", scene: "供應商要求你接受較短交期，你提出可接受的條件。",
    dialogue: [
      ["Supplier", "f", "We can deliver on Friday if you approve the change today."],
      ["Ben", "m", "Before I approve it, I need to understand what would be changed."],
      ["Supplier", "f", "A local material would be used instead of the imported one."],
      ["Ben", "m", "Has that material been tested under the same conditions?"],
      ["Supplier", "f", "Not yet, but the specifications are similar."],
      ["Ben", "m", "If the material had been tested earlier, we could have considered it today."],
      ["Ben", "m", "I can approve the change only if the test results are provided first."],
      ["Supplier", "f", "Understood. We will send them tomorrow morning."],
    ],
    contractions: [],
    fixed: [{ en: "If the material had been tested earlier, we could have considered it today.", zh: "如果材料早一點完成測試，我們今天本來可以考慮採用。", note: "第三條件句描述與過去事實相反的情況" }],
    drills: [
      { pattern: "If ___ had been tested earlier, we could have considered it.", slots: ["the material", "the design", "the sample", "the software"] },
      { pattern: "I can approve the change only if ___ is provided first.", slots: ["the report", "the evidence", "the schedule", "the cost estimate"] },
    ],
    newWords: [["approve", "核准", 0], ["local", "本地的", 2], ["imported", "進口的", 2], ["conditions", "條件；環境", 3], ["specifications", "規格", 4], ["similar", "相似的", 4], ["considered", "考慮", 5], ["results", "結果", 6]],
    speaking: ["用第三條件句說明錯失的機會。", "提出核准變更的必要條件。", "詢問替代材料是否經過測試。"],
  }),
  makeLesson({
    day: 75, phase: 3, week: 11, title: "面試自介：經驗與成果", scene: "你在英文面試中，用工作成果證明自己適合職缺。",
    dialogue: [
      ["Interviewer", "f", "Please tell me about yourself and your experience."],
      ["Ben", "m", "I am a mechanical engineer with eight years of manufacturing experience."],
      ["Ben", "m", "In my current role, I lead projects that improve production efficiency."],
      ["Interviewer", "f", "Which achievement are you most proud of?"],
      ["Ben", "m", "I led a redesign that reduced assembly time by twenty percent."],
      ["Ben", "m", "Having worked closely with operators, I learned how small changes affect daily work."],
      ["Interviewer", "f", "Why are you interested in this position?"],
      ["Ben", "m", "I want a role where my technical experience can support larger international projects."],
    ],
    contractions: [],
    fixed: [{ en: "Having worked closely with operators, I learned how small changes affect daily work.", zh: "與作業員密切合作後，我了解小改變如何影響日常工作。", note: "分詞構句連接經驗與收穫" }],
    drills: [
      { pattern: "I am a ___ with eight years of ___ experience.", slots: ["mechanical engineer / manufacturing", "designer / product", "manager / project"] },
      { pattern: "I led a ___ that reduced ___ by twenty percent.", slots: ["redesign / assembly time", "project / waste", "review / errors"] },
    ],
    newWords: [["mechanical", "機械的", 1], ["manufacturing", "製造業", 1], ["efficiency", "效率", 2], ["achievement", "成就", 3], ["redesign", "重新設計", 4], ["reduced", "降低", 4], ["assembly", "組裝", 4], ["operators", "作業員", 5], ["technical", "技術的", 7], ["international", "國際的", 7]],
    speaking: ["用兩句話完成職場自介。", "說出一項有數字的工作成果。", "說明你想應徵的理由。"],
    passage: { en: "I am a mechanical engineer with eight years of manufacturing experience. In my current role, I lead improvement projects and work closely with operators. My strongest achievement was a redesign that reduced assembly time by twenty percent. I am now ready to support larger international projects.", zh: "我是具八年製造經驗的機械工程師。目前負責改善專案並與作業員密切合作。我最重要的成果是重新設計流程，讓組裝時間降低百分之二十。現在我準備參與更大型的國際專案。" },
  }),
  makeLesson({
    day: 76, phase: 3, week: 11, title: "向主管回報專案延誤", scene: "交期再次延後，你向主管完整回報海關問題、風險與替代承諾。",
    dialogue: [
      ["Mark", "m", "I noticed the delivery date slipped again. What happened?"],
      ["Ben", "m", "The parts we ordered from the supplier were held up at customs."],
      ["Ben", "m", "We were told the shipment would clear customs last Friday, but it did not."],
      ["Mark", "m", "Did anyone follow up?"],
      ["Ben", "m", "I did. I called them twice this week."],
      ["Ben", "m", "The person handling our case said the paperwork had been filed under the wrong category, which is why it got stuck."],
      ["Mark", "m", "So what is the new date?"],
      ["Ben", "m", "If the documents are corrected by Wednesday, we should be able to ship by the end of next week."],
      ["Mark", "m", "I need something firmer than that. Can you commit to Friday?"],
      ["Ben", "m", "I understand the urgency, but I would not be comfortable committing to Friday without written confirmation from customs."],
      ["Ben", "m", "The last time we promised a date based on a phone call, we had to push it back twice."],
      ["Mark", "m", "So you are telling me we have no date at all."],
      ["Ben", "m", "Not quite. What I can commit to is this: if customs confirms by Wednesday morning, Friday is realistic."],
      ["Ben", "m", "If they do not, the earliest we could ship would be the following Tuesday."],
      ["Ben", "m", "I would rather give you both dates now than a firm one I cannot keep."],
      ["Mark", "m", "Fair enough. What would you do differently next time?"],
      ["Ben", "m", "Having dealt with this problem twice now, I know I should have requested the customs paperwork before the shipment left, instead of assuming the supplier had taken care of it."],
      ["Ben", "m", "If we had checked the filing category at the start, we would not have lost two weeks."],
      ["Ben", "m", "I have added that step to our checklist."],
      ["Mark", "m", "Good. Send me a short update every Monday until the issue is resolved."],
    ],
    contractions: [],
    fixed: [
      { en: "I understand the urgency, but I would not be comfortable committing to Friday without written confirmation from customs.", zh: "我了解事情緊急，但在沒有海關書面確認前，我無法承諾星期五。", note: "先承認對方需求，再婉拒不可靠的承諾" },
      { en: "What I can commit to is this: if customs confirms by Wednesday morning, Friday is realistic.", zh: "我可以承諾的是：如果海關在星期三早上前確認，星期五就可行。", note: "拒絕後立刻給可驗證的替代承諾" },
    ],
    drills: [
      { pattern: "If ___ confirms by Wednesday, Friday is realistic.", slots: ["customs", "the supplier", "the client", "the carrier"] },
      { pattern: "If we had checked ___ earlier, we would not have lost two weeks.", slots: ["the filing category", "the documents", "the schedule", "the requirements"] },
    ],
    newWords: [["slipped", "延後", 0], ["supplier", "供應商", 1], ["customs", "海關", 1], ["shipment", "貨件", 2], ["paperwork", "文件作業", 5], ["category", "類別", 5], ["urgency", "急迫性", 9], ["confirmation", "確認", 9], ["realistic", "實際可行的", 12], ["assuming", "假設；認定", 16], ["checklist", "檢查表", 18], ["resolved", "解決", 19]],
    dictation: ["The parts we ordered from the supplier were held up at customs.", "The person handling our case said the paperwork had been filed under the wrong category, which is why it got stuck.", "I understand the urgency, but I would not be comfortable committing to Friday without written confirmation from customs.", "If we had checked the filing category at the start, we would not have lost two weeks.", "I called them twice this week."],
    speaking: ["說明零件為何卡在海關。", "婉拒沒有書面確認的交期承諾。", "提出兩個有條件的替代日期。", "用第三條件句說明下次如何避免延誤。"],
    passage: { en: "The parts Ben ordered were held up at customs because the paperwork had been filed under the wrong category. Rather than promise an unsupported date, he offered two dates that depended on written confirmation. Having dealt with the problem twice, he added an earlier paperwork check to the project checklist.", zh: "Ben 訂購的零件因文件歸類錯誤而卡在海關。他沒有承諾缺乏依據的日期，而是依書面確認結果提出兩個日期。處理過同樣問題兩次後，他在專案檢查表加入更早的文件查核。" },
  }),
  makeLesson({
    day: 77, phase: 3, week: 11, title: "W11 週考：職場回報與協商", scene: "你接受職場口試，完成簡報、問題回報、條件協商與面試自介。",
    dialogue: [
      ["Teacher", "f", "Please summarize the project status."],
      ["Ben", "m", "Having reviewed the figures, I am confident that seventy percent has been completed."],
      ["Teacher", "f", "Explain one problem that affected the schedule."],
      ["Ben", "m", "The parts we ordered were delayed because the paperwork had been filed incorrectly."],
      ["Teacher", "f", "What would have prevented the delay?"],
      ["Ben", "m", "If we had checked the documents earlier, we would not have lost two weeks."],
      ["Teacher", "f", "Now give me a brief professional introduction."],
      ["Ben", "m", "I am an engineer who leads improvement projects and delivers measurable results."],
    ],
    contractions: [],
    fixed: [{ en: "If we had checked the documents earlier, we would not have lost two weeks.", zh: "如果我們早一點檢查文件，就不會損失兩週。", note: "W11 第三條件句驗收" }],
    drills: [
      { pattern: "The ___ was delayed because ___.", slots: ["shipment / the paperwork was incorrect", "test / the sample arrived late", "project / a defect was found"] },
      { pattern: "I am an engineer who ___.", slots: ["leads projects", "solves technical problems", "improves production"] },
    ],
    newWords: [["summarize", "總結", 0], ["status", "狀態", 0], ["incorrectly", "不正確地", 3], ["prevented", "防止", 4], ["professional", "專業的", 6], ["measurable", "可衡量的", 7]],
    speaking: ["做一分鐘專案進度簡報。", "用被動語態與關係子句回報問題。", "用第三條件句提出改善。", "完成三十秒面試自介。"],
    passage: { en: "Having reviewed the figures, Ben reported that seventy percent of the project had been completed. The shipment was delayed because the paperwork had been filed incorrectly. If the team had checked the documents earlier, it would not have lost two weeks. Ben also introduced himself as an engineer who delivers measurable results.", zh: "檢視數字後，Ben 回報專案已完成百分之七十。貨件因文件填寫錯誤而延誤。如果團隊早點檢查文件，就不會損失兩週。Ben 也自我介紹為能交付可衡量成果的工程師。" },
  }),

  // W12：議題論述、優缺點、假設、婉轉表達
  makeLesson({
    day: 78, phase: 3, week: 12, title: "表明立場並限定範圍", scene: "團隊討論是否應讓員工在家工作，你先提出立場與適用範圍。",
    dialogue: [
      ["Sara", "f", "Should companies let employees work from home?"],
      ["Ben", "m", "I think they should offer that option, although it would not work for every job."],
      ["Sara", "f", "What is your main reason?"],
      ["Ben", "m", "Tasks that require deep concentration are often completed faster at home."],
      ["Sara", "f", "Can you give a specific example?"],
      ["Ben", "m", "I finished a report in two days that would normally have taken four."],
      ["Sara", "f", "So are you recommending fully remote work?"],
      ["Ben", "m", "No. My position is a hybrid schedule with clear team days."],
    ],
    contractions: [],
    fixed: [{ en: "I think they should offer that option, although it would not work for every job.", zh: "我認為公司應提供這個選項，雖然它不適用每一種工作。", note: "立場後立刻限定範圍，避免過度概括" }],
    drills: [
      { pattern: "I think ___, although ___.", slots: ["remote work is useful / it is not suitable for every role", "training matters / it takes time", "automation helps / it requires oversight"] },
      { pattern: "My position is ___ with ___.", slots: ["a hybrid schedule / clear team days", "a gradual change / monthly reviews", "a pilot program / measurable goals"] },
    ],
    newWords: [["option", "選項", 1], ["require", "需要", 3], ["concentration", "專注", 3], ["specific", "具體的", 4], ["normally", "通常", 5], ["recommending", "建議", 6], ["remote", "遠端的", 6], ["hybrid", "混合的", 7]],
    speaking: ["提出立場並用 although 限定。", "給一個具體例子。", "清楚說出最後主張。"],
  }),
  makeLesson({
    day: 79, phase: 3, week: 12, title: "比較優點與缺點", scene: "你主持一場混合辦公政策討論，整理雙方的優缺點。",
    dialogue: [
      ["Mark", "m", "What is the strongest advantage of remote work?"],
      ["Ben", "m", "It saves commuting time, which gives employees more control over their day."],
      ["Mark", "m", "What is the main disadvantage?"],
      ["Ben", "m", "New employees may miss the informal learning that happens in an office."],
      ["Mark", "m", "Which factor matters more?"],
      ["Ben", "m", "That depends on the role, the employee, and the support that is provided."],
      ["Mark", "m", "How would you balance them?"],
      ["Ben", "m", "I would schedule office days for training and protect home days for focused work."],
    ],
    contractions: [],
    fixed: [{ en: "That depends on the role, the employee, and the support that is provided.", zh: "這取決於職務、員工，以及公司提供的支援。", note: "比較優缺點後交代判斷條件" }],
    drills: [
      { pattern: "The strongest advantage is ___.", slots: ["greater focus", "less commuting", "lower cost", "more flexibility"] },
      { pattern: "The main disadvantage is ___.", slots: ["weaker communication", "less informal learning", "unequal access"] },
    ],
    newWords: [["advantage", "優點", 0], ["commuting", "通勤", 1], ["control", "掌控", 1], ["disadvantage", "缺點", 2], ["informal", "非正式的", 3], ["factor", "因素", 4], ["balance", "平衡", 6], ["protect", "保留；保護", 7]],
    speaking: ["各說一個優點與缺點。", "說明你的判斷取決於哪些條件。", "提出兼顧雙方的安排。"],
  }),
  makeLesson({
    day: 80, phase: 3, week: 12, title: "假設政策帶來的結果", scene: "主管要你預測全面遠端與全面進辦公室的可能結果。",
    dialogue: [
      ["Mark", "m", "What might happen if everyone worked remotely?"],
      ["Ben", "m", "Productivity might improve, but new employees could feel isolated."],
      ["Mark", "m", "What if everyone were required to return full time?"],
      ["Ben", "m", "Some experienced employees might leave for more flexible positions."],
      ["Mark", "m", "What would you test before making a permanent decision?"],
      ["Ben", "m", "I would run a three-month trial in which each team chooses two office days."],
      ["Mark", "m", "How would success be measured?"],
      ["Ben", "m", "It would be measured through output, staff retention, and customer feedback."],
    ],
    contractions: [],
    fixed: [{ en: "I would run a three-month trial in which each team chooses two office days.", zh: "我會進行三個月試辦，讓各團隊選擇兩個進辦公室的日子。", note: "用假設語氣提出尚未執行的方案" }],
    drills: [
      { pattern: "If everyone ___, ___ might ___.", slots: ["worked remotely / productivity / improve", "returned full time / some employees / leave", "shared one schedule / communication / improve"] },
      { pattern: "It would be measured through ___.", slots: ["output", "retention", "feedback", "quality data"] },
    ],
    newWords: [["productivity", "生產力", 1], ["isolated", "孤立的", 1], ["required", "被要求", 2], ["flexible", "彈性的", 3], ["permanent", "永久的", 4], ["trial", "試辦", 5], ["measured", "衡量", 6], ["retention", "留任率", 7]],
    speaking: ["預測全面遠端的兩個結果。", "提出三個月試辦方案。", "說明如何衡量成功。"],
  }),
  makeLesson({
    day: 81, phase: 3, week: 12, title: "婉轉質疑與提出替代方案", scene: "會議上有人提議立刻全面改制，你以不衝突的方式質疑。",
    dialogue: [
      ["Sara", "f", "We should move the entire team online next month."],
      ["Ben", "m", "While I see your point, I would argue that one month is not enough preparation time."],
      ["Sara", "f", "What concerns you most?"],
      ["Ben", "m", "The support system, which has not been tested, could fail under heavy demand."],
      ["Sara", "f", "Are you against the idea?"],
      ["Ben", "m", "Not at all. It might be worth considering whether a smaller pilot would reduce the risk."],
      ["Sara", "f", "What would that pilot include?"],
      ["Ben", "m", "Two volunteer teams would test the system for six weeks and report the results."],
    ],
    contractions: [],
    fixed: [
      { en: "While I see your point, I would argue that one month is not enough preparation time.", zh: "我理解你的觀點，但我認為一個月的準備時間不夠。", note: "先承認對方觀點，再提出反方理由" },
      { en: "It might be worth considering whether a smaller pilot would reduce the risk.", zh: "或許值得考慮較小規模的試辦能否降低風險。", note: "用婉轉句型提出替代方案" },
    ],
    drills: [
      { pattern: "While I see your point, I would argue that ___.", slots: ["we need more time", "the evidence is limited", "the risk is too high"] },
      { pattern: "It might be worth considering whether ___.", slots: ["a pilot would help", "the schedule could change", "another supplier is available"] },
    ],
    newWords: [["entire", "全部的", 0], ["preparation", "準備", 1], ["concerns", "使擔心；顧慮", 2], ["demand", "需求；負荷", 3], ["pilot", "試辦計畫", 5], ["reduce", "降低", 5], ["risk", "風險", 5], ["volunteer", "自願的", 7]],
    speaking: ["先承認觀點再反駁。", "婉轉指出一項風險。", "提出較小規模的替代方案。"],
  }),
  makeLesson({
    day: 82, phase: 3, week: 12, title: "婉拒不合理承諾", scene: "客戶要求你在資料不足時承諾交期，你拒絕並提出可執行方案。",
    dialogue: [
      ["Client", "f", "Can you guarantee delivery by the fifteenth?"],
      ["Ben", "m", "I understand why that date matters to you."],
      ["Ben", "m", "However, I would not be comfortable committing to a date until customs confirms."],
      ["Client", "f", "We need a date for our launch plan."],
      ["Ben", "m", "What I can commit to is a written update within twenty-four hours of confirmation."],
      ["Client", "f", "Could you reserve production capacity now?"],
      ["Ben", "m", "Yes. Capacity can be reserved while the documents are being reviewed."],
      ["Client", "f", "That would give us a workable backup plan."],
    ],
    contractions: [],
    fixed: [{ en: "However, I would not be comfortable committing to a date until customs confirms.", zh: "不過，在海關確認前，我無法承諾日期。", note: "婉拒不合理要求，但不逃避責任" }],
    drills: [
      { pattern: "I would not be comfortable committing to ___ until ___.", slots: ["a date / customs confirms", "a price / the scope is clear", "the change / testing is complete"] },
      { pattern: "What I can commit to is ___.", slots: ["a written update", "a daily status call", "reserved capacity", "a revised estimate"] },
    ],
    newWords: [["guarantee", "保證", 0], ["launch", "上市；啟動", 3], ["confirmation", "確認", 4], ["reserve", "預留", 5], ["capacity", "產能", 5], ["reviewed", "審查", 6], ["workable", "可行的", 7], ["backup", "備用方案", 7]],
    speaking: ["承認客戶的日期需求。", "婉拒缺乏依據的承諾。", "提出書面更新與預留產能方案。"],
  }),
  makeLesson({
    day: 83, phase: 3, week: 12, title: "三分鐘陳述：遠端工作", scene: "你依六個論證動作，完成一篇約三分鐘的遠端工作主題陳述。",
    dialogue: [
      ["Coach", "f", "State your position and limit its scope."],
      ["Ben", "m", "I think companies should offer employees the option to work from home, although it clearly would not work for every job."],
      ["Coach", "f", "Give two reasons and one specific example."],
      ["Ben", "m", "Remote work can improve focus and return commuting time to employees."],
      ["Ben", "m", "For example, I completed a quarterly report in two days that would normally have taken four."],
      ["Coach", "f", "Acknowledge the strongest opposing view."],
      ["Ben", "m", "I acknowledge that new employees may lose the informal learning that happens beside experienced coworkers."],
      ["Coach", "f", "Respond to that concern and conclude."],
      ["Ben", "m", "That is a reason to bring trainees and mentors together, not a reason to require everyone five days a week."],
      ["Ben", "m", "Therefore, I support a hybrid schedule that combines focused home days with purposeful office days."],
    ],
    contractions: [],
    fixed: [{ en: "That is a reason to bring trainees and mentors together, not a reason to require everyone five days a week.", zh: "這是讓受訓者與導師聚在一起的理由，不是要求所有人每週進辦公室五天的理由。", note: "承認反方後，針對其真正問題提出回應" }],
    drills: [
      { pattern: "I acknowledge that ___; however, ___.", slots: ["training is harder remotely / targeted office days can address it", "communication may slow / clear routines can help"] },
      { pattern: "Therefore, I support ___ that ___.", slots: ["a hybrid schedule / combines focus and collaboration", "a pilot / produces measurable evidence"] },
    ],
    newWords: [["scope", "範圍", 0], ["quarterly", "每季的", 4], ["acknowledge", "承認", 5], ["opposing", "反對的", 5], ["trainees", "受訓者", 8], ["mentors", "導師", 8], ["therefore", "因此", 9], ["purposeful", "有明確目的的", 9]],
    speaking: ["做三分鐘陳述：立場、兩個理由、例子、承認反方、回應反方、收尾。", "陳述後回答一題追問。", "用具體例子支持一個理由。"],
    passage: { en: "I support a hybrid work schedule, although it is not suitable for every job. Remote work improves concentration and reduces commuting time. For example, I once finished a quarterly report in half the usual time at home. I acknowledge that new employees need informal learning from experienced coworkers. However, that concern supports planned training days, not a five-day office requirement. A balanced policy should combine purposeful office time with protected time for focused work.", zh: "我支持混合辦公，雖然它不適合每一種工作。遠端工作能提升專注並減少通勤時間。例如，我曾在家用平常一半的時間完成季度報告。我承認新人需要向資深同事進行非正式學習，但這項顧慮支持的是規劃好的訓練日，而非每週五天進辦公室。平衡的政策應結合有目的的辦公室時間與受保障的專注工作時間。" },
  }),
  makeLesson({
    day: 84, phase: 3, week: 12, title: "W12 週考：完整議題論述", scene: "你完成三分鐘論述，並接受針對證據、反方與政策細節的追問。",
    dialogue: [
      ["Teacher", "f", "Give your position on hybrid work."],
      ["Ben", "m", "I support it because it improves focus and reduces commuting, although some roles must remain on site."],
      ["Teacher", "f", "What is the strongest argument against your position?"],
      ["Ben", "m", "New employees may receive less informal training when experienced coworkers are remote."],
      ["Teacher", "f", "How do you respond to that argument?"],
      ["Ben", "m", "I would schedule shared training days for the people being trained and the people training them."],
      ["Teacher", "f", "What evidence would make you change your view?"],
      ["Ben", "m", "If output and retention declined during a fair trial, I would reconsider the policy."],
    ],
    contractions: [],
    fixed: [{ en: "If output and retention declined during a fair trial, I would reconsider the policy.", zh: "如果產出與留任率在公平試辦期間下降，我會重新考慮這項政策。", note: "提出能改變自己立場的證據，避免只做單向宣傳" }],
    drills: [
      { pattern: "I support ___ because ___, although ___.", slots: ["hybrid work / it improves focus / some roles must stay on site", "a pilot / it gives evidence / it takes time"] },
      { pattern: "If ___ declined, I would reconsider ___.", slots: ["output / the policy", "quality / the change", "retention / the schedule"] },
    ],
    newWords: [["argument", "論點", 2], ["evidence", "證據", 6], ["declined", "下降", 7], ["fair", "公平的", 7], ["reconsider", "重新考慮", 7], ["policy", "政策", 7]],
    speaking: ["完成三分鐘立場陳述。", "清楚承認最強反方觀點並回應。", "說明什麼證據會讓你改變立場。"],
    passage: { en: "Ben supports hybrid work because it improves focus and reduces commuting. He acknowledges that new employees may receive less informal training. His response is to schedule shared training days. He would reconsider the policy if output and retention declined during a fair trial.", zh: "Ben 支持混合辦公，因為它能提升專注並減少通勤。他承認新人可能獲得較少非正式訓練，因此主張安排共同訓練日。如果公平試辦期間的產出與留任率下降，他會重新考慮政策。" },
  }),

  // W13：綜合實戰、語域轉換、期末驗收
  makeLesson({
    day: 85, phase: 3, week: 13, title: "同一事實的三種語域", scene: "交期不切實際，你分別對同事、主管與正式書面更新表達相同事實。",
    dialogue: [
      ["Coach", "f", "Tell a coworker that Friday is not realistic."],
      ["Ben", "m", "I do not think Friday is realistic."],
      ["Coach", "f", "Now tell your manager."],
      ["Ben", "m", "I am not confident that Friday is a realistic target."],
      ["Coach", "f", "Now write it in a formal update."],
      ["Ben", "m", "Given the remaining customs requirements, a Friday delivery is unlikely."],
      ["Coach", "f", "Did all three versions preserve the same factual meaning?"],
      ["Ben", "m", "Yes. Only the level of directness and context changed."],
    ],
    contractions: [],
    fixed: [{ en: "Given the remaining customs requirements, a Friday delivery is unlikely.", zh: "考量尚未完成的海關要求，星期五交貨的可能性不高。", note: "正式書面版要有足夠背景，單獨貼進 Email 也看得懂" }],
    drills: [
      { pattern: "Coworker: I do not think ___ is realistic.", slots: ["Friday", "this budget", "one engineer", "the current plan"] },
      { pattern: "Formal: Given ___, ___ is unlikely.", slots: ["the remaining requirements / Friday delivery", "the current staffing level / completion this month", "the test results / immediate approval"] },
    ],
    newWords: [["confident", "有信心的", 3], ["target", "目標", 3], ["given", "考量到", 5], ["remaining", "剩餘的", 5], ["requirements", "要求", 5], ["unlikely", "不太可能的", 5], ["directness", "直接程度", 7], ["context", "背景資訊", 7]],
    speaking: ["對同事說星期五不可行。", "對主管表達相同事實。", "寫成可獨立成立的正式更新。"],
  }),
  makeLesson({
    day: 86, phase: 3, week: 13, title: "語域轉換：預算不足", scene: "你要表達現有預算不足，同時維持三種說法的事實一致。",
    dialogue: [
      ["Coach", "f", "Tell your coworker that the work cannot be finished within this budget."],
      ["Ben", "m", "We cannot finish it within this budget."],
      ["Coach", "f", "How would you tell your manager?"],
      ["Ben", "m", "I do not believe the current budget is sufficient to complete the agreed scope."],
      ["Coach", "f", "Give me the formal written version."],
      ["Ben", "m", "Based on the approved scope and current supplier quotes, additional funding will be required."],
      ["Coach", "f", "What alternative would you offer?"],
      ["Ben", "m", "We could either increase the budget or postpone the optional features."],
    ],
    contractions: [],
    fixed: [{ en: "Based on the approved scope and current supplier quotes, additional funding will be required.", zh: "依核准範圍與目前供應商報價，將需要額外資金。", note: "正式書面說法交代判斷依據與需要的行動" }],
    drills: [
      { pattern: "I do not believe the current ___ is sufficient to ___.", slots: ["budget / complete the scope", "schedule / finish testing", "team size / meet the deadline"] },
      { pattern: "We could either ___ or ___.", slots: ["increase the budget / reduce the scope", "add staff / extend the schedule", "replace the supplier / accept the delay"] },
    ],
    newWords: [["sufficient", "足夠的", 3], ["agreed", "已同意的", 3], ["scope", "範圍", 3], ["approved", "核准的", 5], ["quotes", "報價", 5], ["additional", "額外的", 5], ["funding", "資金", 5], ["postpone", "延後", 7], ["optional", "選擇性的", 7]],
    speaking: ["用三種語域表達預算不足。", "確認三句沒有改變事實。", "提出增加預算或縮小範圍的替代方案。"],
  }),
  makeLesson({
    day: 87, phase: 3, week: 13, title: "語域轉換：責任與事實", scene: "客訴原因不在你的團隊，你用不同語域釐清責任，但不推卸處理責任。",
    dialogue: [
      ["Coach", "f", "How would you explain the cause to a coworker?"],
      ["Ben", "m", "Our team did not cause this problem."],
      ["Coach", "f", "Now explain it to your manager."],
      ["Ben", "m", "The evidence indicates that the issue originated outside our team."],
      ["Coach", "f", "Write a formal version for the customer."],
      ["Ben", "m", "The issue was traced to a component that had been supplied by an external vendor."],
      ["Coach", "f", "How will you avoid sounding defensive?"],
      ["Ben", "m", "I will add that we are coordinating the replacement and will remain responsible for the update."],
    ],
    contractions: [],
    fixed: [{ en: "The issue was traced to a component that had been supplied by an external vendor.", zh: "問題追查至外部供應商提供的零件。", note: "被動語態與關係子句客觀呈現調查結果" }],
    drills: [
      { pattern: "The evidence indicates that ___.", slots: ["the issue originated outside our team", "the damage occurred during transport", "the data was entered incorrectly"] },
      { pattern: "We are ___ and will remain responsible for ___.", slots: ["coordinating the replacement / the update", "reviewing the evidence / customer communication", "contacting the vendor / follow-up"] },
    ],
    newWords: [["evidence", "證據", 3], ["indicates", "顯示", 3], ["originated", "源自", 3], ["traced", "追查", 5], ["component", "零件", 5], ["external", "外部的", 5], ["vendor", "供應商", 5], ["defensive", "防衛性的", 6], ["coordinating", "協調", 7]],
    speaking: ["用三種語域說明問題並非團隊造成。", "用被動語態與關係子句寫正式說法。", "補充團隊會負責的後續行動。"],
  }),
  makeLesson({
    day: 88, phase: 3, week: 13, title: "語域轉換：人力不足", scene: "專案缺兩名人力，你向三種對象說明需求與風險。",
    dialogue: [
      ["Coach", "f", "Tell your coworker what you need."],
      ["Ben", "m", "I need two more people to catch up."],
      ["Coach", "f", "Now make the request to your manager."],
      ["Ben", "m", "To recover the current delay, I would recommend assigning two additional team members."],
      ["Coach", "f", "Write the formal project update."],
      ["Ben", "m", "Unless two additional resources are assigned by Monday, the current milestone is likely to be missed."],
      ["Coach", "f", "What if no one is available?"],
      ["Ben", "m", "If support cannot be assigned, I recommend moving the milestone by one week."],
    ],
    contractions: [],
    fixed: [{ en: "Unless two additional resources are assigned by Monday, the current milestone is likely to be missed.", zh: "除非星期一前增加兩名人力，否則目前里程碑很可能無法達成。", note: "正式書面同時交代條件、期限與影響" }],
    drills: [
      { pattern: "To recover ___, I would recommend assigning ___.", slots: ["the delay / two team members", "the schedule / another engineer", "the lost time / extra support"] },
      { pattern: "Unless ___, ___ is likely to be missed.", slots: ["support is assigned / the milestone", "the test passes / the deadline", "funding is approved / the launch"] },
    ],
    newWords: [["recover", "追回；恢復", 3], ["assigning", "指派", 3], ["resources", "資源；人力", 5], ["milestone", "里程碑", 5], ["available", "可用的", 6], ["support", "支援", 7]],
    speaking: ["用三種語域要求兩名人力。", "正式版要包含期限與不增援的後果。", "提出無法增援時的替代方案。"],
  }),
  makeLesson({
    day: 89, phase: 3, week: 13, title: "綜合回報：三大結構", scene: "你在主管會議中用被動、關係子句與條件句回報品質事故。",
    dialogue: [
      ["Director", "f", "Please explain why production was stopped."],
      ["Ben", "m", "Production was stopped after a defect was found in the valve that controls fuel flow."],
      ["Director", "f", "How did the defect pass inspection?"],
      ["Ben", "m", "The checklist had been updated, but the revised version was not given to the night shift."],
      ["Director", "f", "Could this have been prevented?"],
      ["Ben", "m", "If the revised checklist had been distributed correctly, the defect would have been detected earlier."],
      ["Director", "f", "What has been done since then?"],
      ["Ben", "m", "Having interviewed both shifts, we have introduced a signed handover process."],
    ],
    contractions: [],
    fixed: [{ en: "If the revised checklist had been distributed correctly, the defect would have been detected earlier.", zh: "如果修訂後的檢查表有正確發放，缺陷就會更早被發現。", note: "第三條件句內同時使用被動語態" }],
    drills: [
      { pattern: "___ was stopped after ___ was found in the ___ that ___.", slots: ["Production / a defect / valve / controls fuel flow", "Testing / an error / software / records pressure"] },
      { pattern: "Having ___, we have introduced ___.", slots: ["interviewed both shifts / a signed handover", "reviewed the incident / a new check", "tested the process / a backup step"] },
    ],
    newWords: [["production", "生產", 0], ["valve", "閥", 1], ["fuel", "燃料", 1], ["inspection", "檢查", 2], ["revised", "修訂的", 3], ["shift", "班別", 3], ["distributed", "分發", 5], ["detected", "偵測", 5], ["handover", "交接", 7]],
    speaking: ["用被動語態回報停產。", "用關係子句說明故障零件。", "用第三條件句說明如何避免。", "用分詞構句說明改善依據。"],
  }),
  makeLesson({
    day: 90, phase: 3, week: 13, title: "期末模擬：陳述與問答防守", scene: "期末考前，你完成主題陳述並接受質疑、澄清與反駁。",
    dialogue: [
      ["Examiner", "f", "Present your proposal for improving project communication."],
      ["Ben", "m", "I propose a weekly written update that records decisions, risks, and responsible owners."],
      ["Ben", "m", "This would reduce confusion because information that is currently scattered would be kept in one place."],
      ["Examiner", "f", "Would another report create unnecessary work?"],
      ["Ben", "m", "I acknowledge that concern, especially for teams that already hold daily meetings."],
      ["Ben", "m", "However, a ten-minute update would replace repeated questions and provide a record for absent members."],
      ["Examiner", "f", "What if people do not read it?"],
      ["Ben", "m", "If the update were linked to decisions that require approval, people would have a reason to read it."],
      ["Examiner", "f", "Give your final recommendation."],
      ["Ben", "m", "I recommend a six-week trial whose results are measured by fewer repeated questions and faster approvals."],
    ],
    contractions: [],
    fixed: [{ en: "I acknowledge that concern, especially for teams that already hold daily meetings.", zh: "我承認這項顧慮，尤其是已經每天開會的團隊。", note: "先完整承認反方，再用可衡量的方案回應" }],
    drills: [
      { pattern: "I propose ___ that ___.", slots: ["a weekly update / records decisions", "a shared checklist / assigns owners", "a trial / measures results"] },
      { pattern: "I acknowledge ___; however, ___.", slots: ["the extra work / the update would replace repeated questions", "the cost / the change would prevent delays"] },
    ],
    newWords: [["proposal", "提案", 0], ["responsible", "負責的", 1], ["confusion", "混亂", 2], ["scattered", "分散的", 2], ["unnecessary", "不必要的", 3], ["absent", "缺席的", 5], ["linked", "連結", 7], ["approvals", "核准", 9]],
    speaking: ["做三分鐘改善提案。", "承認反方並具體回應。", "回答兩題追問。", "以可衡量的試辦方案收尾。"],
  }),
  makeLesson({
    day: 91, phase: 3, week: 13, title: "期末考：完整能力驗收", scene: "完成兩小時全範圍期末考：自介、情境處理、三分鐘陳述、問答防守與語域轉換。",
    dialogue: [
      ["Examiner", "f", "Begin with a professional introduction and one measurable achievement."],
      ["Ben", "m", "I am a mechanical engineer with eight years of manufacturing experience, and I led a redesign that reduced assembly time by twenty percent."],
      ["Examiner", "f", "Report a project problem using the required advanced structures."],
      ["Ben", "m", "The parts we ordered were held up at customs because paperwork that had been filed incorrectly was not discovered in time."],
      ["Ben", "m", "If the category had been checked earlier, the shipment would not have been delayed."],
      ["Ben", "m", "Having reviewed the incident, I have added a document check that must be completed before shipping."],
      ["Examiner", "f", "Now present and defend your position on hybrid work."],
      ["Ben", "m", "I support a hybrid schedule because it improves focus, although I acknowledge that new employees need direct access to experienced coworkers."],
      ["Ben", "m", "That concern supports planned training days, not a rule requiring every employee to be present every day."],
      ["Examiner", "f", "Finally, say that Friday is unrealistic in three registers."],
      ["Ben", "m", "Coworker: I do not think Friday is realistic."],
      ["Ben", "m", "Manager: I am not confident that Friday is a realistic target."],
      ["Ben", "m", "Formal update: Given the remaining customs requirements, a Friday delivery is unlikely."],
    ],
    contractions: [],
    fixed: [
      { en: "If the category had been checked earlier, the shipment would not have been delayed.", zh: "如果分類早一點檢查，貨件就不會延誤。", note: "期末第三條件句與被動語態驗收" },
      { en: "That concern supports planned training days, not a rule requiring every employee to be present every day.", zh: "這項顧慮支持規劃訓練日，而非要求每位員工每天到場。", note: "期末承認反方再回應驗收" },
    ],
    drills: [
      { pattern: "If ___ had been ___, ___ would not have been ___.", slots: ["the category / checked / the shipment / delayed", "the defect / detected / production / stopped", "the documents / reviewed / the deadline / missed"] },
      { pattern: "Given ___, ___ is unlikely.", slots: ["the remaining requirements / Friday delivery", "the current budget / full completion", "the available staff / an early launch"] },
    ],
    newWords: [["achievement", "成就", 0], ["structures", "結構", 2], ["incident", "事件；事故", 5], ["defend", "為觀點辯護", 6], ["registers", "語域", 9], ["formal", "正式的", 12]],
    dictation: ["The parts we ordered were held up at customs.", "If the category had been checked earlier, the shipment would not have been delayed.", "Having reviewed the incident, I have added a document check.", "Given the remaining customs requirements, a Friday delivery is unlikely.", "I am not confident that Friday is a realistic target."],
    speaking: ["完成一分鐘職場自介與量化成果。", "用被動、關係子句、第三條件句及分詞構句回報問題。", "完成三分鐘主題陳述與問答防守。", "把同一事實改成同事、主管、正式書面三種語域。"],
    vocab: ["achievement", "customs", "shipment", "incident", "acknowledge", "evidence", "realistic", "registers", "formal", "unlikely"],
    passage: { en: "Final assessment: First, deliver a professional introduction with one measurable achievement. Second, report a workplace problem using passive voice, a relative clause, a third conditional, and a participle clause. Third, give a three-minute position statement with reasons, evidence, a concession, and a response to that concession. Defend the position in follow-up questions. Finally, communicate one difficult fact to a coworker, a manager, and a formal written audience without changing its meaning.", zh: "期末驗收：先完成職場自介與一項量化成果。接著使用被動語態、關係子句、第三條件句及分詞構句回報職場問題。再做三分鐘立場陳述，包含理由、證據、承認反方與回應，並接受追問防守。最後，把同一項難以傳達的事實分別說給同事、主管及正式書面讀者，且不能改變事實。" },
  }),
);

COURSE_PACK.sort((a, b) => a.day - b.day);
