/*
 * 離線單字音標字典（IPA）
 * 涵蓋常用單字；查不到的字會留空（不影響發音功能）。
 * 想擴充：直接在這個物件裡加 "單字": "音標" 即可。
 */
const PHONETIC_DICT = {
  "a": "ə", "about": "əˈbaʊt", "above": "əˈbʌv", "after": "ˈæftər", "again": "əˈgɛn",
  "all": "ɔl", "also": "ˈɔlso", "always": "ˈɔlwez", "and": "ænd", "animal": "ˈænəml",
  "answer": "ˈænsər", "any": "ˈɛni", "apple": "ˈæpl", "apply": "əˈplaɪ", "area": "ˈɛriə",
  "ask": "æsk", "back": "bæk", "bad": "bæd", "bag": "bæg", "ball": "bɔl",
  "banana": "bəˈnænə", "be": "bi", "beautiful": "ˈbjutəfl", "because": "bɪˈkɔz", "become": "bɪˈkʌm",
  "bed": "bɛd", "before": "bɪˈfɔr", "begin": "bɪˈgɪn", "behind": "bɪˈhaɪnd", "best": "bɛst",
  "better": "ˈbɛtər", "between": "bɪˈtwin", "big": "bɪg", "bird": "bɝd", "black": "blæk",
  "blue": "blu", "boat": "bot", "body": "ˈbɑdi", "book": "bʊk", "both": "boθ",
  "box": "bɑks", "boy": "bɔɪ", "bread": "brɛd", "bring": "brɪŋ", "brother": "ˈbrʌðər",
  "brown": "braʊn", "build": "bɪld", "business": "ˈbɪznəs", "busy": "ˈbɪzi", "but": "bʌt",
  "buy": "baɪ", "by": "baɪ", "call": "kɔl", "can": "kæn", "car": "kɑr",
  "card": "kɑrd", "care": "kɛr", "carry": "ˈkæri", "cat": "kæt", "catch": "kætʃ",
  "chair": "tʃɛr", "change": "tʃendʒ", "child": "tʃaɪld", "children": "ˈtʃɪldrən", "city": "ˈsɪti",
  "class": "klæs", "clean": "klin", "clear": "klɪr", "clock": "klɑk", "close": "kloz",
  "cold": "kold", "color": "ˈkʌlər", "come": "kʌm", "computer": "kəmˈpjutər", "cook": "kʊk",
  "cool": "kul", "country": "ˈkʌntri", "course": "kɔrs", "cup": "kʌp", "cut": "kʌt",
  "dance": "dæns", "dark": "dɑrk", "day": "de", "dear": "dɪr", "decide": "dɪˈsaɪd",
  "deep": "dip", "desk": "dɛsk", "die": "daɪ", "different": "ˈdɪfrənt", "difficult": "ˈdɪfɪkəlt",
  "dinner": "ˈdɪnər", "do": "du", "doctor": "ˈdɑktər", "dog": "dɔg", "door": "dɔr",
  "down": "daʊn", "draw": "drɔ", "dream": "drim", "drink": "drɪŋk", "drive": "draɪv",
  "dry": "draɪ", "ear": "ɪr", "early": "ˈɝli", "earth": "ɝθ", "easy": "ˈizi",
  "eat": "it", "egg": "ɛg", "end": "ɛnd", "english": "ˈɪŋglɪʃ", "enough": "ɪˈnʌf",
  "evening": "ˈivnɪŋ", "every": "ˈɛvri", "example": "ɪgˈzæmpl", "eye": "aɪ", "face": "fes",
  "fall": "fɔl", "family": "ˈfæməli", "far": "fɑr", "fast": "fæst", "father": "ˈfɑðər",
  "feel": "fil", "few": "fju", "find": "faɪnd", "fine": "faɪn", "finish": "ˈfɪnɪʃ",
  "fire": "ˈfaɪər", "first": "fɝst", "fish": "fɪʃ", "five": "faɪv", "floor": "flɔr",
  "flower": "ˈflaʊər", "fly": "flaɪ", "food": "fud", "foot": "fʊt", "for": "fɔr",
  "free": "fri", "friend": "frɛnd", "from": "frʌm", "fruit": "frut", "full": "fʊl",
  "fun": "fʌn", "game": "gem", "garden": "ˈgɑrdn", "get": "gɛt", "girl": "gɝl",
  "give": "gɪv", "glass": "glæs", "go": "go", "good": "gʊd", "great": "gret",
  "green": "grin", "ground": "graʊnd", "group": "grup", "grow": "gro", "hair": "hɛr",
  "half": "hæf", "hand": "hænd", "happy": "ˈhæpi", "hard": "hɑrd", "have": "hæv",
  "he": "hi", "head": "hɛd", "hear": "hɪr", "heart": "hɑrt", "help": "hɛlp",
  "her": "hɝ", "here": "hɪr", "high": "haɪ", "his": "hɪz", "home": "hom",
  "hope": "hop", "hot": "hɑt", "hour": "ˈaʊər", "house": "haʊs", "how": "haʊ",
  "hungry": "ˈhʌŋgri", "idea": "aɪˈdiə", "important": "ɪmˈpɔrtnt", "in": "ɪn", "interesting": "ˈɪntrəstɪŋ",
  "it": "ɪt", "job": "dʒɑb", "juice": "dʒus", "jump": "dʒʌmp", "just": "dʒʌst",
  "keep": "kip", "key": "ki", "kind": "kaɪnd", "know": "no", "land": "lænd",
  "large": "lɑrdʒ", "last": "læst", "late": "let", "laugh": "læf", "learn": "lɝn",
  "leave": "liv", "left": "lɛft", "leg": "lɛg", "letter": "ˈlɛtər", "life": "laɪf",
  "light": "laɪt", "like": "laɪk", "line": "laɪn", "listen": "ˈlɪsn", "little": "ˈlɪtl",
  "live": "lɪv", "long": "lɔŋ", "look": "lʊk", "lose": "luz", "love": "lʌv",
  "low": "lo", "lunch": "lʌntʃ", "make": "mek", "man": "mæn", "many": "ˈmɛni",
  "map": "mæp", "may": "me", "meet": "mit", "milk": "mɪlk", "minute": "ˈmɪnɪt",
  "money": "ˈmʌni", "month": "mʌnθ", "moon": "mun", "more": "mɔr", "morning": "ˈmɔrnɪŋ",
  "mother": "ˈmʌðər", "mountain": "ˈmaʊntn", "mouth": "maʊθ", "move": "muv", "much": "mʌtʃ",
  "music": "ˈmjuzɪk", "must": "mʌst", "name": "nem", "near": "nɪr", "need": "nid",
  "never": "ˈnɛvər", "new": "nu", "news": "nuz", "next": "nɛkst", "nice": "naɪs",
  "night": "naɪt", "no": "no", "nose": "noz", "not": "nɑt", "now": "naʊ",
  "number": "ˈnʌmbər", "ocean": "ˈoʃn", "of": "ʌv", "off": "ɔf", "office": "ˈɔfɪs",
  "often": "ˈɔfn", "old": "old", "on": "ɑn", "one": "wʌn", "only": "ˈonli",
  "open": "ˈopən", "or": "ɔr", "orange": "ˈɔrɪndʒ", "other": "ˈʌðər", "out": "aʊt",
  "over": "ˈovər", "page": "pedʒ", "paper": "ˈpepər", "parent": "ˈpɛrənt", "park": "pɑrk",
  "part": "pɑrt", "party": "ˈpɑrti", "pay": "pe", "pen": "pɛn", "people": "ˈpipl",
  "person": "ˈpɝsn", "phone": "fon", "picture": "ˈpɪktʃər", "place": "ples", "plant": "plænt",
  "play": "ple", "please": "pliz", "point": "pɔɪnt", "poor": "pʊr", "power": "ˈpaʊər",
  "practice": "ˈpræktɪs", "problem": "ˈprɑbləm", "put": "pʊt", "question": "ˈkwɛstʃən", "quick": "kwɪk",
  "quiet": "ˈkwaɪət", "rain": "ren", "read": "rid", "ready": "ˈrɛdi", "real": "ril",
  "red": "rɛd", "remember": "rɪˈmɛmbər", "rest": "rɛst", "rich": "rɪtʃ", "right": "raɪt",
  "river": "ˈrɪvər", "road": "rod", "room": "rum", "run": "rʌn", "sad": "sæd",
  "safe": "sef", "same": "sem", "say": "se", "school": "skul", "sea": "si",
  "see": "si", "sell": "sɛl", "send": "sɛnd", "she": "ʃi", "ship": "ʃɪp",
  "shoe": "ʃu", "shop": "ʃɑp", "short": "ʃɔrt", "show": "ʃo", "sick": "sɪk",
  "side": "saɪd", "sing": "sɪŋ", "sister": "ˈsɪstər", "sit": "sɪt", "sky": "skaɪ",
  "sleep": "slip", "slow": "slo", "small": "smɔl", "smile": "smaɪl", "snow": "sno",
  "so": "so", "some": "sʌm", "song": "sɔŋ", "soon": "sun", "sorry": "ˈsɑri",
  "sound": "saʊnd", "speak": "spik", "spend": "spɛnd", "sport": "spɔrt", "spring": "sprɪŋ",
  "stand": "stænd", "star": "stɑr", "start": "stɑrt", "stay": "ste", "stop": "stɑp",
  "store": "stɔr", "story": "ˈstɔri", "street": "strit", "strong": "strɔŋ", "student": "ˈstudnt",
  "study": "ˈstʌdi", "sugar": "ˈʃʊgər", "summer": "ˈsʌmər", "sun": "sʌn", "sure": "ʃʊr",
  "table": "ˈtebl", "take": "tek", "talk": "tɔk", "tall": "tɔl", "tea": "ti",
  "teach": "titʃ", "teacher": "ˈtitʃər", "tell": "tɛl", "test": "tɛst", "than": "ðæn",
  "thank": "θæŋk", "that": "ðæt", "the": "ðə", "their": "ðɛr", "them": "ðɛm",
  "then": "ðɛn", "there": "ðɛr", "they": "ðe", "thing": "θɪŋ", "think": "θɪŋk",
  "this": "ðɪs", "time": "taɪm", "tired": "ˈtaɪərd", "to": "tu", "today": "təˈde",
  "together": "təˈgɛðər", "tomorrow": "təˈmɑro", "tonight": "təˈnaɪt", "too": "tu", "tooth": "tuθ",
  "top": "tɑp", "town": "taʊn", "travel": "ˈtrævl", "tree": "tri", "true": "tru",
  "try": "traɪ", "turn": "tɝn", "two": "tu", "under": "ˈʌndər", "understand": "ˌʌndərˈstænd",
  "up": "ʌp", "use": "juz", "very": "ˈvɛri", "wait": "wet", "walk": "wɔk",
  "wall": "wɔl", "want": "wɑnt", "warm": "wɔrm", "wash": "wɑʃ", "watch": "wɑtʃ",
  "water": "ˈwɔtər", "way": "we", "we": "wi", "wear": "wɛr", "weather": "ˈwɛðər",
  "week": "wik", "well": "wɛl", "what": "wʌt", "when": "wɛn", "where": "wɛr",
  "white": "waɪt", "who": "hu", "why": "waɪ", "wind": "wɪnd", "window": "ˈwɪndo",
  "winter": "ˈwɪntər", "wish": "wɪʃ", "with": "wɪð", "woman": "ˈwʊmən", "word": "wɝd",
  "work": "wɝk", "world": "wɝld", "write": "raɪt", "wrong": "rɔŋ", "year": "jɪr",
  "yellow": "ˈjɛlo", "yes": "jɛs", "yesterday": "ˈjɛstərde", "you": "ju", "young": "jʌŋ"
};

// 查單字音標：回傳 IPA 字串，查不到回傳 null
function lookupPhonetic(word) {
  if (!word) return null;
  const key = word.trim().toLowerCase().replace(/[^a-z'-]/g, "");
  return PHONETIC_DICT[key] || null;
}

/*
 * 離線中文對照表
 * 想擴充：直接在這裡加 "單字": "中文" 即可。
 */
const ZH_DICT = {
  "about": "關於", "above": "在上面", "after": "之後", "again": "再次", "all": "全部",
  "also": "也", "always": "總是", "and": "和", "animal": "動物", "answer": "回答",
  "any": "任何", "apple": "蘋果", "apply": "申請", "area": "區域", "ask": "問",
  "back": "背面／回來", "bad": "壞的", "bag": "袋子", "ball": "球", "banana": "香蕉",
  "beautiful": "美麗的", "because": "因為", "become": "變成", "bed": "床", "before": "之前",
  "begin": "開始", "behind": "在後面", "best": "最好的", "better": "更好的", "between": "在之間",
  "big": "大的", "bird": "鳥", "black": "黑色", "blue": "藍色", "boat": "船",
  "body": "身體", "book": "書", "both": "兩者", "box": "盒子", "boy": "男孩",
  "bread": "麵包", "bring": "帶來", "brother": "兄弟", "brown": "棕色", "build": "建造",
  "business": "生意", "busy": "忙碌的", "but": "但是", "buy": "買", "by": "藉由",
  "call": "打電話／呼叫", "can": "能夠", "car": "汽車", "card": "卡片", "care": "在乎／照顧",
  "carry": "攜帶", "cat": "貓", "catch": "抓住", "chair": "椅子", "change": "改變",
  "child": "小孩", "children": "孩子們", "city": "城市", "class": "課堂／班級", "clean": "乾淨的",
  "clear": "清楚的", "clock": "時鐘", "close": "關閉／靠近", "cold": "冷的", "color": "顏色",
  "come": "來", "computer": "電腦", "cook": "烹飪", "cool": "涼的／酷", "country": "國家",
  "course": "課程", "cup": "杯子", "cut": "切", "dance": "跳舞", "dark": "黑暗的",
  "day": "天", "dear": "親愛的", "decide": "決定", "deep": "深的", "desk": "書桌",
  "die": "死", "different": "不同的", "difficult": "困難的", "dinner": "晚餐", "do": "做",
  "doctor": "醫生", "dog": "狗", "door": "門", "down": "向下", "draw": "畫",
  "dream": "夢想", "drink": "喝", "drive": "開車", "dry": "乾的", "ear": "耳朵",
  "early": "早的", "earth": "地球", "easy": "容易的", "eat": "吃", "egg": "蛋",
  "end": "結束", "english": "英語", "enough": "足夠的", "evening": "傍晚", "every": "每個",
  "example": "例子", "eye": "眼睛", "face": "臉", "fall": "掉落／秋天", "family": "家庭",
  "far": "遠的", "fast": "快的", "father": "父親", "feel": "感覺", "few": "很少的",
  "find": "找到", "fine": "好的", "finish": "完成", "fire": "火", "first": "第一",
  "fish": "魚", "five": "五", "floor": "地板", "flower": "花", "fly": "飛",
  "food": "食物", "foot": "腳", "for": "為了", "free": "自由的／免費的", "friend": "朋友",
  "from": "來自", "fruit": "水果", "full": "滿的", "fun": "樂趣", "game": "遊戲",
  "garden": "花園", "get": "得到", "girl": "女孩", "give": "給", "glass": "玻璃／杯子",
  "go": "去", "good": "好的", "great": "很棒的", "green": "綠色", "ground": "地面",
  "group": "團體", "grow": "成長", "hair": "頭髮", "half": "一半", "hand": "手",
  "happy": "快樂的", "hard": "困難的／硬的", "have": "有", "he": "他", "head": "頭",
  "hear": "聽到", "heart": "心", "help": "幫助", "her": "她的", "here": "這裡",
  "high": "高的", "his": "他的", "home": "家", "hope": "希望", "hot": "熱的",
  "hour": "小時", "house": "房子", "how": "如何", "hungry": "餓的", "idea": "點子",
  "important": "重要的", "in": "在裡面", "interesting": "有趣的", "it": "它", "job": "工作",
  "juice": "果汁", "jump": "跳", "just": "只是／剛剛", "keep": "保持", "key": "鑰匙",
  "kind": "種類／親切的", "know": "知道", "land": "土地", "large": "大的", "last": "最後的",
  "late": "遲的", "laugh": "笑", "learn": "學習", "leave": "離開", "left": "左邊",
  "leg": "腿", "letter": "信／字母", "life": "生命", "light": "光／輕的", "like": "喜歡",
  "line": "線／隊伍", "listen": "聽", "little": "小的", "live": "居住", "long": "長的",
  "look": "看", "lose": "失去", "love": "愛", "low": "低的", "lunch": "午餐",
  "make": "製作", "man": "男人", "many": "許多", "map": "地圖", "may": "可能",
  "meet": "見面", "milk": "牛奶", "minute": "分鐘", "money": "錢", "month": "月份",
  "moon": "月亮", "more": "更多", "morning": "早上", "mother": "母親", "mountain": "山",
  "mouth": "嘴巴", "move": "移動", "much": "許多", "music": "音樂", "must": "必須",
  "name": "名字", "near": "附近", "need": "需要", "never": "從不", "new": "新的",
  "news": "新聞", "next": "下一個", "nice": "好的", "night": "夜晚", "no": "不",
  "nose": "鼻子", "not": "不", "now": "現在", "number": "號碼", "ocean": "海洋",
  "of": "的", "off": "關閉／離開", "office": "辦公室", "often": "經常", "old": "老的",
  "on": "在上面", "one": "一", "only": "只有", "open": "打開", "or": "或者",
  "orange": "橘子／橘色", "other": "其他的", "out": "向外", "over": "結束／在上方", "page": "頁",
  "paper": "紙", "parent": "父母", "park": "公園", "part": "部分", "party": "派對",
  "pay": "付款", "pen": "筆", "people": "人們", "person": "人", "phone": "電話",
  "picture": "圖片", "place": "地方", "plant": "植物", "play": "玩／播放", "please": "請",
  "point": "點／指", "poor": "貧窮的", "power": "力量", "practice": "練習", "problem": "問題",
  "put": "放", "question": "問題", "quick": "快的", "quiet": "安靜的", "rain": "雨",
  "read": "閱讀", "ready": "準備好的", "real": "真實的", "red": "紅色", "remember": "記得",
  "rest": "休息", "rich": "富有的", "right": "正確的／右邊", "river": "河流", "road": "道路",
  "room": "房間", "run": "跑", "sad": "傷心的", "safe": "安全的", "same": "相同的",
  "say": "說", "school": "學校", "sea": "海", "see": "看見", "sell": "賣",
  "send": "寄送", "she": "她", "ship": "船", "shoe": "鞋子", "shop": "商店",
  "short": "短的", "show": "展示", "sick": "生病的", "side": "邊", "sing": "唱歌",
  "sister": "姊妹", "sit": "坐", "sky": "天空", "sleep": "睡覺", "slow": "慢的",
  "small": "小的", "smile": "微笑", "snow": "雪", "so": "所以", "some": "一些",
  "song": "歌曲", "soon": "很快", "sorry": "抱歉", "sound": "聲音", "speak": "說",
  "spend": "花費", "sport": "運動", "spring": "春天", "stand": "站立", "star": "星星",
  "start": "開始", "stay": "停留", "stop": "停止", "store": "商店", "story": "故事",
  "street": "街道", "strong": "強壯的", "student": "學生", "study": "讀書", "sugar": "糖",
  "summer": "夏天", "sun": "太陽", "sure": "確定的", "table": "桌子", "take": "拿",
  "talk": "說話", "tall": "高的", "tea": "茶", "teach": "教", "teacher": "老師",
  "tell": "告訴", "test": "測驗", "than": "比", "thank": "謝謝", "that": "那個",
  "the": "這／那", "their": "他們的", "them": "他們", "then": "然後", "there": "那裡",
  "they": "他們", "thing": "東西", "think": "想", "this": "這個", "time": "時間",
  "tired": "疲倦的", "to": "到", "today": "今天", "together": "一起", "tomorrow": "明天",
  "tonight": "今晚", "too": "也／太", "tooth": "牙齒", "top": "頂部", "town": "城鎮",
  "travel": "旅行", "tree": "樹", "true": "真的", "try": "嘗試", "turn": "轉動／輪到",
  "two": "二", "under": "在下面", "understand": "理解", "up": "向上", "use": "使用",
  "very": "非常", "wait": "等待", "walk": "走路", "wall": "牆", "want": "想要",
  "warm": "溫暖的", "wash": "洗", "watch": "手錶／觀看", "water": "水", "way": "方法／路",
  "we": "我們", "wear": "穿", "weather": "天氣", "week": "星期", "well": "好地／井",
  "what": "什麼", "when": "何時", "where": "哪裡", "white": "白色", "who": "誰",
  "why": "為什麼", "wind": "風", "window": "窗戶", "winter": "冬天", "wish": "希望",
  "with": "和", "woman": "女人", "word": "單字", "work": "工作", "world": "世界",
  "write": "寫", "wrong": "錯誤的", "year": "年", "yellow": "黃色", "yes": "是",
  "yesterday": "昨天", "you": "你", "young": "年輕的"
};

// 查單字中文：回傳中文字串，查不到回傳 null
function lookupZh(word) {
  if (!word) return null;
  const key = word.trim().toLowerCase().replace(/[^a-z'-]/g, "");
  return ZH_DICT[key] || null;
}
