// 內建國中初階單字包 — 8 級 × 50 字，每字附例句＋回覆句（國中初階程度生活日常對話）
// 欄位：t=單字 zh=中文 ph=音標 ex=例句 exZh=例句中文 re=回覆句 reZh=回覆句中文
const JHS1_PACK = [
{ level: 1, words: [
{ t:"about", zh:"關於；大約", ph:"əˈbaʊt", ex:"The movie is about a brave dog.", exZh:"這部電影是關於一隻勇敢的狗。", re:"I want to see it this weekend.", reZh:"我這週末想去看。" },
{ t:"above", zh:"在...上面", ph:"əˈbʌv", ex:"The bird flew above the trees.", exZh:"鳥在樹木上方飛翔。", re:"It looked so beautiful from there.", reZh:"從那邊看起來很漂亮。" },
{ t:"act", zh:"行動；表演", ph:"ækt", ex:"She will act in the school play.", exZh:"她將在校園劇中表演。", re:"That sounds exciting!", reZh:"聽起來很刺激！" },
{ t:"address", zh:"地址；談及", ph:"əˈdrɛs", ex:"What is your address?", exZh:"你的地址是什麼？", re:"It is on Maple Street.", reZh:"在楓樹街上。" },
{ t:"afraid", zh:"害怕的", ph:"əˈfred", ex:"Are you afraid of spiders?", exZh:"你怕蜘蛛嗎？", re:"No, not really.", reZh:"不，不太怕。" },
{ t:"ago", zh:"以前", ph:"əˈgo", ex:"I saw him two days ago.", exZh:"我兩天前看到他。", re:"Did you have fun with him?", reZh:"你和他玩得開心嗎？" },
{ t:"air", zh:"空氣", ph:"ɛr", ex:"The air in the mountain is fresh.", exZh:"山裡的空氣很清新。", re:"I love breathing fresh air.", reZh:"我喜歡呼吸新鮮空氣。" },
{ t:"airplane", zh:"飛機", ph:"ˈɛrplen", ex:"I took an airplane to Japan.", exZh:"我搭飛機到日本。", re:"How was the trip?", reZh:"旅程怎麼樣？" },
{ t:"all", zh:"全部；所有", ph:"ɔl", ex:"All the students are here today.", exZh:"今天所有學生都在。", re:"Great! We can start the class.", reZh:"太好了！我們可以開始上課。" },
{ t:"along", zh:"沿著；一起", ph:"əˈlɔŋ", ex:"We walked along the beach.", exZh:"我們沿著海灘散步。", re:"Did you enjoy the walk?", reZh:"你享受散步嗎？" },
{ t:"animal", zh:"動物", ph:"ˈænɪməl", ex:"I love that animal at the zoo.", exZh:"我喜歡動物園裡的那隻動物。", re:"Which one is your favorite?", reZh:"你最喜歡哪一隻？" },
{ t:"ant", zh:"螞蟻", ph:"ænt", ex:"Look at this ant on the ground.", exZh:"看看地上的這隻螞蟻。", re:"Ants are so tiny and hard-working.", reZh:"螞蟻很小但很勤奮。" },
{ t:"anyone", zh:"任何人", ph:"ˈɛniˌwʌn", ex:"Does anyone want to play?", exZh:"有人想玩嗎？", re:"I do! Let's play together.", reZh:"我想！讓我們一起玩。" },
{ t:"anything", zh:"任何事物", ph:"ˈɛniˌθɪŋ", ex:"Do you need anything from the store?", exZh:"你需要店裡的任何東西嗎？", re:"No, thank you. I'm fine.", reZh:"不用，謝謝。我很好。" },
{ t:"area", zh:"區域；面積", ph:"ˈɛriə", ex:"This area is very quiet.", exZh:"這個區域很安靜。", re:"Yes, I like living here.", reZh:"是的，我喜歡住在這裡。" },
{ t:"art", zh:"藝術", ph:"ɑrt", ex:"She is good at art and drawing.", exZh:"她很擅長藝術和繪畫。", re:"Her paintings are beautiful.", reZh:"她的畫很漂亮。" },
{ t:"away", zh:"遠離；離開", ph:"əˈwe", ex:"He went away on vacation.", exZh:"他去度假了。", re:"When will he come back?", reZh:"他什麼時候回來？" },
{ t:"backpack", zh:"背包", ph:"ˈbækˌpæk", ex:"I put my books in my backpack.", exZh:"我把書放在背包裡。", re:"Is it heavy?", reZh:"很重嗎？" },
{ t:"band", zh:"樂隊；帶子", ph:"bænd", ex:"The school band plays at concerts.", exZh:"校樂隊在音樂會上演奏。", re:"I'd love to listen to them.", reZh:"我很想聽他們演奏。" },
{ t:"bank", zh:"銀行；河岸", ph:"bæŋk", ex:"I need to go to the bank.", exZh:"我需要去銀行。", re:"Do you need to withdraw money?", reZh:"你需要取錢嗎？" },
{ t:"basket", zh:"籃子", ph:"ˈbæskɪt", ex:"Put the apples in the basket.", exZh:"把蘋果放在籃子裡。", re:"This basket is perfect for picnics.", reZh:"這個籃子很適合野餐。" },
{ t:"bat", zh:"蝙蝠；球棒", ph:"bæt", ex:"The bat came out at night.", exZh:"蝙蝠在晚上出現。", re:"I'm a little scared of them.", reZh:"我有點怕它們。" },
{ t:"beach", zh:"海灘", ph:"bitʃ", ex:"Let's go to the beach on Sunday.", exZh:"我們週日去海灘吧。", re:"Great! I'll bring my swimsuit.", reZh:"很好！我會帶上泳衣。" },
{ t:"bear", zh:"熊；忍受", ph:"bɛr", ex:"The bear was very big and scary.", exZh:"那隻熊很大，很嚇人。", re:"I would be afraid too.", reZh:"我也會害怕。" },
{ t:"bedroom", zh:"臥室", ph:"ˈbɛdˌrum", ex:"My bedroom is very small.", exZh:"我的臥室很小。", re:"But it looks cozy.", reZh:"但看起來很舒服。" },
{ t:"bee", zh:"蜜蜂", ph:"bi", ex:"The bee was making honey.", exZh:"蜜蜂在製造蜂蜜。", re:"I love honey on my bread.", reZh:"我喜歡麵包上的蜂蜜。" },
{ t:"before", zh:"在...之前", ph:"bɪˈfɔr", ex:"Please come before five o'clock.", exZh:"請在五點前來。", re:"I will be there on time.", reZh:"我會準時到達。" },
{ t:"behind", zh:"在...後面", ph:"bɪˈhaɪnd", ex:"The cat is hiding behind the door.", exZh:"貓躲在門後。", re:"Let's find it and play with it.", reZh:"讓我們找到它，和它一起玩。" },
{ t:"bell", zh:"鐘；鈴", ph:"bɛl", ex:"The school bell rings at eight.", exZh:"校鐘在八點響。", re:"That means class is starting.", reZh:"那意味著課要開始了。" },
{ t:"below", zh:"在...下面", ph:"bɪˈlo", ex:"The fish are swimming below us.", exZh:"魚在我們下面游泳。", re:"Can you see them clearly?", reZh:"你能看清楚嗎？" },
{ t:"bench", zh:"長椅", ph:"bɛntʃ", ex:"Let's sit on the bench and rest.", exZh:"讓我們坐在長椅上休息。", re:"Good idea. I'm tired.", reZh:"好主意。我累了。" },
{ t:"beside", zh:"在...旁邊", ph:"bɪˈsaɪd", ex:"She sat beside her friend.", exZh:"她坐在朋友旁邊。", re:"They looked happy together.", reZh:"他們看起來很開心。" },
{ t:"bicycle", zh:"自行車", ph:"ˈbaɪsɪkəl", ex:"I ride my bicycle to school.", exZh:"我騎自行車上學。", re:"Does your bicycle have new tires?", reZh:"你的自行車輪胎是新的嗎？" },
{ t:"birthday", zh:"生日", ph:"ˈbɝθde", ex:"My birthday is in May.", exZh:"我的生日在五月。", re:"We should have a party!", reZh:"我們應該舉辦派對！" },
{ t:"blackboard", zh:"黑板", ph:"ˈblækˌbɔrd", ex:"The teacher writes on the blackboard.", exZh:"老師在黑板上寫字。", re:"Can you read what she wrote?", reZh:"你能讀清楚她寫的嗎？" },
{ t:"blow", zh:"吹", ph:"blo", ex:"The wind will blow the leaves away.", exZh:"風會吹走葉子。", re:"I love autumn weather.", reZh:"我喜歡秋天的天氣。" },
{ t:"boil", zh:"沸騰；煮", ph:"bɔɪl", ex:"The water will boil soon.", exZh:"水很快就會沸騰。", re:"Be careful! It's very hot.", reZh:"小心！很燙。" },
{ t:"bone", zh:"骨頭", ph:"bon", ex:"The dog is eating a bone.", exZh:"狗在啃骨頭。", re:"It looks happy with that bone.", reZh:"它看起來很開心。" },
{ t:"boss", zh:"老闆", ph:"bɔs", ex:"My father is the boss at work.", exZh:"我父親是工作的老闆。", re:"That's a big responsibility.", reZh:"那是很大的責任。" },
{ t:"brave", zh:"勇敢的", ph:"brev", ex:"The brave boy helped his friend.", exZh:"勇敢的男孩幫助了他的朋友。", re:"He really is very courageous.", reZh:"他確實很勇敢。" },
{ t:"bridge", zh:"橋", ph:"brɪdʒ", ex:"We crossed the bridge to the park.", exZh:"我們過橋去公園。", re:"That bridge is very beautiful.", reZh:"那座橋很漂亮。" },
{ t:"bring", zh:"帶來；拿來", ph:"brɪŋ", ex:"Can you bring your homework tomorrow?", exZh:"你明天能帶功課來嗎？", re:"Yes, I won't forget it.", reZh:"是的，我不會忘記。" },
{ t:"brush", zh:"刷子；刷", ph:"brʌʃ", ex:"I brush my teeth every morning.", exZh:"我每天早上刷牙。", re:"That's a good habit.", reZh:"那是個好習慣。" },
{ t:"build", zh:"建築；建立", ph:"bɪld", ex:"We will build a sandcastle.", exZh:"我們要建造一個沙堡。", re:"That sounds like fun!", reZh:"聽起來很有趣！" },
{ t:"butter", zh:"黃油；奶油", ph:"ˈbʌtɝ", ex:"I spread butter on my toast.", exZh:"我在吐司上塗奶油。", re:"Butter makes toast taste better.", reZh:"奶油讓吐司更好吃。" },
{ t:"button", zh:"按鈕；紐扣", ph:"ˈbʌtən", ex:"Push the button to start.", exZh:"按按鈕開始。", re:"Nothing happened. Try again.", reZh:"沒有反應。再試一次。" },
{ t:"camera", zh:"相機", ph:"ˈkæmɚə", ex:"She took photos with her camera.", exZh:"她用相機拍照。", re:"Her photos are very professional.", reZh:"她的照片很專業。" },
{ t:"can", zh:"能夠；罐子", ph:"kæn", ex:"I can swim very well.", exZh:"我游泳游得很好。", re:"Can you teach me?", reZh:"你能教我嗎？" },
{ t:"candy", zh:"糖果", ph:"ˈkændi", ex:"The candy is sweet and delicious.", exZh:"糖果甜且好吃。", re:"I love eating candy.", reZh:"我喜歡吃糖果。" },
{ t:"cap", zh:"帽子；蓋子", ph:"kæp", ex:"He wore a red cap.", exZh:"他戴著紅帽子。", re:"It looks cool on him.", reZh:"在他身上看起來很酷。" },
] },
{ level: 2, words: [
{ t:"care", zh:"關心；照顧", ph:"kɛr", ex:"I care about my family.", exZh:"我關心我的家人。", re:"They care about you too.", reZh:"他們也關心你。" },
{ t:"carry", zh:"攜帶；搬運", ph:"ˈkæri", ex:"Can you carry this box for me?", exZh:"你能幫我搬這個盒子嗎？", re:"Sure, it's not too heavy.", reZh:"好的，不太重。" },
{ t:"cellphone", zh:"手機", ph:"ˈsɛlfon", ex:"My cellphone is on the table.", exZh:"我的手機在桌子上。", re:"Do you need to make a call?", reZh:"你需要打電話嗎？" },
{ t:"center", zh:"中心", ph:"ˈsɛntɝ", ex:"The center of the city is busy.", exZh:"城市中心很繁忙。", re:"I prefer quieter neighborhoods.", reZh:"我更喜歡安靜的社區。" },
{ t:"change", zh:"改變；零錢", ph:"tʃendʒ", ex:"Things can change quickly.", exZh:"事情可能快速改變。", re:"That's why we must be prepared.", reZh:"所以我們必須做好準備。" },
{ t:"chat", zh:"聊天", ph:"tʃæt", ex:"Let's chat about the new movie.", exZh:"讓我們聊聊新電影。", re:"I haven't seen it yet.", reZh:"我還沒看過。" },
{ t:"check", zh:"檢查；支票", ph:"tʃɛk", ex:"Please check your homework.", exZh:"請檢查你的功課。", re:"I already did. It's all correct.", reZh:"我已經檢查過了。全部正確。" },
{ t:"chess", zh:"國際象棋", ph:"tʃɛs", ex:"Do you know how to play chess?", exZh:"你會下象棋嗎？", re:"Yes, but I'm not very good.", reZh:"會，但我下得不太好。" },
{ t:"chocolate", zh:"巧克力", ph:"ˈtʃɔklət", ex:"I like chocolate ice cream.", exZh:"我喜歡巧克力冰淇淋。", re:"Me too! It's my favorite.", reZh:"我也是！那是我的最愛。" },
{ t:"chopsticks", zh:"筷子", ph:"ˈtʃɑpstɪks", ex:"I eat with chopsticks every day.", exZh:"我每天用筷子吃飯。", re:"Can you use chopsticks well?", reZh:"你會用筷子嗎？" },
{ t:"classmate", zh:"同學", ph:"ˈklæsmet", ex:"My classmate is very friendly.", exZh:"我的同學很友善。", re:"That's great! Friends are important.", reZh:"那很好！朋友很重要。" },
{ t:"classroom", zh:"教室", ph:"ˈklæsrum", ex:"The classroom is very bright.", exZh:"教室很明亮。", re:"Good lighting helps us study better.", reZh:"好的光線幫助我們更好地學習。" },
{ t:"clothes", zh:"衣服", ph:"kloðz", ex:"I bought new clothes yesterday.", exZh:"我昨天買了新衣服。", re:"What color did you choose?", reZh:"你選了什麼顏色？" },
{ t:"coat", zh:"外套；外衣", ph:"kot", ex:"Wear your coat. It's cold outside.", exZh:"穿上外套。外面很冷。", re:"I almost forgot! Thanks.", reZh:"我差點忘了！謝謝。" },
{ t:"coin", zh:"硬幣", ph:"kɔɪn", ex:"I found a coin on the ground.", exZh:"我在地上找到一個硬幣。", re:"Maybe you're lucky today!", reZh:"也許你今天很幸運！" },
{ t:"color", zh:"顏色", ph:"ˈkʌlɝ", ex:"What is your favorite color?", exZh:"你最喜歡的顏色是什麼？", re:"I like blue. It's calm and peaceful.", reZh:"我喜歡藍色。它很平靜安祥。" },
{ t:"comic", zh:"漫畫", ph:"ˈkɑmɪk", ex:"I read a comic book yesterday.", exZh:"我昨天讀了一本漫畫書。", re:"Are you into comics?", reZh:"你喜歡漫畫嗎？" },
{ t:"cookie", zh:"餅乾", ph:"ˈkʊki", ex:"These cookies are delicious.", exZh:"這些餅乾很好吃。", re:"Can I have one more?", reZh:"我能再要一塊嗎？" },
{ t:"corn", zh:"玉米", ph:"kɔrn", ex:"Fresh corn is sweet and tasty.", exZh:"新鮮玉米甜且好吃。", re:"I'll buy some at the market.", reZh:"我會在市場買一些。" },
{ t:"correct", zh:"正確的；改正", ph:"kəˈrɛkt", ex:"Your answer is correct.", exZh:"你的答案是正確的。", re:"Thank you for checking.", reZh:"謝謝你檢查。" },
{ t:"count", zh:"計數；伯爵", ph:"kaʊnt", ex:"Can you count to one hundred?", exZh:"你能數到一百嗎？", re:"Yes, I've been practicing.", reZh:"是的，我一直在練習。" },
{ t:"course", zh:"課程；當然", ph:"kɔrs", ex:"I'm taking an English course.", exZh:"我在上英文課程。", re:"How do you like it so far?", reZh:"到目前為止你覺得怎麼樣？" },
{ t:"cover", zh:"蓋子；覆蓋", ph:"ˈkʌvɝ", ex:"Cover your mouth when you cough.", exZh:"咳嗽時用嘴蓋住。", re:"That's very important.", reZh:"那很重要。" },
{ t:"cow", zh:"母牛", ph:"kaʊ", ex:"The cow is eating grass.", exZh:"母牛在吃草。", re:"Farm animals are interesting.", reZh:"農場動物很有趣。" },
{ t:"cross", zh:"穿過；十字形", ph:"krɔs", ex:"Let's cross the street carefully.", exZh:"讓我們小心穿過街道。", re:"Always look both ways first.", reZh:"先看兩邊。" },
{ t:"cute", zh:"可愛的", ph:"kjut", ex:"That puppy is so cute!", exZh:"那隻小狗太可愛了！", re:"I want to pet it.", reZh:"我想摸它。" },
{ t:"date", zh:"日期；約會", ph:"det", ex:"What is the date today?", exZh:"今天是幾號？", re:"It's the third of July.", reZh:"七月三號。" },
{ t:"dead", zh:"死的", ph:"dɛd", ex:"The plant is dead. We need a new one.", exZh:"植物死了。我們需要新的。", re:"I'll water the next one carefully.", reZh:"我會小心澆下一個。" },
{ t:"decide", zh:"決定", ph:"dɪˈsaɪd", ex:"I can't decide what to eat.", exZh:"我決定不了吃什麼。", re:"How about pizza?", reZh:"披薩怎麼樣？" },
{ t:"deep", zh:"深的", ph:"dip", ex:"The water is very deep here.", exZh:"這裡的水很深。", re:"Be careful when swimming.", reZh:"游泳時要小心。" },
{ t:"delicious", zh:"美味的", ph:"dɪˈlɪʃəs", ex:"This food is so delicious!", exZh:"這個食物太美味了！", re:"The chef is very talented.", reZh:"廚師很有才華。" },
{ t:"dictionary", zh:"字典", ph:"ˈdɪkʃəˌnɛri", ex:"Look up the word in your dictionary.", exZh:"在你的字典裡查這個詞。", re:"Good idea. I'll do that.", reZh:"好主意。我會的。" },
{ t:"dinner", zh:"晚餐", ph:"ˈdɪnɝ", ex:"What time is dinner?", exZh:"晚餐幾點？", re:"Usually at six o'clock.", reZh:"通常在六點。" },
{ t:"doctor", zh:"醫生", ph:"ˈdɑktɝ", ex:"I visited the doctor yesterday.", exZh:"我昨天看醫生。", re:"Are you feeling better now?", reZh:"你現在感覺好點了嗎？" },
{ t:"dolphin", zh:"海豚", ph:"ˈdɑlfɪn", ex:"The dolphin is jumping in the water.", exZh:"海豚在水中跳躍。", re:"Dolphins are very smart animals.", reZh:"海豚是聰明的動物。" },
{ t:"donkey", zh:"驢子", ph:"ˈdɑŋki", ex:"The donkey carries heavy things.", exZh:"驢子搬運重物。", re:"It's a hard-working animal.", reZh:"它很勤勞。" },
{ t:"dragon", zh:"龍", ph:"ˈdrægən", ex:"Dragons are in Chinese stories.", exZh:"龍在中文故事裡。", re:"They are fascinating creatures.", reZh:"它們很有魅力。" },
{ t:"dress", zh:"連衣裙；穿衣", ph:"drɛs", ex:"She wore a blue dress.", exZh:"她穿著藍色連衣裙。", re:"She looked beautiful.", reZh:"她看起來很漂亮。" },
{ t:"driver", zh:"司機", ph:"ˈdraɪvɝ", ex:"The driver is very careful.", exZh:"司機很小心。", re:"Safety is most important.", reZh:"安全最重要。" },
{ t:"drum", zh:"鼓", ph:"drʌm", ex:"He plays the drum in the band.", exZh:"他在樂隊裡打鼓。", re:"The sound is so loud!", reZh:"聲音太大了！" },
{ t:"duck", zh:"鴨子", ph:"dʌk", ex:"The duck is swimming in the pond.", exZh:"鴨子在池塘裡游泳。", re:"It looks so happy there.", reZh:"它在那裡看起來很開心。" },
{ t:"dumpling", zh:"餃子", ph:"ˈdʌmplɪŋ", ex:"I love eating dumplings.", exZh:"我喜歡吃餃子。", re:"They taste great with soy sauce.", reZh:"加醬油更好吃。" },
{ t:"each", zh:"每一個", ph:"itʃ", ex:"Each student has a textbook.", exZh:"每個學生都有課本。", re:"That's only fair to everyone.", reZh:"這對每個人都公平。" },
{ t:"east", zh:"東方", ph:"ist", ex:"The sun rises in the east.", exZh:"太陽從東方升起。", re:"That's right. West is where it sets.", reZh:"沒錯。西邊是它落下的地方。" },
{ t:"elevator", zh:"電梯", ph:"ˈɛləˌvetɝ", ex:"Take the elevator to the tenth floor.", exZh:"搭電梯到十樓。", re:"I prefer stairs for exercise.", reZh:"我更喜歡爬樓梯運動。" },
{ t:"else", zh:"其他的；別的", ph:"ɛls", ex:"Is there anything else you need?", exZh:"還有其他你需要的嗎？", re:"No, that's everything. Thanks!", reZh:"沒有，那就是全部。謝謝！" },
{ t:"engineer", zh:"工程師", ph:"ˌɛndʒɪˈnɪr", ex:"My uncle is an engineer.", exZh:"我叔叔是工程師。", re:"That must be a challenging job.", reZh:"那一定是個具挑戰的工作。" },
{ t:"enjoy", zh:"享受", ph:"ɪnˈdʒɔɪ", ex:"Did you enjoy the concert?", exZh:"你享受音樂會嗎？", re:"Yes! The music was wonderful.", reZh:"是的！音樂很棒。" },
{ t:"enter", zh:"進入", ph:"ˈɛntɝ", ex:"Enter the classroom quietly.", exZh:"安靜地進入教室。", re:"Got it. I'll be quiet.", reZh:"明白了。我會安靜。" },
{ t:"erase", zh:"擦除", ph:"ɪˈres", ex:"Erase the pencil marks on the paper.", exZh:"擦掉紙上的鉛筆痕跡。", re:"I need a good eraser.", reZh:"我需要一個好橡皮擦。" },
] },
{ level: 3, words: [
{ t:"ever", zh:"曾經", ph:"ˈɛvɝ", ex:"Have you ever been to the beach?", exZh:"你曾經去過海灘嗎？", re:"Yes, many times!", reZh:"是的，好多次！" },
{ t:"everyone", zh:"每個人", ph:"ˈɛvriˌwʌn", ex:"Everyone is happy today.", exZh:"今天每個人都很開心。", re:"It's a beautiful day for it.", reZh:"這是美好的一天。" },
{ t:"exam", zh:"考試", ph:"ɪgˈzæm", ex:"I have an exam tomorrow.", exZh:"我明天有考試。", re:"You'll do great! Don't worry.", reZh:"你會做得很好！別擔心。" },
{ t:"excited", zh:"興奮的", ph:"ɪkˈsaɪtɪd", ex:"I'm excited about the field trip.", exZh:"我對戶外教學感到興奮。", re:"Me too! It'll be so much fun.", reZh:"我也是！會很有趣。" },
{ t:"exercise", zh:"運動；練習", ph:"ˈɛksɝˌsaɪz", ex:"I exercise three times a week.", exZh:"我一週運動三次。", re:"That's a healthy habit.", reZh:"那是個健康的習慣。" },
{ t:"fact", zh:"事實", ph:"fækt", ex:"It's a fact that birds can fly.", exZh:"鳥能飛是一個事實。", re:"Most birds can. But not all.", reZh:"大多數鳥會。但不是全部。" },
{ t:"fail", zh:"失敗", ph:"fel", ex:"Don't fail the test this time.", exZh:"這次別讓考試失敗。", re:"I'll study harder.", reZh:"我會更努力讀書。" },
{ t:"famous", zh:"著名的", ph:"ˈfeməs", ex:"That actor is very famous.", exZh:"那位演員很著名。", re:"I'd love to meet him one day.", reZh:"我希望有一天能見到他。" },
{ t:"farmer", zh:"農夫", ph:"ˈfɑrmɝ", ex:"The farmer grows vegetables.", exZh:"農夫種蔬菜。", re:"His work is very hard.", reZh:"他的工作很辛苦。" },
{ t:"feed", zh:"餵食", ph:"fid", ex:"Can you feed the dog?", exZh:"你能餵狗嗎？", re:"Of course! I love the dog.", reZh:"當然！我喜歡狗。" },
{ t:"feel", zh:"感到；觸摸", ph:"fil", ex:"How do you feel today?", exZh:"你今天感覺如何？", re:"I'm doing well, thank you.", reZh:"我很好，謝謝。" },
{ t:"fever", zh:"發燒", ph:"ˈfivɝ", ex:"I have a fever so I can't go out.", exZh:"我發燒了，所以不能出去。", re:"You should rest and drink water.", reZh:"你應該休息和喝水。" },
{ t:"fifteen", zh:"十五", ph:"ˌfɪfˈtin", ex:"I will be fifteen next year.", exZh:"我明年十五歲。", re:"That's still young.", reZh:"那還很年輕。" },
{ t:"fight", zh:"戰鬥；打架", ph:"faɪt", ex:"The two boys will fight over the ball.", exZh:"兩個男孩會為球打架。", re:"I hope they share instead.", reZh:"我希望他們能分享。" },
{ t:"final", zh:"最後的；決賽", ph:"ˈfaɪnəl", ex:"This is the final game of the season.", exZh:"這是季節的最後一場比賽。", re:"I can't wait to see who wins!", reZh:"我迫不及待想看誰會贏！" },
{ t:"finger", zh:"手指", ph:"ˈfɪŋgɝ", ex:"I cut my finger this morning.", exZh:"我今天早上割傷了手指。", re:"I hope it heals quickly.", reZh:"我希望它快速癒合。" },
{ t:"finish", zh:"完成", ph:"ˈfɪnɪʃ", ex:"When will you finish your homework?", exZh:"你什麼時候完成功課？", re:"In about an hour.", reZh:"大約一小時後。" },
{ t:"first", zh:"第一", ph:"ˈfɝst", ex:"She came first in the race.", exZh:"她在比賽中第一個衝線。", re:"She ran so fast!", reZh:"她跑得很快！" },
{ t:"flag", zh:"旗幟", ph:"flæg", ex:"The flag is red and white.", exZh:"旗幟是紅白色。", re:"It waves so beautifully in the wind.", reZh:"它在風中飄揚得很美。" },
{ t:"flower", zh:"花", ph:"ˈflaʊɝ", ex:"This flower is very pretty.", exZh:"這朵花很漂亮。", re:"Would you like me to pick it for you?", reZh:"你要我為你摘下來嗎？" },
{ t:"follow", zh:"跟隨", ph:"ˈfɑlo", ex:"Follow me to the museum.", exZh:"跟我去博物館。", re:"I'm right behind you.", reZh:"我就在你後面。" },
{ t:"forest", zh:"森林", ph:"ˈfɔrɪst", ex:"The forest is full of trees.", exZh:"森林裡樹木繁茂。", re:"I love walking through forests.", reZh:"我喜歡在森林裡散步。" },
{ t:"forget", zh:"忘記", ph:"fɝˈgɛt", ex:"Don't forget your umbrella.", exZh:"別忘了你的傘。", re:"Thanks for reminding me!", reZh:"謝謝提醒！" },
{ t:"fresh", zh:"新鮮的", ph:"frɛʃ", ex:"This bread is fresh and warm.", exZh:"這麵包新鮮又溫暖。", re:"It smells so good.", reZh:"聞起來很香。" },
{ t:"frog", zh:"青蛙", ph:"frɑg", ex:"The frog jumps very high.", exZh:"青蛙跳得很高。", re:"I saw one by the pond yesterday.", reZh:"我昨天在池塘邊看到一隻。" },
{ t:"front", zh:"前面", ph:"frʌnt", ex:"Sit in the front of the class.", exZh:"坐在教室前面。", re:"That way you can see better.", reZh:"這樣你能看得更清楚。" },
{ t:"full", zh:"滿的", ph:"fʊl", ex:"The glass is full of water.", exZh:"玻璃杯裝滿了水。", re:"Be careful not to spill it.", reZh:"小心別灑出來。" },
{ t:"funny", zh:"有趣的；滑稽的", ph:"ˈfʌni", ex:"That joke is very funny.", exZh:"那個笑話很有趣。", re:"I laughed so hard!", reZh:"我笑得很開心！" },
{ t:"future", zh:"未來", ph:"ˈfjutʃɝ", ex:"In the future, I want to be a teacher.", exZh:"將來，我想當老師。", re:"That's a great goal.", reZh:"那是個很好的目標。" },
{ t:"garden", zh:"花園", ph:"ˈgɑrdən", ex:"We grow flowers in the garden.", exZh:"我們在花園裡種花。", re:"Your flowers are beautiful.", reZh:"你的花很漂亮。" },
{ t:"ghost", zh:"幽靈；鬼", ph:"gost", ex:"Do you believe in ghosts?", exZh:"你相信鬼嗎？", re:"I'm not sure. Maybe.", reZh:"我不確定。也許吧。" },
{ t:"giraffe", zh:"長頸鹿", ph:"dʒəˈræf", ex:"The giraffe has a long neck.", exZh:"長頸鹿有長頸子。", re:"It's the tallest animal.", reZh:"它是最高的動物。" },
{ t:"glass", zh:"玻璃；杯子", ph:"glæs", ex:"Be careful with the glass.", exZh:"小心玻璃。", re:"It breaks easily.", reZh:"它容易碎。" },
{ t:"glue", zh:"膠水", ph:"glu", ex:"Use glue to stick the paper.", exZh:"用膠水粘紙。", re:"Don't use too much glue.", reZh:"不要用太多膠水。" },
{ t:"goat", zh:"山羊", ph:"got", ex:"The goat is eating the grass.", exZh:"山羊在吃草。", re:"It's a funny-looking animal.", reZh:"它看起來很有趣。" },
{ t:"gold", zh:"黃金；金色", ph:"gold", ex:"Gold is a precious metal.", exZh:"黃金是貴金屬。", re:"It's very expensive.", reZh:"它很昂貴。" },
{ t:"grade", zh:"年級；等級", ph:"gred", ex:"I'm in grade seven this year.", exZh:"今年我在七年級。", re:"How do you like your new school?", reZh:"你喜歡新學校嗎？" },
{ t:"grandmother", zh:"祖母；奶奶", ph:"ˈgrænˌmʌðɝ", ex:"My grandmother lives with us.", exZh:"我祖母和我們住在一起。", re:"That's nice. Grandmothers are special.", reZh:"那很好。祖母很特別。" },
{ t:"gray", zh:"灰色的", ph:"gre", ex:"The sky is gray today.", exZh:"今天天空是灰色的。", re:"Looks like rain is coming.", reZh:"看起來要下雨了。" },
{ t:"ground", zh:"地面；地", ph:"graʊnd", ex:"The ground is wet after the rain.", exZh:"雨後地面很濕。", re:"Be careful not to slip.", reZh:"小心別滑倒。" },
{ t:"group", zh:"團體；組", ph:"grup", ex:"We work in a group for the project.", exZh:"我們為專案組成一個團隊。", re:"Teamwork makes it easier.", reZh:"團隊合作讓工作更容易。" },
{ t:"guava", zh:"番石榴", ph:"ˈgwɑvə", ex:"I eat a guava every day.", exZh:"我每天吃一個番石榴。", re:"They're very healthy fruit.", reZh:"它們是很健康的水果。" },
{ t:"guitar", zh:"吉他", ph:"gɪˈtɑr", ex:"He plays the guitar beautifully.", exZh:"他吉他彈得很美。", re:"I wish I could play like him.", reZh:"我希望我能像他一樣彈。" },
{ t:"habit", zh:"習慣", ph:"ˈhæbɪt", ex:"Reading is a good habit.", exZh:"閱讀是個好習慣。", re:"I try to read every day.", reZh:"我盡量每天閱讀。" },
{ t:"ham", zh:"火腿", ph:"hæm", ex:"I have ham and cheese sandwich.", exZh:"我有火腿乳酪三明治。", re:"That sounds delicious.", reZh:"聽起來很好吃。" },
{ t:"handsome", zh:"英俊的", ph:"ˈhændsəm", ex:"That actor is very handsome.", exZh:"那個演員很英俊。", re:"Many people think so.", reZh:"很多人都這樣認為。" },
{ t:"hang", zh:"掛；懸吊", ph:"hæŋ", ex:"Hang your coat on the hook.", exZh:"把你的外套掛在掛鉤上。", re:"OK. I'll do it now.", reZh:"好的。我現在就做。" },
{ t:"hate", zh:"討厭", ph:"het", ex:"I hate cold weather.", exZh:"我討厭寒冷的天氣。", re:"I prefer spring and autumn.", reZh:"我更喜歡春秋。" },
{ t:"health", zh:"健康", ph:"hɛlθ", ex:"Good health is important.", exZh:"良好的健康很重要。", re:"That's why I exercise regularly.", reZh:"所以我定期運動。" },
{ t:"heart", zh:"心；心臟", ph:"hɑrt", ex:"My heart beats fast when I'm scared.", exZh:"害怕時我心臟跳得很快。", re:"That's completely normal.", reZh:"那是完全正常的。" },
] },
{ level: 4, words: [
{ t:"hen", zh:"母雞", ph:"hɛn", ex:"The hen laid an egg.", exZh:"母雞下了一個蛋。", re:"Farm life is interesting.", reZh:"農場生活很有趣。" },
{ t:"hill", zh:"小山", ph:"hɪl", ex:"We climbed up the hill.", exZh:"我們爬上了山。", re:"The view from the top was great.", reZh:"從頂部看風景很好。" },
{ t:"history", zh:"歷史", ph:"ˈhɪstɚi", ex:"I love learning history.", exZh:"我喜歡學歷史。", re:"History helps us understand the world.", reZh:"歷史幫助我們理解世界。" },
{ t:"hobby", zh:"愛好", ph:"ˈhɑbi", ex:"My hobby is collecting stamps.", exZh:"我的愛好是集郵。", re:"That's an interesting hobby.", reZh:"那是個有趣的愛好。" },
{ t:"holiday", zh:"假日", ph:"ˈhɑləˌde", ex:"Summer holiday is finally here!", exZh:"暑假終於來了！", re:"What will you do?", reZh:"你會做什麼？" },
{ t:"homework", zh:"功課；家庭作業", ph:"ˈhomˌwɝk", ex:"I finished all my homework.", exZh:"我完成了所有功課。", re:"Good job! You're very responsible.", reZh:"做得好！你很負責。" },
{ t:"honey", zh:"蜂蜜", ph:"ˈhʌni", ex:"Honey is sweet and sticky.", exZh:"蜂蜜甜且粘稠。", re:"Bees make it from flowers.", reZh:"蜜蜂用花蜜製成它。" },
{ t:"hotel", zh:"飯店；旅館", ph:"hoˈtɛl", ex:"We stayed at a nice hotel.", exZh:"我們住在一家不錯的飯店。", re:"Did you enjoy your stay?", reZh:"你享受住宿嗎？" },
{ t:"hour", zh:"小時；鐘點", ph:"ˈaʊɝ", ex:"We waited for one hour.", exZh:"我們等了一個小時。", re:"That's a long time.", reZh:"那很長。" },
{ t:"hurry", zh:"匆忙；急忙", ph:"ˈhɝi", ex:"Hurry up! We're late!", exZh:"快點！我們遲到了！", re:"I'm coming as fast as I can.", reZh:"我盡快過去。" },
{ t:"husband", zh:"丈夫", ph:"ˈhʌzbənd", ex:"Her husband is a teacher.", exZh:"她的丈夫是老師。", re:"That's a noble profession.", reZh:"那是個崇高的職業。" },
{ t:"idea", zh:"主意；想法", ph:"aɪˈdiə", ex:"That's a great idea!", exZh:"那是個好主意！", re:"Let's do it right away.", reZh:"我們馬上做吧。" },
{ t:"inside", zh:"裡面", ph:"ˌɪnˈsaɪd", ex:"Come inside the house.", exZh:"進屋裡。", re:"It's warmer here.", reZh:"這裡更溫暖。" },
{ t:"interesting", zh:"有趣的", ph:"ˈɪntrəstɪŋ", ex:"This book is very interesting.", exZh:"這本書很有趣。", re:"I can't put it down.", reZh:"我放不下來。" },
{ t:"internet", zh:"網際網路", ph:"ˈɪntɝˌnɛt", ex:"I use the internet for homework.", exZh:"我用網際網路做功課。", re:"It's a useful tool.", reZh:"它是個有用的工具。" },
{ t:"island", zh:"島嶼", ph:"ˈaɪlənd", ex:"This island is very beautiful.", exZh:"這個島很漂亮。", re:"I wish we could stay longer.", reZh:"我希望能待更久。" },
{ t:"jeans", zh:"牛仔褲", ph:"dʒinz", ex:"I wear jeans every day.", exZh:"我每天穿牛仔褲。", re:"They're comfortable and stylish.", reZh:"它們舒服又時尚。" },
{ t:"jog", zh:"慢跑", ph:"dʒɑg", ex:"I jog in the park every morning.", exZh:"我每天早上在公園慢跑。", re:"That's great exercise.", reZh:"那是很好的運動。" },
{ t:"joke", zh:"笑話；開玩笑", ph:"dʒok", ex:"Tell me a joke!", exZh:"講個笑話給我！", re:"Why did the chicken cross the road?", reZh:"為什麼雞要過馬路？" },
{ t:"just", zh:"剛剛；只是", ph:"dʒʌst", ex:"I just arrived home.", exZh:"我剛到家。", re:"Good timing! Dinner is ready.", reZh:"時間恰好！晚餐準備好了。" },
{ t:"keep", zh:"保持；保存", ph:"kip", ex:"Keep your room clean.", exZh:"保持房間乾淨。", re:"I'll try my best.", reZh:"我會盡力。" },
{ t:"kick", zh:"踢", ph:"kɪk", ex:"He kicked the ball into the goal.", exZh:"他把球踢進了球門。", re:"That was an amazing shot!", reZh:"那是個太棒的射門！" },
{ t:"kill", zh:"殺死", ph:"kɪl", ex:"Don't kill the spiders.", exZh:"不要殺死蜘蛛。", re:"They catch bugs and help us.", reZh:"它們抓蟲子幫助我們。" },
{ t:"king", zh:"國王", ph:"kɪŋ", ex:"The king ruled the country.", exZh:"國王統治了國家。", re:"Kings have great power.", reZh:"國王有很大的權力。" },
{ t:"knee", zh:"膝蓋", ph:"ni", ex:"I hurt my knee playing soccer.", exZh:"我踢足球時傷了膝蓋。", re:"You should rest it.", reZh:"你應該讓它休息。" },
{ t:"lady", zh:"女士；女人", ph:"ˈledi", ex:"The old lady is very kind.", exZh:"那位老女士很善良。", re:"She helped us carry groceries.", reZh:"她幫我們提雜貨。" },
{ t:"lake", zh:"湖", ph:"lek", ex:"The lake is beautiful in summer.", exZh:"湖在夏天很漂亮。", re:"I love swimming in the lake.", reZh:"我喜歡在湖裡游泳。" },
{ t:"land", zh:"陸地；降落", ph:"lænd", ex:"The plane will land soon.", exZh:"飛機很快就會降落。", re:"I can see the ground now.", reZh:"我現在能看到地面了。" },
{ t:"large", zh:"大的", ph:"lɑrdʒ", ex:"This house is very large.", exZh:"這所房子很大。", re:"It must be expensive.", reZh:"它一定很昂貴。" },
{ t:"laugh", zh:"笑", ph:"læf", ex:"I laughed at the funny movie.", exZh:"我對有趣的電影笑了。", re:"Everyone enjoyed it.", reZh:"大家都享受了。" },
{ t:"leader", zh:"領導者；隊長", ph:"ˈlidɝ", ex:"He is the leader of the group.", exZh:"他是團體的領導者。", re:"He does a great job.", reZh:"他做得很好。" },
{ t:"leave", zh:"離開；留下", ph:"liv", ex:"We leave for the trip tomorrow.", exZh:"我們明天出發去旅行。", re:"I'm so excited!", reZh:"我太興奮了！" },
{ t:"left", zh:"左邊；離開", ph:"lɛft", ex:"Turn left at the corner.", exZh:"在角落向左轉。", re:"OK. I see it now.", reZh:"好的。我看到了。" },
{ t:"lend", zh:"借給", ph:"lɛnd", ex:"Can you lend me a pencil?", exZh:"你能借我一支鉛筆嗎？", re:"Sure! Here you go.", reZh:"當然！給你。" },
{ t:"lie", zh:"躺；說謊", ph:"laɪ", ex:"Don't lie to your parents.", exZh:"不要對父母說謊。", re:"Honesty is the best policy.", reZh:"誠實是最好的政策。" },
{ t:"line", zh:"線；隊伍", ph:"laɪn", ex:"Draw a line on the paper.", exZh:"在紙上畫一條線。", re:"Make it straight.", reZh:"要直的。" },
{ t:"lip", zh:"嘴唇", ph:"lɪp", ex:"She has red lip gloss on.", exZh:"她塗了紅色唇彩。", re:"It looks nice.", reZh:"看起來不錯。" },
{ t:"lonely", zh:"孤獨的", ph:"ˈlonli", ex:"I feel lonely sometimes.", exZh:"有時我感到孤獨。", re:"You can call me anytime.", reZh:"你可以隨時給我打電話。" },
{ t:"lose", zh:"失去；輸掉", ph:"luz", ex:"Don't lose your way.", exZh:"不要迷路。", re:"I have a map with me.", reZh:"我帶著地圖。" },
{ t:"lunch", zh:"午餐", ph:"lʌntʃ", ex:"What did you eat for lunch?", exZh:"你午餐吃了什麼？", re:"I had a sandwich and juice.", reZh:"我吃了三明治和果汁。" },
{ t:"mad", zh:"生氣的；瘋狂的", ph:"mæd", ex:"Don't get mad at me.", exZh:"別對我生氣。", re:"I'm sorry. I didn't mean it.", reZh:"對不起。我不是故意的。" },
{ t:"mail", zh:"郵件；郵寄", ph:"mel", ex:"Did you mail the letter?", exZh:"你寄了那封信嗎？", re:"Yes, it went out yesterday.", reZh:"是的，昨天寄出去了。" },
{ t:"map", zh:"地圖", ph:"mæp", ex:"Look at the map to find the way.", exZh:"看地圖找路。", re:"We're going the right direction.", reZh:"我們走的方向正確。" },
{ t:"math", zh:"數學", ph:"mæθ", ex:"I have a math test today.", exZh:"我今天有數學測驗。", re:"I hope you do well.", reZh:"我希望你表現好。" },
{ t:"matter", zh:"重要；物質", ph:"ˈmætɝ", ex:"It doesn't matter if you're late.", exZh:"你遲到不要緊。", re:"Thanks for understanding.", reZh:"謝謝你的理解。" },
{ t:"mean", zh:"意思是；平均", ph:"min", ex:"What does this word mean?", exZh:"這個詞是什麼意思？", re:"Let me check the dictionary.", reZh:"讓我查字典。" },
{ t:"medicine", zh:"藥；醫學", ph:"ˈmɛdəsən", ex:"Take your medicine on time.", exZh:"按時吃藥。", re:"It tastes bad, but it helps.", reZh:"味道不好，但有幫助。" },
{ t:"member", zh:"成員", ph:"ˈmɛmbɝ", ex:"I am a member of the club.", exZh:"我是俱樂部的成員。", re:"That's wonderful!", reZh:"那太好了！" },
{ t:"mind", zh:"介意；思想", ph:"maɪnd", ex:"Do you mind if I sit here?", exZh:"你介意我坐這裡嗎？", re:"Not at all. Please sit.", reZh:"不介意。請坐。" },
{ t:"mirror", zh:"鏡子", ph:"ˈmɪrɝ", ex:"Look at yourself in the mirror.", exZh:"照鏡子看自己。", re:"You look great today.", reZh:"你今天看起來很好。" },
] },
{ level: 5, words: [
{ t:"mistake", zh:"錯誤", ph:"mɪˈstek", ex:"I made a mistake on the test.", exZh:"我在測驗上犯了一個錯誤。", re:"Don't worry. Everyone makes mistakes.", reZh:"別擔心。每個人都會犯錯。" },
{ t:"model", zh:"模型；模特", ph:"ˈmɑdəl", ex:"That model airplane looks cool.", exZh:"那個飛機模型看起來很酷。", re:"I built it myself.", reZh:"我自己造的。" },
{ t:"monkey", zh:"猴子", ph:"ˈmʌŋki", ex:"The monkey swings from tree to tree.", exZh:"猴子在樹間擺動。", re:"They're so acrobatic!", reZh:"它們真靈巧！" },
{ t:"motorcycle", zh:"摩托車", ph:"ˈmotɝˌsaɪkəl", ex:"His motorcycle is very fast.", exZh:"他的摩托車很快。", re:"He loves riding it.", reZh:"他喜歡騎它。" },
{ t:"mouse", zh:"滑鼠；老鼠", ph:"maʊs", ex:"A mouse ran across the kitchen.", exZh:"一隻老鼠跑過廚房。", re:"I'm afraid of them!", reZh:"我怕它們！" },
{ t:"mud", zh:"泥土", ph:"mʌd", ex:"The mud is very sticky.", exZh:"泥土很粘。", re:"I got it all over my shoes.", reZh:"我的鞋上全是。" },
{ t:"nature", zh:"自然", ph:"ˈnetʃɝ", ex:"I love the beauty of nature.", exZh:"我喜歡自然之美。", re:"Nature is very peaceful.", reZh:"自然很平靜。" },
{ t:"near", zh:"靠攏；毗鄰", ph:"nɪr", ex:"The school is near my house.", exZh:"學校鄰接我的房子。", re:"That's convenient.", reZh:"那很方便。" },
{ t:"neighbor", zh:"鄰居", ph:"ˈnebɝ", ex:"My neighbor is very friendly.", exZh:"我的鄰居很友善。", re:"Good neighbors make good communities.", reZh:"好鄰居讓好社區。" },
{ t:"net", zh:"網；淨", ph:"nɛt", ex:"The net caught many fish.", exZh:"網抓住了很多魚。", re:"That's a good catch!", reZh:"那是個好收穫！" },
{ t:"newspaper", zh:"報紙", ph:"ˈnjuzˌpepɝ", ex:"My father reads the newspaper every morning.", exZh:"我父親每天早上讀報紙。", re:"That's a good habit.", reZh:"那是個好習慣。" },
{ t:"nobody", zh:"沒有人", ph:"ˈnobɑdi", ex:"Nobody knows where it came from.", exZh:"沒有人知道它從哪裡來。", re:"It's a mystery.", reZh:"那是個謎。" },
{ t:"noodle", zh:"麵條", ph:"ˈnudəl", ex:"I love eating noodles.", exZh:"我喜歡吃麵條。", re:"Noodles are delicious.", reZh:"麵條很好吃。" },
{ t:"noon", zh:"中午", ph:"nun", ex:"We'll meet at noon.", exZh:"我們中午見面。", re:"That works for me.", reZh:"對我來說可以。" },
{ t:"note", zh:"筆記；便條", ph:"not", ex:"I took notes in class.", exZh:"我在課堂上做了筆記。", re:"That helps with studying.", reZh:"那幫助學習。" },
{ t:"nurse", zh:"護士", ph:"nɝs", ex:"The nurse helped my mother.", exZh:"護士幫助了我的母親。", re:"Nurses are very caring.", reZh:"護士很關心人。" },
{ t:"office", zh:"辦公室", ph:"ˈɑfɪs", ex:"My father works in an office.", exZh:"我父親在辦公室工作。", re:"It must be a busy place.", reZh:"那一定是個忙碌的地方。" },
{ t:"oil", zh:"油", ph:"ɔɪl", ex:"Cooking oil is necessary.", exZh:"食用油是必需的。", re:"We buy it in large containers.", reZh:"我們買大罐的。" },
{ t:"once", zh:"一次；曾經", ph:"wʌns", ex:"I've been there once before.", exZh:"我以前去過一次。", re:"Did you enjoy it?", reZh:"你享受嗎？" },
{ t:"order", zh:"命令；秩序；訂購", ph:"ˈɔrdɝ", ex:"Let me order dinner online.", exZh:"讓我線上訂購晚餐。", re:"Great! What do you want?", reZh:"太好了！你想要什麼？" },
{ t:"outside", zh:"外面", ph:"ˌaʊtˈsaɪd", ex:"It's sunny outside.", exZh:"外面陽光明媚。", re:"Let's go play outside.", reZh:"讓我們出去玩。" },
{ t:"own", zh:"擁有", ph:"on", ex:"I own a bicycle.", exZh:"我擁有一輛自行車。", re:"That's great! What color is it?", reZh:"太好了！什麼顏色？" },
{ t:"package", zh:"包裹；包", ph:"ˈpækɪdʒ", ex:"The package arrived yesterday.", exZh:"包裹昨天到達。", re:"What's inside?", reZh:"裡面是什麼？" },
{ t:"paint", zh:"油漆；繪畫", ph:"pent", ex:"Let's paint the wall blue.", exZh:"讓我們把牆漆成藍色。", re:"Blue is a nice color.", reZh:"藍色很好看。" },
{ t:"pair", zh:"一對；配對", ph:"pɛr", ex:"I bought a new pair of shoes.", exZh:"我買了一雙新鞋。", re:"What style did you choose?", reZh:"你選了什麼風格？" },
{ t:"panda", zh:"熊貓", ph:"ˈpændə", ex:"Pandas are cute and gentle.", exZh:"熊貓可愛又溫和。", re:"They're endangered animals.", reZh:"它們是瀕危動物。" },
{ t:"paper", zh:"紙", ph:"ˈpepɝ", ex:"I need paper for my project.", exZh:"我的專案需要紙。", re:"The stationery store has good paper.", reZh:"文具店有好紙。" },
{ t:"part", zh:"部分；角色", ph:"pɑrt", ex:"She plays an important part.", exZh:"她扮演重要角色。", re:"She's a talented actress.", reZh:"她是才華橫溢的女演員。" },
{ t:"pass", zh:"通過；傳遞", ph:"pæs", ex:"Can you pass me the salt?", exZh:"你能遞給我鹽嗎？", re:"Here you go.", reZh:"給你。" },
{ t:"pay", zh:"付款；支付", ph:"pe", ex:"I'll pay for the tickets.", exZh:"我會付票錢。", re:"That's very kind of you.", reZh:"你真善良。" },
{ t:"pear", zh:"梨", ph:"pɛr", ex:"This pear is sweet and juicy.", exZh:"這梨甜且多汁。", re:"Pears are my favorite fruit.", reZh:"梨是我最喜歡的水果。" },
{ t:"people", zh:"人；人民", ph:"ˈpipəl", ex:"Many people live in this city.", exZh:"很多人住在這座城市。", re:"It's a busy place.", reZh:"那是個繁忙的地方。" },
{ t:"pet", zh:"寵物；撫摸", ph:"pɛt", ex:"I have a pet dog.", exZh:"我有一隻寵物狗。", re:"What's its name?", reZh:"它叫什麼名字？" },
{ t:"pick", zh:"挑選；採摘", ph:"pɪk", ex:"Pick any toy you want.", exZh:"挑選任何你想要的玩具。", re:"This one is cool!", reZh:"這個很酷！" },
{ t:"pie", zh:"派；圓餅", ph:"paɪ", ex:"Apple pie is delicious.", exZh:"蘋果派很好吃。", re:"My grandmother makes the best pies.", reZh:"我祖母做最好的派。" },
{ t:"pig", zh:"豬", ph:"pɪg", ex:"The pig rolled in the mud.", exZh:"豬在泥裡翻滾。", re:"Farm animals are interesting.", reZh:"農場動物很有趣。" },
{ t:"pink", zh:"粉紅色", ph:"pɪŋk", ex:"She likes the color pink.", exZh:"她喜歡粉紅色。", re:"It suits her well.", reZh:"很適合她。" },
{ t:"pizza", zh:"披薩", ph:"ˈpitsə", ex:"Let's order pizza for dinner.", exZh:"讓我們訂披薩當晚餐。", re:"I love pizza!", reZh:"我愛披薩！" },
{ t:"plan", zh:"計畫；計劃", ph:"plæn", ex:"What's your plan for today?", exZh:"你今天的計畫是什麼？", re:"I haven't decided yet.", reZh:"我還沒決定。" },
{ t:"player", zh:"運動員；播放者", ph:"ˈpleɝ", ex:"He's a great soccer player.", exZh:"他是個很好的足球運動員。", re:"I wish I could play like him.", reZh:"我希望我能像他一樣玩。" },
{ t:"pocket", zh:"口袋", ph:"ˈpɑkɪt", ex:"I put the coins in my pocket.", exZh:"我把硬幣放在口袋裡。", re:"Be careful not to lose them.", reZh:"小心別丟了。" },
{ t:"police", zh:"警察", ph:"pəˈlis", ex:"The police officer helped us.", exZh:"警察幫助了我們。", re:"Police keep us safe.", reZh:"警察保護我們。" },
{ t:"pond", zh:"池塘", ph:"pɑnd", ex:"There are fish in the pond.", exZh:"池塘裡有魚。", re:"I like watching them swim.", reZh:"我喜歡看它們游泳。" },
{ t:"pool", zh:"游泳池；水池", ph:"pul", ex:"Let's go to the swimming pool.", exZh:"讓我們去游泳池。", re:"I love swimming!", reZh:"我喜歡游泳！" },
{ t:"popcorn", zh:"爆米花", ph:"ˈpɑpˌkɔrn", ex:"I bought popcorn at the movies.", exZh:"我在電影院買了爆米花。", re:"Popcorn is perfect for watching films.", reZh:"爆米花很適合看電影。" },
{ t:"pork", zh:"豬肉", ph:"pɔrk", ex:"I don't eat pork.", exZh:"我不吃豬肉。", re:"I respect that.", reZh:"我尊重。" },
{ t:"postcard", zh:"明信片", ph:"ˈpostˌkɑrd", ex:"I sent a postcard from vacation.", exZh:"我從假期寄了明信片。", re:"That's a nice tradition.", reZh:"那是個好傳統。" },
{ t:"potato", zh:"馬鈴薯", ph:"pəˈteto", ex:"Baked potato is yummy.", exZh:"烤馬鈴薯好吃。", re:"My favorite is mashed potato.", reZh:"我最喜歡馬鈴薯泥。" },
{ t:"prepare", zh:"準備", ph:"prɪˈpɛr", ex:"Let me prepare dinner.", exZh:"讓我準備晚餐。", re:"Need any help?", reZh:"需要幫助嗎？" },
{ t:"present", zh:"禮物；現在；出現", ph:"ˈprɛzənt", ex:"I got a nice present for my birthday.", exZh:"我生日收到了很好的禮物。", re:"What was it?", reZh:"是什麼？" },
] },
{ level: 6, words: [
{ t:"price", zh:"價格", ph:"praɪs", ex:"The price is too high.", exZh:"價格太高了。", re:"Let's look for a better deal.", reZh:"讓我們找更好的。" },
{ t:"princess", zh:"公主", ph:"ˈprɪnsɛs", ex:"The princess lived in a castle.", exZh:"公主住在城堡裡。", re:"That sounds like a fairy tale.", reZh:"聽起來像童話。" },
{ t:"problem", zh:"問題", ph:"ˈprɑbləm", ex:"I have a problem with math.", exZh:"我在數學上有問題。", re:"Let me help you.", reZh:"讓我幫你。" },
{ t:"pull", zh:"拉；拖", ph:"pʊl", ex:"Pull the door to open it.", exZh:"拉門打開它。", re:"It's heavy.", reZh:"它很重。" },
{ t:"puppy", zh:"小狗；幼犬", ph:"ˈpʌpi", ex:"The puppy is so cute!", exZh:"小狗太可愛了！", re:"I want to take it home.", reZh:"我想把它帶回家。" },
{ t:"purple", zh:"紫色", ph:"ˈpɝpəl", ex:"She wore a purple dress.", exZh:"她穿著紫色連衣裙。", re:"It's a beautiful color.", reZh:"那是很美的顏色。" },
{ t:"queen", zh:"皇后；王后", ph:"kwin", ex:"The queen wore a crown.", exZh:"皇后戴著王冠。", re:"She looked majestic.", reZh:"她看起來威嚴。" },
{ t:"quick", zh:"快速的", ph:"kwɪk", ex:"Make a quick decision.", exZh:"做一個快速決定。", re:"Don't overthink it.", reZh:"不要想太多。" },
{ t:"rabbit", zh:"兔子", ph:"ˈræbɪt", ex:"The rabbit hopped across the field.", exZh:"兔子在田野裡跳躍。", re:"Rabbits are so cute.", reZh:"兔子很可愛。" },
{ t:"rainbow", zh:"彩虹", ph:"ˈrenˌbo", ex:"The rainbow appeared after the rain.", exZh:"雨後出現了彩虹。", re:"It was so beautiful!", reZh:"太漂亮了！" },
{ t:"raise", zh:"抬起；飼養", ph:"rez", ex:"Raise your hand to answer.", exZh:"舉手回答。", re:"I think I know this one.", reZh:"我想我知道。" },
{ t:"real", zh:"真實的；真的", ph:"ˈril", ex:"Is this a real diamond?", exZh:"這是真鑽石嗎？", re:"No, it's just glass.", reZh:"不，只是玻璃。" },
{ t:"refrigerator", zh:"冰箱", ph:"rɪˈfrɪdʒəˌretɝ", ex:"Put the milk in the refrigerator.", exZh:"把牛奶放進冰箱。", re:"It'll keep it cold.", reZh:"這樣它會冷。" },
{ t:"repeat", zh:"重複", ph:"rɪˈpit", ex:"Please repeat what I said.", exZh:"請重複我說的。", re:"I didn't understand the first time.", reZh:"我第一次沒聽懂。" },
{ t:"restaurant", zh:"餐廳", ph:"ˈrɛstɚˌɑnt", ex:"We ate at a nice restaurant.", exZh:"我們在一家不錯的餐廳吃飯。", re:"How was the food?", reZh:"食物怎麼樣？" },
{ t:"return", zh:"返回；回歸", ph:"rɪˈtɝn", ex:"When will you return?", exZh:"你什麼時候回來？", re:"I'll be back by evening.", reZh:"我晚上會回來。" },
{ t:"rich", zh:"富有的；豐富的", ph:"rɪtʃ", ex:"He comes from a rich family.", exZh:"他來自富有的家庭。", re:"Money doesn't buy happiness though.", reZh:"但錢買不到幸福。" },
{ t:"ride", zh:"騎；乘坐", ph:"raɪd", ex:"I ride my bike to school.", exZh:"我騎自行車上學。", re:"That's good exercise.", reZh:"那很好的運動。" },
{ t:"rise", zh:"上升；起身", ph:"raɪz", ex:"The sun rises at six in the morning.", exZh:"太陽早上六點升起。", re:"That's very early.", reZh:"那很早。" },
{ t:"robot", zh:"機器人", ph:"ˈrobɑt", ex:"The robot can do many tasks.", exZh:"機器人可以做很多工作。", re:"Technology is amazing.", reZh:"技術很令人驚嘆。" },
{ t:"roll", zh:"滾動；捲；麵包", ph:"rol", ex:"The ball will roll down the hill.", exZh:"球會滾下山。", re:"Be careful it doesn't get lost.", reZh:"小心別丟了。" },
{ t:"rope", zh:"繩子", ph:"rop", ex:"Jump rope is fun exercise.", exZh:"跳繩是有趣的運動。", re:"Let's jump together.", reZh:"讓我們一起跳。" },
{ t:"round", zh:"圓的；輪", ph:"raʊnd", ex:"The table is round.", exZh:"桌子是圓的。", re:"It's perfect for dinner.", reZh:"很適合吃飯。" },
{ t:"row", zh:"行；列；划", ph:"ro", ex:"Sit in the third row.", exZh:"坐在第三排。", re:"Can I sit next to you?", reZh:"我能坐你旁邊嗎？" },
{ t:"rush", zh:"急忙；衝", ph:"rʌʃ", ex:"Don't rush. Take your time.", exZh:"別急。慢慢來。", re:"OK, I'm taking it easy.", reZh:"好的，我慢點。" },
{ t:"salad", zh:"沙拉", ph:"ˈsæləd", ex:"I like eating fresh salad.", exZh:"我喜歡吃新鮮沙拉。", re:"Salad is very healthy.", reZh:"沙拉很健康。" },
{ t:"salt", zh:"鹽", ph:"sɔlt", ex:"Please pass the salt.", exZh:"請遞鹽給我。", re:"The food needs more salt.", reZh:"食物需要更多鹽。" },
{ t:"sandwich", zh:"三明治", ph:"ˈsændˌwɪtʃ", ex:"I made a sandwich for lunch.", exZh:"我為午餐做了三明治。", re:"What kind of filling?", reZh:"什麼餡料？" },
{ t:"scared", zh:"害怕的；驚嚇", ph:"skɛrd", ex:"Don't be scared of the dark.", exZh:"不要害怕黑暗。", re:"I'll be here with you.", reZh:"我會和你在一起。" },
{ t:"scarf", zh:"圍巾；頭巾", ph:"skɑrf", ex:"Wear a scarf. It's cold.", exZh:"戴圍巾。很冷。", re:"Thanks for the reminder.", reZh:"謝謝提醒。" },
{ t:"scooter", zh:"滑板車", ph:"ˈskutɝ", ex:"I ride my scooter to the park.", exZh:"我騎滑板車到公園。", re:"That's a fun way to travel.", reZh:"那是有趣的旅行方式。" },
{ t:"sea", zh:"海", ph:"si", ex:"The sea is beautiful in summer.", exZh:"海在夏天很漂亮。", re:"I love the sound of the waves.", reZh:"我喜歡波浪的聲音。" },
{ t:"seat", zh:"座位", ph:"sit", ex:"Take a seat and relax.", exZh:"坐下放鬆。", re:"Thanks, I'm a bit tired.", reZh:"謝謝，我有點累。" },
{ t:"secret", zh:"秘密", ph:"ˈsikrɪt", ex:"I'll keep your secret.", exZh:"我會保守你的秘密。", re:"Thanks. I trust you.", reZh:"謝謝。我相信你。" },
{ t:"sell", zh:"賣；出售", ph:"sɛl", ex:"We sell books at the shop.", exZh:"我們在商店賣書。", re:"Do you have any recommendations?", reZh:"你有推薦嗎？" },
{ t:"send", zh:"寄送；發送", ph:"sɛnd", ex:"I'll send you an email.", exZh:"我會給你寄電子郵件。", re:"Great! I'll wait for it.", reZh:"太好了！我等著。" },
{ t:"sentence", zh:"句子", ph:"ˈsɛntəns", ex:"Write a complete sentence.", exZh:"寫一個完整句子。", re:"Make sure it has a subject and verb.", reZh:"確保它有主語和動詞。" },
{ t:"seventy", zh:"七十", ph:"ˈsɛvənti", ex:"My grandfather is seventy years old.", exZh:"我祖父七十歲。", re:"He's still very active.", reZh:"他仍然很活躍。" },
{ t:"shape", zh:"形狀", ph:"ʃep", ex:"This shape is a square.", exZh:"這個形狀是正方形。", re:"Can you name other shapes?", reZh:"你能說出其他形狀嗎？" },
{ t:"shark", zh:"鯊魚", ph:"ʃɑrk", ex:"The shark swam past us.", exZh:"鯊魚游過我們身邊。", re:"Were you scared?", reZh:"你害怕嗎？" },
{ t:"shine", zh:"發光；照耀", ph:"ʃaɪn", ex:"The stars shine brightly.", exZh:"星星閃爍明亮。", re:"They're beautiful tonight.", reZh:"今晚很漂亮。" },
{ t:"ship", zh:"船；運送", ph:"ʃɪp", ex:"The ship sailed across the ocean.", exZh:"船穿過大洋航行。", re:"That must have been a long journey.", reZh:"那一定是個長旅程。" },
{ t:"shoe", zh:"鞋", ph:"ʃu", ex:"These shoes are very comfortable.", exZh:"這些鞋很舒服。", re:"I need new shoes too.", reZh:"我也需要新鞋。" },
{ t:"shout", zh:"喊叫；大聲說", ph:"ʃaʊt", ex:"Don't shout in the library.", exZh:"不要在圖書館裡喊叫。", re:"Sorry. I'll be quiet.", reZh:"對不起。我會安靜。" },
{ t:"shower", zh:"淋浴；陣雨", ph:"ˈʃaʊɝ", ex:"I take a shower every morning.", exZh:"我每天早上洗澡。", re:"That's good for your health.", reZh:"那對健康有好處。" },
{ t:"side", zh:"側面；邊", ph:"saɪd", ex:"Stand by my side.", exZh:"站在我身邊。", re:"I'll always be here for you.", reZh:"我永遠為你在這裡。" },
{ t:"simple", zh:"簡單的", ph:"ˈsɪmpəl", ex:"The math problem is simple.", exZh:"數學問題很簡單。", re:"I solved it in my head.", reZh:"我在腦子裡解決了。" },
{ t:"singer", zh:"歌手", ph:"ˈsɪŋɝ", ex:"She is a professional singer.", exZh:"她是職業歌手。", re:"Her voice is beautiful.", reZh:"她的聲音很美。" },
{ t:"sixteen", zh:"十六", ph:"ˌsɪksˈtin", ex:"I'll be sixteen next month.", exZh:"下個月我十六歲。", re:"That's exciting!", reZh:"那很興奮！" },
{ t:"size", zh:"大小；尺寸", ph:"saɪz", ex:"What size shoes do you wear?", exZh:"你穿多大的鞋？", re:"I wear size nine.", reZh:"我穿九號。" },
] },
{ level: 7, words: [
{ t:"ski", zh:"滑雪；滑雪板", ph:"ski", ex:"I love to ski in winter.", exZh:"我喜歡冬天滑雪。", re:"Have you been to the mountains?", reZh:"你去過山區嗎？" },
{ t:"smart", zh:"聰明的；時尚的", ph:"smɑrt", ex:"She is very smart in school.", exZh:"她在學校很聰明。", re:"And she works hard too.", reZh:"而且她也很努力。" },
{ t:"smile", zh:"微笑；笑容", ph:"smaɪl", ex:"She smiled at the baby.", exZh:"她對嬰兒微笑。", re:"Babies love smiles.", reZh:"嬰兒喜歡微笑。" },
{ t:"snack", zh:"零食；小吃", ph:"snæk", ex:"Would you like a snack?", exZh:"你想要零食嗎？", re:"I'm hungry actually.", reZh:"其實我餓了。" },
{ t:"snake", zh:"蛇", ph:"snek", ex:"The snake slithered across the ground.", exZh:"蛇在地上爬行。", re:"I'm glad they're not dangerous.", reZh:"我很高興它們不危險。" },
{ t:"sock", zh:"襪子", ph:"sɑk", ex:"I lost a sock in the wash.", exZh:"我在洗衣時丟了一隻襪子。", re:"Socks always disappear.", reZh:"襪子總是消失。" },
{ t:"soft", zh:"軟的；柔軟", ph:"sɔft", ex:"This pillow is very soft.", exZh:"這個枕頭很軟。", re:"Perfect for a good night's sleep.", reZh:"完美睡眠。" },
{ t:"somebody", zh:"某人", ph:"ˈsʌmbədi", ex:"Somebody left the door open.", exZh:"有人把門開著。", re:"We should close it.", reZh:"我們應該關上。" },
{ t:"something", zh:"某物；某事", ph:"ˈsʌmˌθɪŋ", ex:"There's something in your hair.", exZh:"你頭髮裡有東西。", re:"Let me get it out.", reZh:"讓我弄出來。" },
{ t:"son", zh:"兒子", ph:"sʌn", ex:"He's a good son to his parents.", exZh:"他是父母的好兒子。", re:"They're very proud of him.", reZh:"他們為他感到驕傲。" },
{ t:"song", zh:"歌曲；歌", ph:"sɔŋ", ex:"I love that song.", exZh:"我喜歡那首歌。", re:"It's stuck in my head.", reZh:"它在我腦子裡。" },
{ t:"sound", zh:"聲音", ph:"saʊnd", ex:"I heard a strange sound.", exZh:"我聽到奇怪的聲音。", re:"What was it?", reZh:"是什麼？" },
{ t:"sour", zh:"酸的；酸味", ph:"ˈsaʊɝ", ex:"This lemon is very sour.", exZh:"這個檸檬很酸。", re:"My mouth puckered up.", reZh:"我的嘴皺起來了。" },
{ t:"space", zh:"空間；太空", ph:"spes", ex:"We learned about space in science class.", exZh:"我們在科學課上學到太空。", re:"It's fascinating.", reZh:"很有魅力。" },
{ t:"spell", zh:"拼寫；咒語", ph:"spɛl", ex:"Can you spell this word?", exZh:"你能拼這個詞嗎？", re:"S-P-E-L-L.", reZh:"S-P-E-L-L。" },
{ t:"spider", zh:"蜘蛛", ph:"ˈspaɪdɝ", ex:"The spider built a beautiful web.", exZh:"蜘蛛築了美麗的網。", re:"I'm afraid of spiders.", reZh:"我怕蜘蛛。" },
{ t:"sport", zh:"運動；體育", ph:"spɔrt", ex:"My favorite sport is basketball.", exZh:"我最喜歡的運動是籃球。", re:"I love watching games.", reZh:"我喜歡看比賽。" },
{ t:"square", zh:"正方形；廣場", ph:"skwɛr", ex:"The town square is very big.", exZh:"鎮廣場很大。", re:"There's always something happening.", reZh:"總有事情在發生。" },
{ t:"stamp", zh:"郵票；跺腳", ph:"stæmp", ex:"Put a stamp on the envelope.", exZh:"在信封上貼郵票。", re:"It goes in the corner.", reZh:"在角落。" },
{ t:"station", zh:"車站；站", ph:"ˈsteʃən", ex:"The train station is downtown.", exZh:"火車站在市中心。", re:"How often do trains come?", reZh:"多久來一班？" },
{ t:"steak", zh:"牛排；牛肉", ph:"stek", ex:"I ordered a steak for dinner.", exZh:"我訂了牛排晚餐。", re:"How was it?", reZh:"怎麼樣？" },
{ t:"still", zh:"仍然；靜止", ph:"stɪl", ex:"He is still sleeping.", exZh:"他仍然在睡覺。", re:"Let him rest.", reZh:"讓他休息。" },
{ t:"stomach", zh:"肚子；胃", ph:"ˈstʌmək", ex:"My stomach hurts after eating too much.", exZh:"吃太多後我的肚子疼。", re:"You should rest and drink water.", reZh:"你應該休息喝水。" },
{ t:"story", zh:"故事；樓層", ph:"ˈstɔri", ex:"Tell me a story before bed.", exZh:"睡前給我講個故事。", re:"I love listening to your stories.", reZh:"我喜歡聽你的故事。" },
{ t:"strawberry", zh:"草莓", ph:"ˈstrɔˌbɛri", ex:"I picked a strawberry from the garden.", exZh:"我從花園裡摘了一個草莓。", re:"It's so sweet!", reZh:"它很甜！" },
{ t:"stranger", zh:"陌生人", ph:"ˈstrendʒɝ", ex:"Don't talk to strangers.", exZh:"不要和陌生人交談。", re:"That's good safety advice.", reZh:"那是好的安全建議。" },
{ t:"sugar", zh:"糖", ph:"ˈʃʊgɝ", ex:"Sugar makes things sweet.", exZh:"糖使事物變甜。", re:"But it's not good for your teeth.", reZh:"但對牙齒不好。" },
{ t:"super", zh:"超級的；超級市場", ph:"ˈsupɝ", ex:"That's a super idea!", exZh:"那是個超級主意！", re:"Let's do it now!", reZh:"讓我們現在做！" },
{ t:"supermarket", zh:"超級市場", ph:"ˈsupɝˌmɑrkɪt", ex:"Let's go to the supermarket.", exZh:"讓我們去超級市場。", re:"I need to buy groceries.", reZh:"我需要買雜貨。" },
{ t:"surprise", zh:"驚喜；驚訝", ph:"sɝˈpraɪz", ex:"I have a surprise for you.", exZh:"我有驚喜給你。", re:"Really? What is it?", reZh:"真的？是什麼？" },
{ t:"sweater", zh:"毛衣；針織衫", ph:"ˈswɛtɝ", ex:"I wore a warm sweater.", exZh:"我穿著溫暖的毛衣。", re:"It's cozy and comfortable.", reZh:"它舒服又舒適。" },
{ t:"swim", zh:"游泳", ph:"swɪm", ex:"I swim in the pool every week.", exZh:"我每週在池子裡游泳。", re:"Swimming is great exercise.", reZh:"游泳是很好的運動。" },
{ t:"tail", zh:"尾巴", ph:"tel", ex:"The dog wagged its tail.", exZh:"狗搖著尾巴。", re:"It looked so happy.", reZh:"它看起來很開心。" },
{ t:"taste", zh:"味道；品嚐", ph:"test", ex:"What does it taste like?", exZh:"它嚐起來怎麼樣？", re:"It tastes sweet and delicious.", reZh:"嚐起來很甜很好吃。" },
{ t:"taxi", zh:"出租車；計程車", ph:"ˈtæksi", ex:"Let's take a taxi to the airport.", exZh:"讓我們搭計程車去機場。", re:"That's a good idea.", reZh:"好主意。" },
{ t:"teenager", zh:"青少年", ph:"ˈtiˌnedʒɝ", ex:"She is a teenager now.", exZh:"她現在是青少年。", re:"Growing up is interesting.", reZh:"成長很有趣。" },
{ t:"tell", zh:"告訴；講", ph:"tɛl", ex:"Tell me what happened.", exZh:"告訴我發生了什麼。", re:"I'll explain everything.", reZh:"我會解釋一切。" },
{ t:"tennis", zh:"網球", ph:"ˈtɛnɪs", ex:"I play tennis on weekends.", exZh:"我週末打網球。", re:"That's great exercise.", reZh:"那很好的運動。" },
{ t:"terrible", zh:"可怕的；糟糕的", ph:"ˈtɛrəbəl", ex:"That was a terrible movie.", exZh:"那是個可怕的電影。", re:"I agree. Let's leave.", reZh:"我同意。讓我們離開。" },
{ t:"than", zh:"比", ph:"ðæn", ex:"This is bigger than that.", exZh:"這個比那個大。", re:"You're right.", reZh:"你說得對。" },
{ t:"theater", zh:"劇院；戲院", ph:"ˈθiətɝ", ex:"We went to the theater last night.", exZh:"我們昨晚去了劇院。", re:"What did you watch?", reZh:"你看了什麼？" },
{ t:"thing", zh:"東西；事情", ph:"θɪŋ", ex:"I have many things to do.", exZh:"我有很多事要做。", re:"You're so busy!", reZh:"你真忙！" },
{ t:"thirteen", zh:"十三", ph:"ˌθɝˈtin", ex:"I'm thirteen years old.", exZh:"我十三歲。", re:"You're getting older!", reZh:"你長大了！" },
{ t:"thousand", zh:"一千", ph:"ˈθaʊzənd", ex:"There are a thousand stars.", exZh:"有一千顆星星。", re:"It's impossible to count them.", reZh:"不可能數完。" },
{ t:"ticket", zh:"票；車票", ph:"ˈtɪkɪt", ex:"I bought two tickets for the movie.", exZh:"我買了兩張電影票。", re:"Great! When should we go?", reZh:"很好！我們什麼時候去？" },
{ t:"tiger", zh:"老虎", ph:"ˈtaɪgɝ", ex:"The tiger is a powerful animal.", exZh:"老虎是強大的動物。", re:"They're endangered species.", reZh:"它們是瀕危物種。" },
{ t:"toast", zh:"吐司；敬酒", ph:"tost", ex:"I ate toast for breakfast.", exZh:"我早餐吃了吐司。", re:"Did you put butter on it?", reZh:"你在上面塗黃油了嗎？" },
{ t:"tofu", zh:"凝乳蛋白", ph:"ˈtofu", ex:"Tofu is a healthy protein.", exZh:"這是健康的蛋白質食物。", re:"I like eating tofu.", reZh:"我喜歡吃它。" },
{ t:"tomato", zh:"番茄；西紅柿", ph:"təˈmeto", ex:"I put tomatoes in my salad.", exZh:"我在沙拉裡放番茄。", re:"Fresh tomatoes taste better.", reZh:"新鮮番茄味道更好。" },
{ t:"tooth", zh:"牙齒；牙", ph:"tuθ", ex:"I lost a tooth.", exZh:"我掉了一顆牙。", re:"It will grow back.", reZh:"它會長回來。" },
] },
{ level: 8, words: [
{ t:"touch", zh:"觸摸；接觸", ph:"tʌtʃ", ex:"Don't touch that!", exZh:"不要碰那個！", re:"It's dangerous.", reZh:"它很危險。" },
{ t:"tower", zh:"塔；高塔", ph:"ˈtaʊɝ", ex:"The tower is very tall.", exZh:"塔很高。", re:"You can see the whole city from the top.", reZh:"從頂部可以看到整個城市。" },
{ t:"town", zh:"城鎮；城市", ph:"taʊn", ex:"This is a small town.", exZh:"這是一個小城鎮。", re:"Everyone knows each other.", reZh:"大家都彼此認識。" },
{ t:"trash", zh:"垃圾；廢物", ph:"træʃ", ex:"Put the trash in the bin.", exZh:"把垃圾放進桶裡。", re:"Don't litter.", reZh:"不要亂扔垃圾。" },
{ t:"treat", zh:"對待；款待；待遇", ph:"trit", ex:"How does he treat you?", exZh:"他怎樣對待你？", re:"He treats me very well.", reZh:"他對我很好。" },
{ t:"trick", zh:"把戲；伎倆", ph:"trɪk", ex:"He performed a magic trick.", exZh:"他表演了魔術。", re:"That was impressive!", reZh:"那很令人印象深刻！" },
{ t:"trouble", zh:"麻煩；困難", ph:"ˈtrʌbəl", ex:"I'm having trouble with my computer.", exZh:"我的電腦有麻煩。", re:"Do you need help?", reZh:"你需要幫助嗎？" },
{ t:"true", zh:"真的；真實", ph:"tru", ex:"Is it true?", exZh:"是真的嗎？", re:"Yes, absolutely.", reZh:"是的，絕對是。" },
{ t:"try", zh:"嘗試；試", ph:"traɪ", ex:"Try your best.", exZh:"盡力而為。", re:"I will do my best.", reZh:"我會盡力。" },
{ t:"turtle", zh:"烏龜；海龜", ph:"ˈtɝtəl", ex:"The turtle is moving slowly.", exZh:"烏龜動作很慢。", re:"Slow and steady wins the race.", reZh:"慢而穩定贏得比賽。" },
{ t:"twenty", zh:"二十", ph:"ˈtwɛnti", ex:"I have twenty books.", exZh:"我有二十本書。", re:"That's a lot!", reZh:"那很多！" },
{ t:"typhoon", zh:"颱風", ph:"ˈtaɪˌfun", ex:"A typhoon is coming.", exZh:"颱風要來了。", re:"We should stay safe inside.", reZh:"我們應該呆在裡面保持安全。" },
{ t:"uncle", zh:"叔叔；舅舅", ph:"ˈʌŋkəl", ex:"My uncle is visiting us.", exZh:"我叔叔要拜訪我們。", re:"How long will he stay?", reZh:"他要留多久？" },
{ t:"understand", zh:"理解；明白", ph:"ˌʌndɝˈstænd", ex:"Do you understand the question?", exZh:"你明白問題嗎？", re:"Yes, I think so.", reZh:"是的，我想是。" },
{ t:"uniform", zh:"制服", ph:"ˈjunəˌfɔrm", ex:"I wear a uniform to school.", exZh:"我穿著制服上學。", re:"It looks smart.", reZh:"看起來很精明。" },
{ t:"up", zh:"上；向上", ph:"ʌp", ex:"Look up at the sky.", exZh:"抬頭看天空。", re:"The clouds look beautiful.", reZh:"雲看起來很漂亮。" },
{ t:"use", zh:"使用；用", ph:"juz", ex:"Use this pencil.", exZh:"用這支鉛筆。", re:"Thanks, it works great.", reZh:"謝謝，效果很好。" },
{ t:"vacation", zh:"假期；休假", ph:"veˈkeʃən", ex:"We're going on vacation next month.", exZh:"我們下個月去度假。", re:"Where will you go?", reZh:"你要去哪裡？" },
{ t:"video", zh:"視頻；錄像", ph:"ˈvɪdio", ex:"I watched a video online.", exZh:"我在線上看了一個視頻。", re:"What was it about?", reZh:"它是關於什麼的？" },
{ t:"violin", zh:"小提琴", ph:"ˌvaɪəˈlɪn", ex:"She plays the violin beautifully.", exZh:"她小提琴拉得很美。", re:"I'd love to learn.", reZh:"我想學。" },
{ t:"visit", zh:"訪問；參觀", ph:"ˈvɪzɪt", ex:"Let's visit the museum tomorrow.", exZh:"讓我們明天去參觀博物館。", re:"That sounds fun!", reZh:"聽起來很好玩！" },
{ t:"voice", zh:"聲音；嗓音", ph:"vɔɪs", ex:"She has a beautiful voice.", exZh:"她有美麗的聲音。", re:"I love listening to her sing.", reZh:"我喜歡聽她唱歌。" },
{ t:"waitress", zh:"女服務員", ph:"ˈwetrɪs", ex:"The waitress brought us the menu.", exZh:"女服務員給我們帶來了菜單。", re:"She was very helpful.", reZh:"她很有幫助。" },
{ t:"wallet", zh:"錢包", ph:"ˈwɑlɪt", ex:"I lost my wallet.", exZh:"我丟了錢包。", re:"Oh no! Did you find it?", reZh:"哎呀！你找到了嗎？" },
{ t:"wave", zh:"波浪；揮手", ph:"wev", ex:"The waves are high today.", exZh:"今天波浪很高。", re:"It's good for surfing.", reZh:"很適合衝浪。" },
{ t:"wear", zh:"穿著；戴", ph:"wɛr", ex:"I wear glasses.", exZh:"我戴眼鏡。", re:"They look good on you.", reZh:"它們在你身上看起來不錯。" },
{ t:"weather", zh:"天氣", ph:"ˈwɛðɝ", ex:"The weather is beautiful today.", exZh:"今天天氣很美。", re:"Perfect for a picnic.", reZh:"很適合野餐。" },
{ t:"well", zh:"好的；井", ph:"wɛl", ex:"She sings very well.", exZh:"她唱得很好。", re:"She should join the choir.", reZh:"她應該加入唱詩班。" },
{ t:"wet", zh:"濕的", ph:"wɛt", ex:"My hair is wet.", exZh:"我的頭髮濕了。", re:"Did you go swimming?", reZh:"你去游泳了嗎？" },
{ t:"wheel", zh:"輪子；方向盤", ph:"wil", ex:"The wheel is turning.", exZh:"輪子在轉動。", re:"The bicycle needs a new one.", reZh:"自行車需要新的。" },
{ t:"win", zh:"贏；獲勝", ph:"wɪn", ex:"We will win the game.", exZh:"我們會贏得比賽。", re:"I hope so!", reZh:"我希望如此！" },
{ t:"winner", zh:"獲勝者；贏家", ph:"ˈwɪnɝ", ex:"The winner receives a prize.", exZh:"獲勝者獲得獎勵。", re:"Congratulations on winning!", reZh:"獲勝恭喜！" },
{ t:"winter", zh:"冬季；冬天", ph:"ˈwɪntɝ", ex:"Winter is my favorite season.", exZh:"冬季是我最喜歡的季節。", re:"Because of the snow?", reZh:"因為下雪？" },
{ t:"wish", zh:"願望；希望；祝願", ph:"wɪʃ", ex:"I wish I could fly.", exZh:"我希望我能飛。", re:"That would be amazing!", reZh:"那將是了不起的！" },
{ t:"wonderful", zh:"精彩的；很好的", ph:"ˈwʌndɝfəl", ex:"What a wonderful day!", exZh:"多麼美妙的一天！", re:"I'll remember it forever.", reZh:"我永遠會記住。" },
{ t:"word", zh:"詞語；單詞", ph:"wɝd", ex:"Learn a new word every day.", exZh:"每天學習一個新詞。", re:"That's a good habit.", reZh:"那是個好習慣。" },
{ t:"worry", zh:"擔心；煩惱", ph:"ˈwɝi", ex:"Don't worry about it.", exZh:"不用擔心。", re:"I'll help you solve it.", reZh:"我會幫你解決。" },
{ t:"yogurt", zh:"酸奶；優格", ph:"ˈjogɝt", ex:"I eat yogurt for breakfast.", exZh:"我早餐吃酸奶。", re:"It's very healthy.", reZh:"很健康。" },
{ t:"young", zh:"年輕的", ph:"jʌŋ", ex:"She is young and energetic.", exZh:"她年輕且充滿活力。", re:"Yes, she has great potential.", reZh:"是的，她有很大潛力。" },
{ t:"zebra", zh:"斑馬", ph:"ˈzɛbrə", ex:"The zebra has black and white stripes.", exZh:"斑馬有黑白條紋。", re:"Nature makes beautiful patterns.", reZh:"自然製造美麗的圖案。" },
{ t:"Monday", zh:"星期一", ph:"ˈmʌnde", ex:"Monday is the first day of the week.", exZh:"星期一是一週的第一天。", re:"I don't like Mondays.", reZh:"我不喜歡星期一。" },
{ t:"Wednesday", zh:"星期三", ph:"ˈwɛnzde", ex:"I have a test on Wednesday.", exZh:"我週三有考試。", re:"Good luck!", reZh:"祝你好運！" },
{ t:"Friday", zh:"星期五", ph:"ˈfraɪde", ex:"Friday is my favorite day.", exZh:"星期五是我最喜歡的日子。", re:"The weekend is coming!", reZh:"週末要來了！" },
{ t:"Sunday", zh:"星期日；星期天", ph:"ˈsʌnde", ex:"We go to church on Sunday.", exZh:"我們週日去教堂。", re:"It's a day of rest.", reZh:"這是休息的日子。" },
{ t:"January", zh:"一月", ph:"ˈdʒænjuˌwɛri", ex:"January is the first month.", exZh:"一月是第一個月。", re:"It's the start of a new year.", reZh:"這是新年的開始。" },
{ t:"March", zh:"三月", ph:"mɑrtʃ", ex:"March comes after February.", exZh:"三月在二月之後。", re:"Spring is coming soon.", reZh:"春天快要來了。" },
{ t:"May", zh:"五月", ph:"me", ex:"May is a beautiful month.", exZh:"五月是美麗的月份。", re:"The flowers bloom in May.", reZh:"花在五月開放。" },
{ t:"July", zh:"七月", ph:"dʒuˈlaɪ", ex:"July is usually very hot.", exZh:"七月通常很熱。", re:"Perfect for swimming.", reZh:"很適合游泳。" },
{ t:"September", zh:"九月", ph:"sɛpˈtɛmbɝ", ex:"School starts in September.", exZh:"學校在九月開始。", re:"I'm excited for the new year.", reZh:"我對新學年感到興奮。" },
{ t:"November", zh:"十一月", ph:"noˈvɛmbɝ", ex:"November is getting cold.", exZh:"十一月變冷了。", re:"Winter is around the corner.", reZh:"冬天快要來了。" },
] },
];
