// 內建國中中階單字包 — 8 級 × 50 字，每字附例句＋回覆句（國中中階程度生活日常對話）
// 欄位：t=單字 zh=中文 ph=音標 ex=例句 exZh=例句中文 re=回覆句 reZh=回覆句中文
const JHS2_PACK = [
{ level: 1, words: [
{ t:"able", zh:"能夠的", ph:"ˈebl", ex:"She is able to speak three languages very well.", exZh:"她能把三種語言說得很好。", re:"That is really impressive to me.", reZh:"那真的令我佩服。" },
{ t:"absent", zh:"缺席的", ph:"ˈæbsənt", ex:"He was absent from school because he caught a cold.", exZh:"他因為感冒沒去上學。", re:"I hope he gets well soon.", reZh:"希望他早日康復。" },
{ t:"accident", zh:"意外", ph:"ˈæksɪdənt", ex:"There was a car accident near the school gate.", exZh:"學校大門旁發生了一起車禍。", re:"I hope nobody was badly hurt.", reZh:"希望沒有人受重傷。" },
{ t:"activity", zh:"活動", ph:"ækˈtɪvəti", ex:"Our class is planning an outdoor activity for Friday.", exZh:"我們班正在規劃星期五的戶外活動。", re:"I hope the weather stays sunny.", reZh:"希望天氣保持晴朗。" },
{ t:"actress", zh:"女演員", ph:"ˈæktrəs", ex:"That famous actress won a big award last night.", exZh:"那位知名女演員昨晚獲得大獎。", re:"She truly deserves the honor.", reZh:"她實至名歸。" },
{ t:"advice", zh:"建議", ph:"ədˈvaɪs", ex:"My teacher gave me useful advice about studying English.", exZh:"老師給了我讀英文的實用建議。", re:"Good advice can change everything.", reZh:"好建議能改變一切。" },
{ t:"allow", zh:"允許", ph:"əˈlaʊ", ex:"My parents allow me to play games on weekends.", exZh:"我爸媽允許我週末打電動。", re:"That sounds like a fair rule.", reZh:"聽起來是公平的規定。" },
{ t:"among", zh:"在...之中", ph:"əˈmʌŋ", ex:"She is the tallest girl among all her classmates.", exZh:"她是所有同學中最高的女生。", re:"She should join the basketball team.", reZh:"她應該加入籃球隊。" },
{ t:"angle", zh:"角度", ph:"ˈæŋgəl", ex:"Draw a right angle with your ruler and pencil.", exZh:"用尺和鉛筆畫一個直角。", re:"Math tools make drawing easier.", reZh:"數學工具使畫圖更容易。" },
{ t:"anyway", zh:"無論如何", ph:"ˈɛniˌwe", ex:"It rained, but we enjoyed the picnic anyway.", exZh:"雖然下雨，我們野餐野得照樣開心。", re:"A little rain never stops fun.", reZh:"一場小雨擋不住樂趣。" },
{ t:"apply", zh:"申請", ph:"əˈplaɪ", ex:"I plan to apply for the school music club.", exZh:"我打算申請加入學校音樂社。", re:"Good luck, I hope you get in.", reZh:"祝你好運，希望你入社成功。" },
{ t:"argue", zh:"爭論", ph:"ˈɑrgju", ex:"Please do not argue with your brother over toys.", exZh:"請不要為了玩具和弟弟吵架。", re:"They should learn to share things.", reZh:"他們該學著分享。" },
{ t:"arrival", zh:"到達", ph:"əˈraɪvəl", ex:"The arrival of the train was delayed thirty minutes.", exZh:"火車的到站延誤了三十分鐘。", re:"Waiting that long is really annoying.", reZh:"等那麼久真的很煩。" },
{ t:"assistant", zh:"助手", ph:"əˈsɪstənt", ex:"The assistant helped the doctor prepare for the checkup.", exZh:"助理幫醫生準備健康檢查。", re:"Teamwork makes everything run smoothly.", reZh:"分工合作使一切順利。" },
{ t:"attend", zh:"參加", ph:"əˈtɛnd", ex:"All students must attend the morning meeting at eight.", exZh:"所有學生必須參加八時的朝會。", re:"I will set my alarm earlier.", reZh:"我會把鬧鐘調早一些。" },
{ t:"autumn", zh:"秋天", ph:"ˈɔtəm", ex:"The leaves turn red and gold in the autumn.", exZh:"秋天樹葉轉為紅色和金黃色。", re:"Autumn is my favorite season too.", reZh:"秋天也是我最愛的季節。" },
{ t:"awake", zh:"醒著", ph:"əˈwek", ex:"The loud thunder kept me awake all night long.", exZh:"轟隆的雷聲使我整晚睡不著。", re:"You should take a nap today.", reZh:"你今天應該補個眠。" },
{ t:"balance", zh:"平衡", ph:"ˈbæləns", ex:"You need good balance to ride a bicycle well.", exZh:"把腳踏車騎好需要良好的平衡感。", re:"Practice a little every single day.", reZh:"每天練習一些些。" },
{ t:"barbecue", zh:"烤肉", ph:"ˈbɑrbɪˌkju", ex:"We are having a barbecue by the river this weekend.", exZh:"我們這週末要在河邊烤肉。", re:"Count me in, I love barbecue.", reZh:"算我一份，我愛烤肉。" },
{ t:"basement", zh:"地下室", ph:"ˈbesmənt", ex:"We store old books and toys in the basement.", exZh:"我們把舊書和玩具存放在地下室。", re:"It must be full of memories.", reZh:"那裡一定充滿回憶。" },
{ t:"beard", zh:"鬍子", ph:"bɪrd", ex:"My uncle grew a long beard during the winter.", exZh:"我叔叔冬天留了長鬍子。", re:"Does it keep his face warm?", reZh:"鬍子能保暖他的臉嗎？" },
{ t:"beauty", zh:"美麗", ph:"ˈbjuti", ex:"We enjoyed the beauty of the sunrise at the beach.", exZh:"我們在海邊欣賞日出之美。", re:"Nature always amazes me deeply.", reZh:"大自然總令我深深讚嘆。" },
{ t:"belief", zh:"信念", ph:"bɪˈlif", ex:"It is my belief that hard work brings success.", exZh:"我相信努力會帶給人成功。", re:"I share the same belief too.", reZh:"我也有同樣的信念。" },
{ t:"bill", zh:"帳單", ph:"bɪl", ex:"Dad paid the electricity bill at the convenience store.", exZh:"爸爸在便利商店繳了電費帳單。", re:"Paying bills there is so handy.", reZh:"在那繳費真方便。" },
{ t:"bitter", zh:"苦的", ph:"ˈbɪtɚ", ex:"This herbal tea tastes bitter but is good for you.", exZh:"這青草茶喝起來苦，但對你有益。", re:"I will add a little honey.", reZh:"我會加一些蜂蜜。" },
{ t:"blanket", zh:"毛毯", ph:"ˈblæŋkɪt", ex:"Mom covered the sleeping baby with a soft blanket.", exZh:"媽媽用柔軟的毯子蓋住熟睡的寶寶。", re:"The baby looks warm and cozy.", reZh:"寶寶看起來溫暖又舒服。" },
{ t:"blind", zh:"盲目的", ph:"blaɪnd", ex:"The kind girl helped the blind man cross the street.", exZh:"善良的女孩幫盲人穿越馬路。", re:"Small acts of kindness matter most.", reZh:"小小的善舉最重要。" },
{ t:"bomb", zh:"炸彈", ph:"bɑm", ex:"The old bomb from the war was safely removed.", exZh:"戰爭留下的舊炸彈被安全移除了。", re:"Thank goodness everyone is safe now.", reZh:"謝天謝地大家都平安。" },
{ t:"bored", zh:"無聊的", ph:"bɔrd", ex:"I felt bored because there was nothing to do.", exZh:"因為無事可做，我覺得好無聊。", re:"Let us play a board game.", reZh:"我們玩桌遊吧。" },
{ t:"bottom", zh:"底部", ph:"ˈbɑtəm", ex:"I found my missing sock at the bottom of the drawer.", exZh:"我在抽屜底部找到不見的襪子。", re:"It is always the last place.", reZh:"總是在最後找的地方。" },
{ t:"bowling", zh:"保齡球", ph:"ˈbolɪŋ", ex:"We go bowling with our cousins every Friday night.", exZh:"我們每週五晚上和表親打保齡球。", re:"Who usually gets the highest score?", reZh:"通常哪位分數最高？" },
{ t:"branch", zh:"樹枝", ph:"bræntʃ", ex:"A little bird built its nest on the branch.", exZh:"一隻小鳥在樹枝上築巢。", re:"Nature is right outside our window.", reZh:"大自然就在我們窗外。" },
{ t:"brick", zh:"磚", ph:"brɪk", ex:"The old house was built with red brick years ago.", exZh:"這棟老屋多年前用紅磚建成。", re:"Brick houses last a long time.", reZh:"磚房很耐久。" },
{ t:"broadcast", zh:"廣播", ph:"ˈbrɔdˌkæst", ex:"The radio station will broadcast the baseball game live.", exZh:"廣播電台將現場轉播棒球賽。", re:"I will listen to it tonight.", reZh:"我今晚會收聽。" },
{ t:"bun", zh:"小麵包", ph:"bʌn", ex:"I ate a warm pork bun for breakfast today.", exZh:"我今天早餐吃了熱騰騰的肉包。", re:"That sounds delicious, where did you buy it?", reZh:"聽起來真好吃，你在哪買的？" },
{ t:"burst", zh:"爆開", ph:"bɝst", ex:"The balloon burst suddenly and scared the little kids.", exZh:"氣球突然爆開，嚇到了小朋友們。", re:"I hope nobody started to cry.", reZh:"希望沒有小孩哭出來。" },
{ t:"cabin", zh:"小屋", ph:"ˈkæbɪn", ex:"We stayed in a wooden cabin near the lake.", exZh:"我們住在湖邊的小木屋。", re:"That sounds like a peaceful trip.", reZh:"聽起來是趟寧靜的旅行。" },
{ t:"calendar", zh:"日曆", ph:"ˈkæləndɚ", ex:"I marked all the test dates on my calendar.", exZh:"我把所有考試日期標在日曆上。", re:"Staying organized really helps studying.", reZh:"有條理真的對讀書有幫助。" },
{ t:"campus", zh:"校園", ph:"ˈkæmpəs", ex:"The university campus is full of tall green trees.", exZh:"大學校園裡滿是高大的綠樹。", re:"It must be lovely to study there.", reZh:"在那裡讀書一定很棒。" },
{ t:"capital", zh:"首都", ph:"ˈkæpɪtəl", ex:"Paris is the capital of France, as everyone knows.", exZh:"大家都知道巴黎是法國的首都。", re:"I dream of visiting it someday.", reZh:"我夢想有天能造訪。" },
{ t:"career", zh:"職業", ph:"kəˈrɪr", ex:"She hopes to build a career in computer science.", exZh:"她希望在資訊科技領域發展職涯。", re:"That field has a bright future.", reZh:"那個領域前景光明。" },
{ t:"cartoon", zh:"卡通", ph:"kɑrˈtun", ex:"My little sister watches her favorite cartoon every morning.", exZh:"我妹妹每天早上看她最愛的卡通。", re:"Which cartoon does she like best?", reZh:"她最喜歡哪部卡通？" },
{ t:"cash", zh:"現金", ph:"kæʃ", ex:"I do not have enough cash to buy the ticket.", exZh:"我沒有足夠的現金買票。", re:"You can borrow some from me.", reZh:"你可以跟我借一些。" },
{ t:"cause", zh:"原因", ph:"kɔz", ex:"Heavy rain was the cause of the traffic jam.", exZh:"大雨是塞車的原因。", re:"The roads were flooded this morning.", reZh:"今天早上路都淹水了。" },
{ t:"cell", zh:"細胞", ph:"sɛl", ex:"We looked at a plant cell under the microscope.", exZh:"我們用顯微鏡觀察植物細胞。", re:"Biology class is full of wonders.", reZh:"生物課充滿驚奇。" },
{ t:"century", zh:"世紀", ph:"ˈsɛntʃɚi", ex:"This temple was built more than a century ago.", exZh:"這座廟建於一百多年前。", re:"Old buildings hold so much history.", reZh:"老建築承載許多歷史。" },
{ t:"chairman", zh:"主席", ph:"ˈtʃɛrˌmæn", ex:"The chairman opened the meeting with a short speech.", exZh:"主席以簡短的致詞為會議揭開序幕。", re:"His speeches are always very clear.", reZh:"他的致詞總是很清楚。" },
{ t:"champion", zh:"冠軍", ph:"ˈtʃæmpiən", ex:"Our team became the champion of the city tournament.", exZh:"我們隊成為市級比賽的冠軍。", re:"All that practice finally paid off.", reZh:"所有練習終於有了回報。" },
{ t:"character", zh:"人物", ph:"ˈkɛrəktɚ", ex:"The main character in this story is very brave.", exZh:"這個故事的主角非常勇敢。", re:"Brave heroes make stories exciting.", reZh:"勇敢的英雄使故事精彩。" },
{ t:"chart", zh:"圖表", ph:"tʃɑrt", ex:"The chart on the wall shows our reading progress.", exZh:"牆上的圖表顯示我們的閱讀進度。", re:"Our class is doing really well.", reZh:"我們班表現得很好。" }
] },
{ level: 2, words: [
{ t:"cheat", zh:"作弊", ph:"tʃit", ex:"Students who cheat on tests will be punished severely.", exZh:"考場作弊的學生會受到嚴厲處罰。", re:"Honesty is always the best policy.", reZh:"誠實永遠是上策。" },
{ t:"chemistry", zh:"化學", ph:"ˈkɛmɪstri", ex:"We did a fun experiment in chemistry class today.", exZh:"我們今天在化學課做了有趣的實驗。", re:"What did you make this time?", reZh:"你們這次做了什麼？" },
{ t:"childish", zh:"幼稚的", ph:"ˈtʃaɪldɪʃ", ex:"Drawing on the wall is a childish thing to do.", exZh:"在牆上亂畫是很幼稚的行為。", re:"His little brother probably did it.", reZh:"可能是他弟弟畫的。" },
{ t:"choice", zh:"選擇", ph:"tʃɔɪs", ex:"Joining the science club was a great choice for me.", exZh:"加入科學社對我而言是很棒的抉擇。", re:"You always loved doing experiments.", reZh:"你一直很愛做實驗。" },
{ t:"classical", zh:"古典的", ph:"ˈklæsɪkəl", ex:"My mother listens to classical music while she cooks.", exZh:"我媽媽煮飯的同時聽古典音樂。", re:"Music makes housework more enjoyable.", reZh:"音樂使家事更愉快。" },
{ t:"clay", zh:"黏土", ph:"kle", ex:"The children made cute animals out of colorful clay.", exZh:"孩子們用彩色黏土做出可愛的動物。", re:"Art class sounds really fun.", reZh:"美術課聽起來真好玩。" },
{ t:"climate", zh:"氣候", ph:"ˈklaɪmɪt", ex:"The climate in this country is warm all year.", exZh:"這個國家全年氣候溫暖。", re:"That sounds perfect for a vacation.", reZh:"聽起來很值得去度假。" },
{ t:"clothing", zh:"衣物", ph:"ˈkloðɪŋ", ex:"This store sells winter clothing at half price now.", exZh:"這家店的冬季衣物如今半價出售。", re:"Let us go shopping this weekend.", reZh:"我們這週末去逛逛吧。" },
{ t:"coal", zh:"煤", ph:"kol", ex:"People used coal to heat their homes long ago.", exZh:"很久以前人們用煤取暖。", re:"Times have really changed since then.", reZh:"如今真是不同了。" },
{ t:"code", zh:"代碼", ph:"kod", ex:"My brother writes computer code for a game company.", exZh:"我哥哥為遊戲公司寫程式碼。", re:"That job sounds really interesting.", reZh:"那工作聽起來真有趣。" },
{ t:"comfortable", zh:"舒適的", ph:"ˈkʌmfɚtəbl", ex:"This sofa is so comfortable that I almost fell asleep.", exZh:"這沙發舒服到我差些睡著。", re:"I want one for my room.", reZh:"我也想要一張放房裡。" },
{ t:"comment", zh:"評論", ph:"ˈkɑmɛnt", ex:"The teacher wrote a kind comment on my essay.", exZh:"老師在我的作文上寫了溫暖的評語。", re:"Her words must encourage you a lot.", reZh:"她的評語一定很鼓勵你。" },
{ t:"communicate", zh:"溝通", ph:"kəˈmjunɪˌket", ex:"We communicate with our cousins abroad through video calls.", exZh:"我們透過視訊和國外的表親保持聯繫。", re:"Technology brings families closer together.", reZh:"科技使家人更親密。" },
{ t:"company", zh:"公司", ph:"ˈkʌmpəni", ex:"My mother has worked for that company for ten years.", exZh:"我媽媽在那家公司工作十年了。", re:"She must really enjoy her job.", reZh:"她一定很喜歡她的工作。" },
{ t:"complain", zh:"抱怨", ph:"kəmˈplen", ex:"Some customers complain when the food arrives too slowly.", exZh:"上菜太慢的話有些顧客會抱怨。", re:"Waiting always makes people impatient.", reZh:"等待總使人不耐煩。" },
{ t:"concert", zh:"演唱會", ph:"ˈkɑnsɚt", ex:"We are going to a concert at the stadium tonight.", exZh:"我們今晚要去體育場聽演唱會。", re:"I heard the tickets sold out.", reZh:"聽聞門票都賣光了。" },
{ t:"confident", zh:"有信心的", ph:"ˈkɑnfɪdənt", ex:"Practice more and you will feel confident on stage.", exZh:"多練習你在台上就會有自信。", re:"Thanks, I will rehearse every day.", reZh:"謝謝，我會每天排練。" },
{ t:"congratulation", zh:"祝賀", ph:"ˌkɑŋgrætʃəˈleʃən", ex:"Please give my congratulation to your sister on graduating.", exZh:"請代我向你姊姊祝賀畢業。", re:"She will be happy to hear that.", reZh:"她聽到會很開心。" },
{ t:"contact", zh:"聯繫", ph:"ˈkɑntækt", ex:"Please contact the office if you have any questions.", exZh:"如有任何疑慮請聯絡辦公室。", re:"I will call them tomorrow morning.", reZh:"我明天早上會打給他們。" },
{ t:"continue", zh:"繼續", ph:"kənˈtɪnu", ex:"The game will continue after the short rain break.", exZh:"短暫的雨停後比賽將繼續進行。", re:"I hope the rain stops soon.", reZh:"希望雨快些停。" },
{ t:"convenient", zh:"方便的", ph:"kənˈvinjənt", ex:"Living near the MRT station is really very convenient.", exZh:"住在捷運站旁真的很方便。", re:"You save so much travel time.", reZh:"你省下好多通勤的功夫。" },
{ t:"cotton", zh:"棉", ph:"ˈkɑtən", ex:"This soft shirt is made of one hundred percent cotton.", exZh:"這件柔軟的襯衫是百分之百純棉的。", re:"Cotton clothes feel great in summer.", reZh:"棉質衣服夏天穿起來很舒服。" },
{ t:"county", zh:"郡", ph:"ˈkaʊnti", ex:"My grandparents live in a quiet county in the south.", exZh:"我的祖父母住在南部一個安靜的縣。", re:"Country life sounds calm and slow.", reZh:"鄉間生活聽起來悠閒緩慢。" },
{ t:"court", zh:"法庭", ph:"kɔrt", ex:"The players are practicing on the basketball court now.", exZh:"球員們正在籃球場上練習。", re:"Let us go watch them play.", reZh:"我們去看他們打球吧。" },
{ t:"crab", zh:"螃蟹", ph:"kræb", ex:"We caught a small crab in the shallow water.", exZh:"我們在淺水處抓到一隻小螃蟹。", re:"Remember to put it back later.", reZh:"記得待會把牠放回去。" },
{ t:"crayon", zh:"蠟筆", ph:"ˈkreɑən", ex:"The little girl drew a rainbow with her new crayon.", exZh:"小女孩用新蠟筆畫了一道彩虹。", re:"Children draw the sweetest pictures.", reZh:"孩子畫的圖最可愛了。" },
{ t:"credit", zh:"信用", ph:"ˈkrɛdɪt", ex:"The whole team deserves credit for winning the championship.", exZh:"贏得冠軍是整個團隊的功勞。", re:"They practiced hard for months.", reZh:"他們苦練了好幾個月。" },
{ t:"crowd", zh:"人群", ph:"kraʊd", ex:"A big crowd gathered to watch the street performer.", exZh:"一大群人聚集觀看街頭藝人表演。", re:"He must be really talented.", reZh:"他一定很有才華。" },
{ t:"cruel", zh:"殘忍的", ph:"ˈkruəl", ex:"Being cruel to animals is never acceptable behavior anywhere.", exZh:"對動物殘忍在哪裡都不能接受。", re:"We should treat them with love.", reZh:"我們應該用愛對待牠們。" },
{ t:"cure", zh:"治療", ph:"kjʊr", ex:"Scientists hope to find a cure for the illness.", exZh:"科學家希望找到治癒這種疾病的方法。", re:"Medical research gives people hope.", reZh:"醫學研究帶給人們希望。" },
{ t:"curtain", zh:"窗簾", ph:"ˈkɝtən", ex:"Mom bought a new curtain for the bedroom window.", exZh:"媽媽為臥室窗戶買了新窗簾。", re:"What color did she choose?", reZh:"她挑了什麼顏色？" },
{ t:"customer", zh:"顧客", ph:"ˈkʌstəmɚ", ex:"The polite customer thanked the waiter for his service.", exZh:"有禮貌的顧客感激服務生的服務。", re:"Kindness always goes both ways.", reZh:"善意總是相互的。" },
{ t:"damage", zh:"損害", ph:"ˈdæmɪdʒ", ex:"The heavy rain caused serious damage to the bridge.", exZh:"大雨對橋樑造成嚴重損害。", re:"I hope they repair it soon.", reZh:"希望他們快些修好。" },
{ t:"deaf", zh:"聾的", ph:"dɛf", ex:"My deaf classmate reads lips and uses sign language.", exZh:"我失聰的同學會讀唇語和用手語。", re:"I want to learn sign language too.", reZh:"我也想學手語。" },
{ t:"debate", zh:"辯論", ph:"dɪˈbet", ex:"Our team won the English debate competition yesterday afternoon.", exZh:"我們隊昨天下午贏得英語辯論比賽。", re:"Congratulations on the great victory!", reZh:"恭喜你們大獲全勝！" },
{ t:"decorate", zh:"裝飾", ph:"ˈdɛkəˌret", ex:"We will decorate the classroom for the Christmas party.", exZh:"我們要為聖誕派對布置教室。", re:"I can bring some colorful lights.", reZh:"我可以帶些彩燈。" },
{ t:"degree", zh:"度數", ph:"dɪˈgri", ex:"The temperature rose by one degree every single hour.", exZh:"氣溫每小時上升一度。", re:"It will be very hot soon.", reZh:"很快就會非常熱了。" },
{ t:"deliver", zh:"遞送", ph:"dɪˈlɪvɚ", ex:"The store will deliver the new sofa tomorrow afternoon.", exZh:"店家明天下午會把新沙發送到。", re:"Finally, we waited two whole weeks.", reZh:"終於，我們等了整整兩週。" },
{ t:"depend", zh:"依靠", ph:"dɪˈpɛnd", ex:"Whether we go hiking will depend on the weather.", exZh:"我們是否去健行要看天氣而定。", re:"Let us check the forecast tonight.", reZh:"我們今晚查一下天氣預報。" },
{ t:"desert", zh:"沙漠", ph:"ˈdɛzɚt", ex:"Camels can walk in the hot desert for days.", exZh:"駱駝能在炎熱的沙漠中走好幾天。", re:"They are amazing desert animals.", reZh:"牠們是神奇的沙漠動物。" },
{ t:"design", zh:"設計", ph:"dɪˈzaɪn", ex:"She wants to design clothes for children in the future.", exZh:"她未來想為孩子設計衣服。", re:"Her dream sounds really wonderful.", reZh:"她的夢想聽起來真棒。" },
{ t:"detail", zh:"細節", ph:"ˈditel", ex:"Please tell me every detail about the school trip.", exZh:"請告訴我校外旅行的每個細節。", re:"Sure, it is a long story.", reZh:"好，那可要講很久。" },
{ t:"development", zh:"發展", ph:"dɪˈvɛləpmənt", ex:"The development of new phones happens faster every year.", exZh:"新手機的研發一年比一年快。", re:"I can hardly keep up now.", reZh:"我都快跟不上了。" },
{ t:"diamond", zh:"鑽石", ph:"ˈdaɪmənd", ex:"The queen wore a shiny diamond necklace at the party.", exZh:"女王在派對上戴著閃亮的鑽石項鍊。", re:"It must be worth a fortune.", reZh:"那一定價值連城。" },
{ t:"difference", zh:"差異", ph:"ˈdɪfɚəns", ex:"Can you tell the difference between these two paintings?", exZh:"你能分辨這兩幅畫的差別嗎？", re:"They look almost the same to me.", reZh:"在我看它們幾乎一樣。" },
{ t:"difficulty", zh:"困難", ph:"ˈdɪfɪˌkʌlti", ex:"He has difficulty remembering names when meeting new people.", exZh:"他見到新朋友常記不住名字，頗有困難。", re:"Writing names down might help him.", reZh:"把名字寫下也許有幫助。" },
{ t:"direct", zh:"直接的", ph:"dəˈrɛkt", ex:"Is there a direct bus from here to the airport?", exZh:"這裡有直達機場的公車嗎？", re:"Yes, it leaves every thirty minutes.", reZh:"有，每三十分鐘一班。" },
{ t:"director", zh:"主任", ph:"dəˈrɛktɚ", ex:"The director asked the actors to practice the scene again.", exZh:"導演要求演員再排練一次那場戲。", re:"Practice makes the performance perfect.", reZh:"多練習才能演得完美。" },
{ t:"disappear", zh:"消失", ph:"ˌdɪsəˈpɪr", ex:"The magician made the white rabbit disappear on stage.", exZh:"魔術師使白兔在舞台上消失了。", re:"How did he do that trick?", reZh:"他那招是怎麼變的？" },
{ t:"discuss", zh:"討論", ph:"dɪˈskʌs", ex:"Let us discuss the plan for the class trip.", exZh:"我們討論一下班遊的計畫吧。", re:"I have some fun ideas already.", reZh:"我已有一些有趣的想法。" }
] },
{ level: 3, words: [
{ t:"disease", zh:"疾病", ph:"dɪˈziz", ex:"Doctors work hard to stop the disease from spreading.", exZh:"醫生努力阻止疾病擴散。", re:"We should all wash our hands.", reZh:"我們都該勤洗手。" },
{ t:"distant", zh:"遠的", ph:"ˈdɪstənt", ex:"We could see a distant island from the shore.", exZh:"我們從岸上能看到遙遙相望的小島。", re:"Maybe we can sail there someday.", reZh:"也許哪天我們能航行到那裡。" },
{ t:"dizzy", zh:"眩暈的", ph:"ˈdɪzi", ex:"I felt dizzy after spinning around too many times.", exZh:"轉圈轉太多次後我頭好暈。", re:"Sit down and rest a moment.", reZh:"坐下休息一下吧。" },
{ t:"doubt", zh:"懷疑", ph:"daʊt", ex:"I doubt the store is still open this late.", exZh:"我懷疑這麼晚商店還開著。", re:"Let us call and ask first.", reZh:"我們先打電話去確認。" },
{ t:"downstairs", zh:"樓下", ph:"ˌdaʊnˈstɛrz", ex:"Grandpa is watching television downstairs in the living room.", exZh:"爺爺在樓下客廳看電視。", re:"I will go say hello to him.", reZh:"我下樓跟他打聲招呼。" },
{ t:"dozen", zh:"一打", ph:"ˈdʌzən", ex:"Mom bought a dozen eggs at the morning market.", exZh:"媽媽在早市買了一打雞蛋。", re:"Is she baking a cake today?", reZh:"她今天要烤蛋糕嗎？" },
{ t:"drug", zh:"藥物", ph:"drʌg", ex:"The doctor said this drug must be taken after meals.", exZh:"醫生囑咐這種藥必須飯後服用。", re:"I will remember to do that.", reZh:"我會記得的。" },
{ t:"drunk", zh:"醉的", ph:"drʌŋk", ex:"A drunk man was singing loudly on the street.", exZh:"一個喝醉的男人在街上大聲唱歌。", re:"Someone should take him home safely.", reZh:"該有人送他安全回家。" },
{ t:"dumb", zh:"啞的", ph:"dʌm", ex:"It was dumb of me to forget my keys again.", exZh:"我又忘了帶鑰匙，真是太傻了。", re:"Do not worry, everyone forgets sometimes.", reZh:"別擔心，每個人偶爾都會忘東忘西。" },
{ t:"earn", zh:"賺取", ph:"ɝn", ex:"She works part time to earn her own pocket money.", exZh:"她打工賺自己的零用錢。", re:"That teaches her to be independent.", reZh:"那能教她獨立。" },
{ t:"ease", zh:"輕鬆", ph:"iz", ex:"The medicine helped ease the pain in my knee quickly.", exZh:"藥物很快減輕了我膝蓋的疼痛。", re:"I am glad you feel better.", reZh:"很高興你好多了。" },
{ t:"educate", zh:"教育", ph:"ˈɛdʒəˌket", ex:"Schools educate children to become responsible and kind citizens.", exZh:"學校教育孩子成為負責又善良的公民。", re:"Teachers carry a big responsibility.", reZh:"老師肩負重大的責任。" },
{ t:"effect", zh:"效果", ph:"ɪˈfɛkt", ex:"Staying up late has a bad effect on your health.", exZh:"熬夜對健康有不好的影響。", re:"I will try to sleep earlier.", reZh:"我會試著早些睡。" },
{ t:"elder", zh:"年長的", ph:"ˈɛldɚ", ex:"We should always show respect to our elder family members.", exZh:"我們應該永保對家中長輩的尊敬。", re:"My grandparents taught me the same.", reZh:"我的祖父母也這麼教我。" },
{ t:"election", zh:"選舉", ph:"ɪˈlɛkʃən", ex:"The class election for president will be held Friday.", exZh:"班長選舉將在星期五舉行。", re:"Who are you voting for?", reZh:"你要投給哪位？" },
{ t:"elementary", zh:"基礎的", ph:"ˌɛləˈmɛntɚi", ex:"My brother teaches art at an elementary school nearby.", exZh:"我哥哥在住家周邊的小學教美術。", re:"Kids must love his art class.", reZh:"孩子們一定很愛他的美術課。" },
{ t:"empty", zh:"空的", ph:"ˈɛmpti", ex:"The streets were empty early on Sunday morning.", exZh:"星期天清晨街道空無一人。", re:"I love that quiet peaceful feeling.", reZh:"我喜歡那份寧靜的感受。" },
{ t:"ending", zh:"結尾", ph:"ˈɛndɪŋ", ex:"The movie had a happy ending that surprised everyone.", exZh:"這部電影有個令大家驚喜的快樂結局。", re:"I love happy endings the most.", reZh:"我最愛快樂結局了。" },
{ t:"energy", zh:"能量", ph:"ˈɛnɚʒi", ex:"Eating a good breakfast gives you energy all morning.", exZh:"吃頓好早餐使你整個早上都有活力。", re:"I never skip my breakfast.", reZh:"我從不跳掉早餐。" },
{ t:"entire", zh:"整個的", ph:"ɪnˈtaɪr", ex:"We spent the entire weekend cleaning up the garage.", exZh:"我們整個週末都在打掃車庫。", re:"That must have been tiring work.", reZh:"那一定很累人。" },
{ t:"envy", zh:"嫉妒", ph:"ˈɛnvi", ex:"I envy people who can sing in front of crowds.", exZh:"我羨慕能在人群前唱歌的人。", re:"You could practice and try too.", reZh:"你也可以練習試試看。" },
{ t:"error", zh:"錯誤", ph:"ˈɛrɚ", ex:"I found a small error in my math homework.", exZh:"我在數學作業裡找到一個小錯誤。", re:"Good thing you checked it again.", reZh:"還好你有再檢查一次。" },
{ t:"event", zh:"事件", ph:"ɪˈvɛnt", ex:"The sports event will take place next Saturday afternoon.", exZh:"運動賽事將在下週六下午舉行。", re:"I plan to join the relay race.", reZh:"我打算參加接力賽。" },
{ t:"exactly", zh:"確實", ph:"ɪgˈzæktli", ex:"The bus arrived at exactly nine in the morning.", exZh:"公車早上九時整準時到站。", re:"Wow, it is always on time.", reZh:"哇，它總是那麼準時。" },
{ t:"examine", zh:"檢查", ph:"ɪgˈzæmɪn", ex:"The dentist will examine my teeth this Thursday afternoon.", exZh:"牙醫這週四下午要檢查我的牙齒。", re:"Remember to brush well before going.", reZh:"去之前記得好好刷牙。" },
{ t:"exchange", zh:"交換", ph:"ɪksˈtʃendʒ", ex:"The two students exchange letters with their foreign friends.", exZh:"這兩位學生和外國朋友互相通信。", re:"Writing letters is a lovely habit.", reZh:"寫信是很美好的習慣。" },
{ t:"exhibition", zh:"展覽", ph:"ˌɛgzɪˈbɪʃən", ex:"We visited an art exhibition at the museum yesterday.", exZh:"我們昨天去博物館看了藝術展。", re:"Which painting did you like best?", reZh:"你最喜歡哪幅畫？" },
{ t:"expect", zh:"預期", ph:"ɪkˈspɛkt", ex:"I expect the package to arrive by Friday afternoon.", exZh:"我預期包裹星期五下午前會到。", re:"Online shopping is quite fast now.", reZh:"如今網購相當快。" },
{ t:"express", zh:"表達", ph:"ɪkˈsprɛs", ex:"It is hard to express my thanks in words.", exZh:"我的感激之情言語不足以表達。", re:"Your smile already says everything.", reZh:"你的笑容已表明一切。" },
{ t:"extra", zh:"額外的", ph:"ˈɛkstrə", ex:"Bring an extra jacket because it gets cold at night.", exZh:"多帶一件外套，因為晚上會變冷。", re:"Thanks for the kind reminder.", reZh:"謝謝你貼心提醒。" },
{ t:"false", zh:"假的", ph:"fɔls", ex:"The news about the school closing was totally false.", exZh:"學校要關閉的消息完全是假的。", re:"People should check facts before sharing.", reZh:"大家分享前應查證事實。" },
{ t:"fancy", zh:"喜歡", ph:"ˈfænsi", ex:"They had dinner at a fancy restaurant downtown yesterday.", exZh:"他們昨天在市中心一家高級餐廳吃晚餐。", re:"That must have cost a lot.", reZh:"那一定花了不少錢。" },
{ t:"fashion", zh:"時尚", ph:"ˈfæʃən", ex:"My sister reads fashion magazines every single month.", exZh:"我姊姊每個月都看時尚雜誌。", re:"She always dresses so stylishly.", reZh:"她總是穿得很時髦。" },
{ t:"fault", zh:"過失", ph:"fɔlt", ex:"It was my fault that we missed the early train.", exZh:"我們沒趕上早班火車是我的錯。", re:"Do not blame yourself too much.", reZh:"別太自責了。" },
{ t:"fee", zh:"費用", ph:"fi", ex:"The entrance fee for the zoo is fifty dollars.", exZh:"動物園的入場收費是五十元。", re:"That price is quite reasonable.", reZh:"這價錢蠻合理的。" },
{ t:"fence", zh:"柵欄", ph:"fɛns", ex:"Dad painted the wooden fence around our yard white.", exZh:"爸爸把我們院子周圍的木柵欄漆成白色。", re:"It must look brand new now.", reZh:"如今看起來一定像新的。" },
{ t:"figure", zh:"數字", ph:"ˈfɪgjɚ", ex:"I cannot figure out the answer to this question.", exZh:"我想不出這題的答案。", re:"Let us solve it together then.", reZh:"那我們一起解吧。" },
{ t:"fisherman", zh:"漁民", ph:"ˈfɪʃɚmən", ex:"The old fisherman goes out to sea every morning.", exZh:"老漁夫每天清晨出海。", re:"What a hardworking life he lives.", reZh:"他的生活多麼勤奮。" },
{ t:"flat", zh:"平的", ph:"flæt", ex:"My bike got a flat tire on the way home.", exZh:"我的腳踏車在回家路上爆胎了。", re:"Did you have to walk home?", reZh:"你只好走路回家嗎？" },
{ t:"flour", zh:"麵粉", ph:"ˈflaʊɚ", ex:"We need two cups of flour to bake the cookies.", exZh:"烤餅乾需要兩杯麵粉。", re:"I will get some from the store.", reZh:"我去商店買一些。" },
{ t:"flu", zh:"流感", ph:"flu", ex:"Half the class was absent because of the flu.", exZh:"因為流感，半個班的人都缺席了。", re:"Everyone should get more rest.", reZh:"大家應該多休息。" },
{ t:"focus", zh:"焦點", ph:"ˈfokəs", ex:"Please focus on your homework before playing video games.", exZh:"打電動前請先專心寫作業。", re:"Okay, I will finish it first.", reZh:"好，我會先寫完。" },
{ t:"fool", zh:"傻瓜", ph:"ful", ex:"He tried to fool us with a silly trick.", exZh:"他想用愚蠢的把戲騙我們。", re:"Nobody believed him at all.", reZh:"根本沒有人相信他。" },
{ t:"force", zh:"力量", ph:"fɔrs", ex:"Do not force the door; it opens the other way.", exZh:"別硬推那扇木板門，它是往另一側開的。", re:"Oh, no wonder it was stuck.", reZh:"喔，難怪推不動。" },
{ t:"forgive", zh:"原諒", ph:"fɚˈgɪv", ex:"Please forgive me for breaking your favorite blue cup.", exZh:"請原諒我打破了你最愛的藍杯子。", re:"It is fine, accidents do happen.", reZh:"沒關係，意外在所難免。" },
{ t:"formal", zh:"正式的", ph:"ˈfɔrməl", ex:"You should wear formal clothes to the wedding ceremony.", exZh:"你應該穿正式服裝參加婚禮。", re:"I will wear my best suit.", reZh:"我會穿上我最好的西裝。" },
{ t:"forward", zh:"向前", ph:"ˈfɔrwɚd", ex:"I am looking forward to the summer vacation trip.", exZh:"我很期待暑假的旅行。", re:"Me too, it will be fun.", reZh:"我也是，一定會很好玩。" },
{ t:"freeze", zh:"冷凍", ph:"friz", ex:"The cold weather will freeze the lake by December.", exZh:"寒冷的天氣會使湖水在十二月前結冰。", re:"Then we can go ice skating.", reZh:"那我們就能去溜冰了。" },
{ t:"friendly", zh:"友善的", ph:"ˈfrɛndli", ex:"The people in this town are friendly to visitors.", exZh:"這個小鎮的人對訪客很友善。", re:"That makes traveling more enjoyable.", reZh:"那使旅行更愉快。" },
{ t:"furniture", zh:"家具", ph:"ˈfɝnɪtʃɚ", ex:"They bought new furniture for their living room last week.", exZh:"他們上週為客廳買了新家具。", re:"I would love to see it.", reZh:"我好想看看。" }
] },
{ level: 4, words: [
{ t:"gain", zh:"獲得", ph:"gen", ex:"You will gain more confidence by practicing every day.", exZh:"每天練習會讓你獲得更多自信。", re:"Thanks, I will keep trying.", reZh:"謝謝，我會繼續努力。" },
{ t:"general", zh:"一般的", ph:"ˈdʒɛnɚəl", ex:"In general, the weather here is mild in spring.", exZh:"一般而言，這裡春天的天氣很溫和。", re:"Spring sounds like the best season.", reZh:"春天聽起來是最棒的季節。" },
{ t:"genius", zh:"天才", ph:"ˈdʒinjəs", ex:"People call him a genius because he learns quickly.", exZh:"因為他一教就會，大家叫他天才。", re:"He still studies very hard though.", reZh:"不過他還是很用功。" },
{ t:"gentleman", zh:"紳士", ph:"ˈdʒɛntəlmən", ex:"A true gentleman always holds the door for others.", exZh:"真正的紳士總是幫別人扶著門。", re:"Good manners never go out of style.", reZh:"好禮貌永不退流行。" },
{ t:"goal", zh:"目標", ph:"gol", ex:"My goal this year is to read twenty books.", exZh:"我今年的目標是讀二十本書。", re:"That is a wonderful reading plan.", reZh:"那是很棒的閱讀計畫。" },
{ t:"golf", zh:"高爾夫", ph:"gɑlf", ex:"My father plays golf with his friends every Sunday.", exZh:"我爸爸每週日和朋友打高爾夫球。", re:"Does he ever take you along?", reZh:"他有帶你一起去嗎？" },
{ t:"graduate", zh:"畢業", ph:"ˈgrædʒəˌwet", ex:"My sister will graduate from senior high school in June.", exZh:"我姊姊六月將從高中畢業。", re:"You must be proud of her.", reZh:"你一定很為她驕傲。" },
{ t:"grammar", zh:"文法", ph:"ˈgræmɚ", ex:"Good grammar makes your English writing much clearer.", exZh:"好的文法讓你的英文寫作更清楚。", re:"I need to review mine more.", reZh:"我需要多複習文法。" },
{ t:"granddaughter", zh:"孫女", ph:"ˈgrænˌdɔtɚ", ex:"Grandpa taught his granddaughter how to ride a bike.", exZh:"爺爺教孫女怎麼騎腳踏車。", re:"What a sweet moment to remember.", reZh:"真是值得回味的溫馨片刻。" },
{ t:"greedy", zh:"貪心的", ph:"ˈgridi", ex:"The greedy king wanted all the gold for himself.", exZh:"貪心的國王想把所有黃金占為己有。", re:"Greed never brings true happiness.", reZh:"貪婪永不會帶給人真正的快樂。" },
{ t:"greeting", zh:"問候", ph:"ˈgritɪŋ", ex:"She sent me a warm greeting card for my birthday.", exZh:"她寄了一張溫馨的生日賀卡給我。", re:"Handwritten cards feel so special.", reZh:"手寫卡片感覺特別溫暖。" },
{ t:"guest", zh:"客人", ph:"gɛst", ex:"We prepared the extra room for our guest tonight.", exZh:"我們為今晚的客人整理了空房。", re:"They will feel right at home.", reZh:"他們一定會感到賓至如歸。" },
{ t:"gun", zh:"槍", ph:"gʌn", ex:"The police officer keeps his gun in a holster.", exZh:"警察把槍放在槍套裡。", re:"Safety training is very important.", reZh:"安全訓練非常重要。" },
{ t:"handle", zh:"處理", ph:"ˈhændəl", ex:"She can handle three tasks at the same time.", exZh:"她能同一時刻處理三件事。", re:"Her time management is impressive.", reZh:"她的行程安排真厲害。" },
{ t:"harbor", zh:"港口", ph:"ˈhɑrbɚ", ex:"Many fishing boats returned to the harbor at sunset.", exZh:"許多漁船在日落回到港口。", re:"That view must be beautiful.", reZh:"那景色一定很美。" },
{ t:"harm", zh:"傷害", ph:"hɑrm", ex:"Too much sugar can harm your teeth and health.", exZh:"太多糖會傷害你的牙齒和健康。", re:"I will cut down on sweets.", reZh:"我會少吃甜食。" },
{ t:"height", zh:"高度", ph:"haɪt", ex:"The nurse measured my height during the health check.", exZh:"健康檢查的時候護理師量了我的身高。", re:"Did you grow taller this year?", reZh:"你今年有長高嗎？" },
{ t:"helpful", zh:"有幫助的", ph:"ˈhɛlpfəl", ex:"The map on your phone is helpful for traveling.", exZh:"手機上的地圖對旅行很有幫助。", re:"I use it all the time.", reZh:"我一直都在用。" },
{ t:"highway", zh:"高速公路", ph:"ˈhaɪˌwe", ex:"We drove along the highway to reach the beach.", exZh:"我們沿著高速公路開往海邊。", re:"How long did the trip take?", reZh:"路程花了多久？" },
{ t:"hiking", zh:"登山", ph:"ˈhaɪkɪŋ", ex:"We are going hiking in the mountains this Saturday.", exZh:"我們這週六要去山上健行。", re:"Remember to bring enough water.", reZh:"記得帶足夠的水。" },
{ t:"hip", zh:"臀部", ph:"hɪp", ex:"The old man hurt his hip when he fell.", exZh:"老先生跌倒的時候傷到了髖部。", re:"I hope he recovers soon.", reZh:"希望他早日康復。" },
{ t:"holy", zh:"神聖的", ph:"ˈholi", ex:"This temple is a holy place for local people.", exZh:"這座廟對當地人而言是神聖的地方。", re:"We should speak quietly inside.", reZh:"我們在裡面應該小聲交談。" },
{ t:"however", zh:"然而", ph:"haʊˈɛvɚ", ex:"I wanted to go out; however, it started raining.", exZh:"我想出門，然而卻開始下雨了。", re:"Maybe you can go out tomorrow.", reZh:"也許你明天再出門。" },
{ t:"human", zh:"人類", ph:"ˈhjumən", ex:"Making mistakes is a normal part of being human.", exZh:"犯錯是身而為人的正常部分。", re:"We learn and grow from them.", reZh:"我們從犯錯中成長。" },
{ t:"humid", zh:"潮濕的", ph:"ˈhjumɪd", ex:"The air feels hot and humid before a typhoon.", exZh:"颱風前空氣又熱又潮濕。", re:"I can hardly stand this weather.", reZh:"我快受不了這樣的天氣。" },
{ t:"hunt", zh:"獵殺", ph:"hʌnt", ex:"Owls hunt small animals quietly during the dark night.", exZh:"貓頭鷹在黑夜裡安靜地獵捕小動物。", re:"Nature is full of surprises.", reZh:"大自然充滿驚奇。" },
{ t:"hurricane", zh:"颶風", ph:"ˈhɝɪˌken", ex:"The hurricane destroyed many houses along the east coast.", exZh:"颶風摧毀了東岸許多房屋。", re:"I hope everyone stays safe.", reZh:"希望大家都平安。" },
{ t:"ignore", zh:"忽視", ph:"ɪgˈnɔr", ex:"Do not ignore the teacher's advice about studying English.", exZh:"不要忽視老師關於讀英文的建議。", re:"You are right, I will listen.", reZh:"你講得有道理，我會聽的。" },
{ t:"impolite", zh:"不禮貌的", ph:"ˌɪmpəˈlaɪt", ex:"It is impolite to talk loudly in the library.", exZh:"在圖書館大聲交談是不禮貌的。", re:"I will remind my little brother.", reZh:"我會提醒我弟弟。" },
{ t:"impossible", zh:"不可能的", ph:"ɪmˈpɑsəbəl", ex:"Nothing is impossible if you work hard enough today.", exZh:"只要夠努力，沒有什麼是不可能的。", re:"Those words really encourage me.", reZh:"這句話真的鼓勵了我。" },
{ t:"include", zh:"包含", ph:"ɪnˈklud", ex:"Does the ticket price include a free drink too?", exZh:"票價有包含一杯免費飲料嗎？", re:"Yes, you can choose any drink.", reZh:"有，你可以任挑一杯。" },
{ t:"income", zh:"收入", ph:"ˈɪnˌkʌm", ex:"His monthly income covers rent, food, and school fees.", exZh:"他的月收入夠付房租、伙食和學費。", re:"Managing money well is important.", reZh:"善用金錢很重要。" },
{ t:"indeed", zh:"確實", ph:"ɪnˈdid", ex:"The final math question was indeed very difficult today.", exZh:"今天最後一題數學確實非常不容易。", re:"Almost nobody answered it correctly.", reZh:"幾乎沒有人答得出。" },
{ t:"influence", zh:"影響", ph:"ˈɪnfluəns", ex:"Good friends have a positive influence on your life.", exZh:"好朋友對你的人生有正面影響。", re:"I am lucky to have them.", reZh:"我很幸運擁有他們。" },
{ t:"information", zh:"信息", ph:"ˌɪnfɚˈmeʃən", ex:"The website gives useful information about the museum hours.", exZh:"這個網站提供博物館開放的實用資訊。", re:"Let me check it before we go.", reZh:"出發前我先查一下。" },
{ t:"instance", zh:"例子", ph:"ˈɪnstəns", ex:"For instance, you can save money by cooking at home.", exZh:"舉例而言，在家煮飯可以省錢。", re:"That is a very practical example.", reZh:"那是很實用的例子。" },
{ t:"instead", zh:"相反", ph:"ɪnˈstɛd", ex:"Let us walk to school instead of taking the bus.", exZh:"我們用走的上學，不要搭公車吧。", re:"Sure, the weather is nice today.", reZh:"好啊，今天天氣很好。" },
{ t:"intelligent", zh:"聰明的", ph:"ɪnˈtɛlɪdʒənt", ex:"Dolphins are intelligent animals that can learn tricks quickly.", exZh:"海豚是能很快把戲學會的聰明動物。", re:"I have seen them perform before.", reZh:"我以前看過牠們表演。" },
{ t:"international", zh:"國際的", ph:"ˌɪntɚˈnæʃənəl", ex:"Our school will host an international student camp soon.", exZh:"我們學校快要舉辦國際學生營隊。", re:"What a great chance to make friends.", reZh:"真是交朋友的好機會。" },
{ t:"introduce", zh:"介紹", ph:"ˌɪntrəˈdus", ex:"Let me introduce my new classmate to you all.", exZh:"讓我向大家介紹我的新同學。", re:"Welcome, we are glad you came.", reZh:"歡迎，很高興你加入。" },
{ t:"inventor", zh:"發明家", ph:"ɪnˈvɛntɚ", ex:"The inventor created a machine that cleans the beach.", exZh:"這位發明家創造了清理海灘的機器。", re:"What a brilliant and useful idea.", reZh:"真是聰明又實用的點子。" },
{ t:"iron", zh:"鐵", ph:"ˈaɪɚn", ex:"Dad used a hot iron to press his white shirt.", exZh:"爸爸用熱熨斗燙他的白襯衫。", re:"He always looks neat for work.", reZh:"他上班總是儀容整齊。" },
{ t:"jealous", zh:"嫉妒的", ph:"ˈdʒɛləs", ex:"He felt jealous when his friend won the prize.", exZh:"朋友得獎的當下他感到嫉妒。", re:"He should feel happy for others.", reZh:"他該為別人感到開心。" },
{ t:"jelly", zh:"果凍", ph:"ˈdʒɛli", ex:"Grandma made sweet jelly from fresh fruit this morning.", exZh:"奶奶今天早上用新鮮水果做了甜果凍。", re:"I would love to try some.", reZh:"我好想吃吃看。" },
{ t:"judge", zh:"判斷", ph:"dʒʌdʒ", ex:"You should never judge a book by its cover.", exZh:"你絕不該以封面評斷一本書。", re:"That is a wise old saying.", reZh:"那是句有智慧的老話。" },
{ t:"kangaroo", zh:"袋鼠", ph:"ˌkæŋgəˈru", ex:"A kangaroo can jump very far with its strong legs.", exZh:"袋鼠能用強壯的腿跳得很遠。", re:"Australia has so many amazing animals.", reZh:"澳洲有好多神奇的動物。" },
{ t:"kindergarten", zh:"幼兒園", ph:"ˈkɪndɚˌgɑrtən", ex:"My little sister just started kindergarten this fall semester.", exZh:"我妹妹今年秋天剛上幼兒園。", re:"Does she enjoy her new school?", reZh:"她喜歡新的幼兒園嗎？" },
{ t:"knight", zh:"騎士", ph:"naɪt", ex:"The brave knight protected the castle from its enemies.", exZh:"勇敢的騎士保護城堡不受敵人侵犯。", re:"I love stories about brave knights.", reZh:"我喜歡勇敢騎士的故事。" },
{ t:"koala", zh:"無尾熊", ph:"koˈɑlə", ex:"The koala sleeps in the tree for twenty hours daily.", exZh:"無尾熊每天在樹上睡二十個小時。", re:"What a relaxing life it has!", reZh:"牠的生活真悠哉！" },
{ t:"lamb", zh:"羊羔", ph:"læm", ex:"The little lamb followed its mother around the farm.", exZh:"小羊在農場裡跟著媽媽走。", re:"Baby animals are always adorable.", reZh:"動物寶寶總是很可愛。" }
] },
{ level: 5, words: [
{ t:"lantern", zh:"燈籠", ph:"ˈlæntɚn", ex:"We lit a paper lantern at the festival last night.", exZh:"昨晚我們在慶典上點亮了紙燈籠。", re:"The lights must have looked lovely.", reZh:"燈光一定很美。" },
{ t:"laughter", zh:"笑聲", ph:"ˈlæftɚ", ex:"The room was filled with laughter during the party.", exZh:"派對期間房裡充滿笑聲。", re:"It sounds like great fun.", reZh:"聽起來很好玩。" },
{ t:"lay", zh:"躺下", ph:"le", ex:"Please lay the baby gently on the soft bed.", exZh:"請輕輕地把寶寶放在柔軟的床上。", re:"I will be very careful.", reZh:"我會非常小心。" },
{ t:"lean", zh:"瘦的", ph:"lin", ex:"Do not lean against that wall; the paint is wet.", exZh:"不要靠在那面牆上，油漆還沒乾。", re:"Thanks for telling me in time.", reZh:"謝謝你及時告訴我。" },
{ t:"less", zh:"較少", ph:"lɛs", ex:"Try to spend less time playing games every day.", exZh:"試著每天少花些時候玩遊戲。", re:"I know, I am working on it.", reZh:"我知道，我正在努力。" },
{ t:"level", zh:"水平", ph:"ˈlɛvəl", ex:"The water level of the river rose after the rain.", exZh:"下雨後河川的水位上升了。", re:"We should stay away from it.", reZh:"我們應該離河邊遠一點。" },
{ t:"lick", zh:"舔", ph:"lɪk", ex:"The happy dog ran over to lick my hand.", exZh:"開心的狗跑過來舔我的手。", re:"It must really like you.", reZh:"牠一定很喜歡你。" },
{ t:"lifeguard", zh:"救生員", ph:"ˈlaɪfˌgɑrd", ex:"The lifeguard saved a boy from the deep water.", exZh:"救生員從深水中救起一個男孩。", re:"He is a true hero.", reZh:"他是真正的英雄。" },
{ t:"likely", zh:"可能的", ph:"ˈlaɪkli", ex:"It is likely to rain heavily later this afternoon.", exZh:"今天下午稍晚很可能下大雨。", re:"I will bring my umbrella then.", reZh:"那我會帶傘。" },
{ t:"liquid", zh:"液體", ph:"ˈlɪkwɪd", ex:"Water turns from liquid to ice when it freezes.", exZh:"水結凍後會從液體變成冰。", re:"Science class taught us that too.", reZh:"自然課也教了這個。" },
{ t:"litter", zh:"垃圾", ph:"ˈlɪtɚ", ex:"People who litter in the park will be fined.", exZh:"在公園亂丟垃圾的人會被罰款。", re:"Good, the park stays clean.", reZh:"很好，公園能保持乾淨。" },
{ t:"lock", zh:"鎖", ph:"lɑk", ex:"Did you remember to lock the front door today?", exZh:"你今天記得鎖前門了嗎？", re:"Yes, I checked it twice.", reZh:"有，我檢查了兩次。" },
{ t:"lower", zh:"降低", ph:"ˈloɚ", ex:"Please lower your voice inside the school library.", exZh:"在學校圖書館裡請降低音量。", re:"Sorry, I forgot where I was.", reZh:"抱歉，我忘了這是圖書館。" },
{ t:"luggage", zh:"行李", ph:"ˈlʌgɪdʒ", ex:"He carried two pieces of luggage to the airport.", exZh:"他帶著兩件行李去機場。", re:"I hope they are not heavy.", reZh:"希望行李不會太重。" },
{ t:"magician", zh:"魔術師", ph:"məˈdʒɪʃən", ex:"The magician pulled a rabbit out of his hat.", exZh:"魔術師從帽子裡變出一隻兔子。", re:"How does he even do that?", reZh:"他到底怎麼辦到的？" },
{ t:"main", zh:"主要的", ph:"men", ex:"The main reason I study hard is my dream.", exZh:"我努力讀書的主因是我的夢想。", re:"Keep chasing it, my friend.", reZh:"朋友，繼續追夢吧。" },
{ t:"mall", zh:"商場", ph:"mɔl", ex:"We spent the whole afternoon shopping at the mall.", exZh:"我們整個下午都在購物中心逛街。", re:"Did you buy anything nice?", reZh:"你有買到好東西嗎？" },
{ t:"manager", zh:"經理", ph:"ˈmænɪdʒɚ", ex:"The manager of the store gave us a discount.", exZh:"店家的主管給了我們折扣。", re:"That was very kind of him.", reZh:"他人真好。" },
{ t:"married", zh:"已婚的", ph:"ˈmærid", ex:"My cousin got married in a beautiful garden last month.", exZh:"我表姊上個月在美麗的花園結婚了。", re:"The wedding must have been lovely.", reZh:"婚禮一定很浪漫。" },
{ t:"mass", zh:"質量", ph:"mæs", ex:"A large mass of dark clouds covered the sky.", exZh:"一大團烏雲遮住了天空。", re:"A storm is probably coming soon.", reZh:"暴風雨可能快到了。" },
{ t:"mat", zh:"墊子", ph:"mæt", ex:"Please wipe your shoes on the mat before entering.", exZh:"進屋前請在腳踏墊上擦鞋。", re:"Sure, I do not want to make a mess.", reZh:"好的，我不想弄髒地板。" },
{ t:"meaning", zh:"意義", ph:"ˈminɪŋ", ex:"Can you explain the meaning of this English word?", exZh:"你能解釋這個英文單字的意思嗎？", re:"Let me check the dictionary first.", reZh:"讓我先查一下字典。" },
{ t:"mechanic", zh:"機械師", ph:"məˈkænɪk", ex:"The mechanic fixed our car in just two hours.", exZh:"技師只花兩小時就修好我們的汽車。", re:"That was surprisingly fast work.", reZh:"速度快得驚人。" },
{ t:"meeting", zh:"會議", ph:"ˈmitɪŋ", ex:"The teachers are having a meeting in the office.", exZh:"老師們正在辦公室開會。", re:"I wonder what it is about.", reZh:"不知道是在討論什麼。" },
{ t:"melon", zh:"甜瓜", ph:"ˈmɛlən", ex:"This sweet melon is perfect for a hot day.", exZh:"這甜甜的甜瓜最合大熱天吃。", re:"Summer fruit is the best.", reZh:"夏天的水果最棒了。" },
{ t:"mention", zh:"提及", ph:"ˈmɛnʃən", ex:"Did he mention the trip when you saw him?", exZh:"你見到他的當下，他有提到旅行嗎？", re:"No, he did not say anything.", reZh:"沒有，他什麼都沒說。" },
{ t:"mess", zh:"亂七八糟", ph:"mɛs", ex:"Your desk is a mess; please clean it up.", exZh:"你的桌子亂七八糟，請整理一下。", re:"I will tidy it right away.", reZh:"我馬上整理。" },
{ t:"messy", zh:"凌亂的", ph:"ˈmɛsi", ex:"My room gets messy quickly when I am busy.", exZh:"我一忙房裡很快就變亂。", re:"Mine is exactly the same.", reZh:"我的房裡也一樣。" },
{ t:"method", zh:"方法", ph:"ˈmɛθəd", ex:"This new method makes learning English words much easier.", exZh:"這個新方法讓背英文單字容易多了。", re:"Please share it with me.", reZh:"請分享給我。" },
{ t:"midnight", zh:"午夜", ph:"ˈmɪdˌnaɪt", ex:"We stayed up until midnight watching the exciting movie.", exZh:"我們看那部刺激的電影看到半夜。", re:"You must be tired today.", reZh:"你今天一定很累。" },
{ t:"miracle", zh:"奇蹟", ph:"ˈmɪrəkəl", ex:"It was a miracle that everyone survived the crash.", exZh:"所有人都在事故中生還，真是奇蹟。", re:"Someone was surely watching over them.", reZh:"一定有人在保佑他們。" },
{ t:"modern", zh:"現代的", ph:"ˈmɑdɚn", ex:"This museum shows both modern art and old paintings.", exZh:"這間博物館展出現代藝術和古畫。", re:"I would love to visit it.", reZh:"我很想去參觀。" },
{ t:"mood", zh:"心情", ph:"mud", ex:"I am in a good mood because of the sunshine.", exZh:"因為陽光普照，我心情很好。", re:"Sunny days make everyone happy.", reZh:"晴天讓每個人都開心。" },
{ t:"murder", zh:"謀殺", ph:"ˈmɝdɚ", ex:"The detective solved the murder case in one week.", exZh:"偵探一週內偵破了謀殺案。", re:"He must be really clever.", reZh:"他一定非常聰明。" },
{ t:"mystery", zh:"謎團", ph:"ˈmɪstɚi", ex:"The old house on the hill remains a mystery.", exZh:"山丘上的老房子仍然是個謎。", re:"Maybe we should explore it someday.", reZh:"也許我們哪天該去一探究竟。" },
{ t:"natural", zh:"自然的", ph:"ˈnætʃɚəl", ex:"It is natural to feel nervous before a test.", exZh:"考前感到緊張是很自然的。", re:"That makes me feel much better.", reZh:"這讓我好受多了。" },
{ t:"nearby", zh:"周邊的", ph:"ˈnɪrˌbaɪ", ex:"There is a nearby park where we can play.", exZh:"周邊有座公園可以讓我們玩。", re:"Let us go there after lunch.", reZh:"午餐後我們就去吧。" },
{ t:"neat", zh:"整潔的", ph:"nit", ex:"His notes are always neat and easy to read.", exZh:"他的筆記總是整齊又容易閱讀。", re:"I wish mine looked like that.", reZh:"真希望我的筆記也那樣。" },
{ t:"needle", zh:"針", ph:"ˈnidəl", ex:"Grandma used a needle and thread to fix my shirt.", exZh:"奶奶用針線幫我補襯衫。", re:"Her sewing skills are amazing.", reZh:"她的縫紉技術真好。" },
{ t:"nephew", zh:"侄子", ph:"ˈnɛfju", ex:"My nephew starts elementary school this coming September.", exZh:"我姪子今年九月要上小學了。", re:"Time really flies so fast.", reZh:"光陰真的跑得飛快。" },
{ t:"niece", zh:"姪女", ph:"nis", ex:"My niece drew a picture of our whole family.", exZh:"我姪女畫了一張我們全家的圖。", re:"Children's drawings are so sweet.", reZh:"小孩子的畫真可愛。" },
{ t:"nod", zh:"點頭", ph:"nɑd", ex:"She gave a small nod to show she agreed.", exZh:"她輕輕點頭表示同意。", re:"So the plan is settled then.", reZh:"那計畫就這麼定了。" },
{ t:"nor", zh:"也不", ph:"nɔr", ex:"He speaks neither French nor German, only simple English.", exZh:"他不會說法語也不會說德語，只會簡單的英語。", re:"English is enough for traveling.", reZh:"旅行用英語就夠了。" },
{ t:"northern", zh:"北方的", ph:"ˈnɔrðɚn", ex:"The northern part of the country gets heavy snow.", exZh:"這個國家的北部會下大雪。", re:"I would love to see snow.", reZh:"我好想看雪。" },
{ t:"nowadays", zh:"現在", ph:"ˈnaʊəˌdez", ex:"Nowadays many students bring tablets to school every day.", exZh:"如今許多學生每天帶平板電腦上學。", re:"Technology changes the way we learn.", reZh:"科技改變了我們學習的方式。" },
{ t:"object", zh:"物體", ph:"ˈɑbdʒɛkt", ex:"What is that strange object on the teacher's desk?", exZh:"老師桌上那個奇怪的物體是什麼？", re:"I have no idea at all.", reZh:"我完全不知道。" },
{ t:"official", zh:"官方的", ph:"əˈfɪʃəl", ex:"The official announcement will be made early tomorrow morning.", exZh:"官方公告將於明天一早發布。", re:"Everyone is waiting for the news.", reZh:"大家都在等這個消息。" },
{ t:"operate", zh:"操作", ph:"ˈɑpəˌret", ex:"Only trained workers can operate this heavy machine safely.", exZh:"只有受訓的工人能安全操作這台重型機器。", re:"Safety rules must come first.", reZh:"安全規定必須擺第一。" },
{ t:"opinion", zh:"意見", ph:"əˈpɪnjən", ex:"In my opinion, this book is worth reading twice.", exZh:"依我看，這本書值得讀兩次。", re:"I will borrow it from you.", reZh:"那我跟你借。" },
{ t:"ordinary", zh:"普通的", ph:"ˈɔrdənɛri", ex:"It was an ordinary day until the surprise party.", exZh:"在驚喜派對之前，那只是平凡的一天。", re:"What a wonderful surprise that was!", reZh:"那真是美好的驚喜！" }
] },
{ level: 6, words: [
{ t:"owl", zh:"貓頭鷹", ph:"aʊl", ex:"An owl was hooting outside my window last night.", exZh:"昨晚一隻貓頭鷹在我窗外叫。", re:"Did it keep you awake?", reZh:"牠有吵到你睡覺嗎？" },
{ t:"pain", zh:"疼痛", ph:"pen", ex:"I felt a sharp pain in my back this morning.", exZh:"今天早上我的背一陣劇痛。", re:"You should see a doctor soon.", reZh:"你應該快去看醫生。" },
{ t:"pal", zh:"朋友", ph:"pæl", ex:"Jack has been my best pal since elementary school.", exZh:"傑克從小學開始就是我最好的朋友。", re:"Old friendships are truly precious.", reZh:"老朋友的情誼真珍貴。" },
{ t:"pale", zh:"蒼白的", ph:"pel", ex:"You look pale today; are you feeling all right?", exZh:"你今天臉色蒼白，還好嗎？", re:"I did not sleep well last night.", reZh:"我昨晚沒睡好。" },
{ t:"pardon", zh:"原諒", ph:"ˈpɑrdən", ex:"Pardon me, could you say that again more slowly?", exZh:"不好意思，可以再慢慢說一次嗎？", re:"Sure, I will speak more clearly.", reZh:"當然，我會說清楚一點。" },
{ t:"parrot", zh:"鸚鵡", ph:"ˈpærət", ex:"My parrot can say hello in three different languages.", exZh:"我的鸚鵡會用三種語言說哈囉。", re:"That is one smart bird!", reZh:"那真是一隻聰明的鳥！" },
{ t:"passage", zh:"通道", ph:"ˈpæsɪdʒ", ex:"We read a short passage about whales in class.", exZh:"我們在課堂上讀了一篇關於鯨魚的短文。", re:"Whales are such interesting animals.", reZh:"鯨魚是很有趣的動物。" },
{ t:"pasta", zh:"義大利麵", ph:"ˈpɑstə", ex:"Dad cooked creamy pasta for us on Sunday night.", exZh:"爸爸星期天晚上煮了奶油義大利麵給我們吃。", re:"Your dad is a great cook.", reZh:"你爸爸真會做菜。" },
{ t:"patient", zh:"患者", ph:"ˈpeʃənt", ex:"The kind doctor spoke gently to the nervous patient.", exZh:"親切的醫生溫和地對緊張的病人說話。", re:"A kind doctor makes a difference.", reZh:"親切的醫生真的差很多。" },
{ t:"peace", zh:"和平", ph:"pis", ex:"Everyone in the world hopes to live in peace.", exZh:"世界上每個人都希望生活在和平之中。", re:"I truly hope that day comes.", reZh:"我真心希望那天到來。" },
{ t:"peanut", zh:"花生", ph:"ˈpiˌnʌt", ex:"My little brother is allergic to peanut butter.", exZh:"我弟弟對花生醬過敏。", re:"He has to be very careful.", reZh:"他必須非常小心。" },
{ t:"percent", zh:"百分比", ph:"pɚˈsɛnt", ex:"About ninety percent of the students passed the test.", exZh:"大約百分之九十的學生通過了考試。", re:"That is a really high rate.", reZh:"那是很高的通過率。" },
{ t:"perform", zh:"表演", ph:"pɚˈfɔrm", ex:"Our band will perform at the school fair tomorrow.", exZh:"我們樂團明天會在園遊會表演。", re:"I will be there cheering for you.", reZh:"我會去為你們加油。" },
{ t:"personal", zh:"個人的", ph:"ˈpɝsənəl", ex:"Please do not read my diary; it is personal.", exZh:"請不要看我的日記，那是私人的。", re:"Sorry, I did not mean to.", reZh:"抱歉，我不是故意的。" },
{ t:"pigeon", zh:"鴿子", ph:"ˈpɪdʒən", ex:"A pigeon landed on the roof of our school.", exZh:"一隻鴿子停在我們學校的屋頂上。", re:"They are everywhere in this city.", reZh:"這座城市到處都是鴿子。" },
{ t:"pilot", zh:"飛行員", ph:"ˈpaɪlət", ex:"The pilot landed the plane safely in the storm.", exZh:"機師在暴風雨中讓飛機安全降落。", re:"The passengers must have been thankful.", reZh:"乘客們一定很感激。" },
{ t:"pity", zh:"遺憾", ph:"ˈpɪti", ex:"It is a pity that you missed the concert.", exZh:"你錯過演唱會真是可惜。", re:"I hope there will be another one.", reZh:"希望還會再辦一場。" },
{ t:"plastic", zh:"塑膠", ph:"ˈplæstɪk", ex:"We should use less plastic to protect the ocean.", exZh:"我們應該少用塑膠來保護海洋。", re:"I bring my own bag now.", reZh:"我現在都自備購物袋。" },
{ t:"pleasant", zh:"令人愉快的", ph:"ˈplɛzənt", ex:"We had a pleasant afternoon walking in the park.", exZh:"我們在公園散步度過了愉快的下午。", re:"We should do it again soon.", reZh:"我們應該很快再去一次。" },
{ t:"plenty", zh:"很多", ph:"ˈplɛnti", ex:"There is plenty of food left for everyone here.", exZh:"這裡剩下的食物夠每個人吃。", re:"Great, I am still very hungry.", reZh:"太好了，我還很餓。" },
{ t:"plus", zh:"加上", ph:"plʌs", ex:"Five plus three equals eight, as everyone knows.", exZh:"五加三等於八，大家都知道。", re:"Math basics are really important.", reZh:"數學基礎真的很重要。" },
{ t:"poetry", zh:"詩歌", ph:"ˈpoətri", ex:"Our teacher asked us to read some modern poetry.", exZh:"老師要我們讀一些現代詩。", re:"Poetry can be hard to understand.", reZh:"詩有的地方很不好懂。" },
{ t:"policeman", zh:"警察", ph:"pəˈlismən", ex:"The policeman helped the lost child find her mother.", exZh:"警察幫走失的小孩找到她的媽媽。", re:"What a heartwarming story that is.", reZh:"真是溫馨的故事。" },
{ t:"pollute", zh:"污染", ph:"pəˈlut", ex:"Factories should not pollute the rivers with dirty waste.", exZh:"工廠不應該用廢水污染河川。", re:"Clean water matters to everyone.", reZh:"乾淨的水對每個人都重要。" },
{ t:"population", zh:"人口", ph:"ˌpɑpjəˈleʃən", ex:"The population of this city grows larger every year.", exZh:"這座城市的人口每年都在增加。", re:"Housing will become a problem.", reZh:"住房會變成問題。" },
{ t:"positive", zh:"正面的", ph:"ˈpɑzətɪv", ex:"Try to stay positive even when things get hard.", exZh:"即使事情變困難也要保持正向。", re:"Your attitude really inspires me.", reZh:"你的態度真的激勵了我。" },
{ t:"power", zh:"力量", ph:"ˈpaʊɚ", ex:"The storm cut off the power for three hours.", exZh:"暴風雨造成停電三小時。", re:"We had to use candles.", reZh:"我們只好點蠟燭。" },
{ t:"praise", zh:"稱讚", ph:"prez", ex:"The coach gave us praise for our great teamwork.", exZh:"教練稱讚我們出色的團隊合作。", re:"That made everyone feel proud.", reZh:"那讓大家都很驕傲。" },
{ t:"pressure", zh:"壓力", ph:"ˈprɛʃɚ", ex:"Students often feel pressure before a big final exam.", exZh:"學生在期末大考前常感到壓力。", re:"Taking deep breaths can help.", reZh:"深呼吸會有幫助。" },
{ t:"prevent", zh:"預防", ph:"prɪˈvɛnt", ex:"Washing your hands often can prevent many common illnesses.", exZh:"勤洗手可以預防許多常見疾病。", re:"I wash mine before every meal.", reZh:"我每餐前都會洗手。" },
{ t:"principal", zh:"校長", ph:"ˈprɪnsəpəl", ex:"The principal gave a speech at the graduation ceremony.", exZh:"校長在畢業典禮上致詞。", re:"Her words were very encouraging.", reZh:"她的話非常鼓舞人心。" },
{ t:"prison", zh:"監獄", ph:"ˈprɪzən", ex:"The thief spent five years in prison for stealing.", exZh:"那個小偷因偷竊在監獄待了五年。", re:"I hope he has changed now.", reZh:"希望他現在已經改過。" },
{ t:"private", zh:"私人的", ph:"ˈpraɪvɪt", ex:"This is a private garden, so we cannot enter.", exZh:"這是私人花園，我們不能進去。", re:"Let us find a public park instead.", reZh:"我們改去公共公園吧。" },
{ t:"producer", zh:"製片人", ph:"prəˈdusɚ", ex:"The producer spent two years making this exciting movie.", exZh:"製片人花了兩年拍這部精彩的電影。", re:"No wonder it looks so good.", reZh:"難怪拍得這麼好。" },
{ t:"professional", zh:"專業人士", ph:"prəˈfɛʃənəl", ex:"She hired a professional to design her new house.", exZh:"她請了專業人士設計新房子。", re:"Experts always do a better job.", reZh:"專家做得就是比較好。" },
{ t:"progress", zh:"進度", ph:"ˈprɑgrɛs", ex:"You have made great progress in English this year.", exZh:"你今年英文進步很多。", re:"Thanks, I practice every single day.", reZh:"謝謝，我每天都練習。" },
{ t:"pronounce", zh:"發音", ph:"prəˈnaʊns", ex:"Some students cannot pronounce this long English word correctly.", exZh:"有些學生無法正確唸出這個長英文單字。", re:"Practice will make it easier.", reZh:"多練習就會變簡單。" },
{ t:"proper", zh:"正確的", ph:"ˈprɑpɚ", ex:"Wearing proper clothes to an interview is very important.", exZh:"面試穿合宜的服裝很重要。", re:"First impressions really do matter.", reZh:"第一印象真的很重要。" },
{ t:"provide", zh:"提供", ph:"prəˈvaɪd", ex:"The school will provide free lunch for every student.", exZh:"學校將為每位學生提供免費午餐。", re:"That helps many families a lot.", reZh:"那幫了很多家庭大忙。" },
{ t:"punishment", zh:"懲罰", ph:"ˈpʌnɪʃmənt", ex:"His punishment was cleaning the classroom for a week.", exZh:"他的處罰是打掃教室一星期。", re:"That seems fair to me.", reZh:"我覺得那很公平。" },
{ t:"purse", zh:"錢包", ph:"pɝs", ex:"She left her purse on the bus this morning.", exZh:"她今天早上把錢包忘在公車上。", re:"Did anyone return it to her?", reZh:"有人把錢包還她嗎？" },
{ t:"quality", zh:"品質", ph:"ˈkwɑləti", ex:"This jacket is expensive, but the quality is excellent.", exZh:"這件外套很貴，但品質非常好。", re:"Good things are worth the price.", reZh:"好東西值得這個價錢。" },
{ t:"quarter", zh:"四分之一", ph:"ˈkwɔrtɚ", ex:"The movie starts at a quarter past seven tonight.", exZh:"電影今晚七點十五分開始。", re:"We should leave home by six.", reZh:"我們六點前該出門。" },
{ t:"rate", zh:"速率", ph:"ret", ex:"The success rate of the new plan is high.", exZh:"新計畫的成功率很高。", re:"That is really good news.", reZh:"那真是好消息。" },
{ t:"raw", zh:"生的", ph:"rɔ", ex:"Eating raw fish is popular in Japanese restaurants.", exZh:"吃生魚片在日本料理店很流行。", re:"I love sushi very much.", reZh:"我非常喜歡壽司。" },
{ t:"recently", zh:"前不久", ph:"ˈrisəntli", ex:"I have not seen him recently because he moved.", exZh:"因為他搬家了，我這陣子都沒見到他。", re:"You should give him a call.", reZh:"你應該打通電話給他。" },
{ t:"recover", zh:"恢復", ph:"rɪˈkʌvɚ", ex:"It took him two weeks to recover from the flu.", exZh:"他花了兩週才從流感中康復。", re:"Glad he is feeling better now.", reZh:"很高興他現在好多了。" },
{ t:"reduce", zh:"減少", ph:"rɪˈdus", ex:"We should reduce the amount of trash we make.", exZh:"我們應該減少製造的垃圾量。", re:"Recycling is a good first step.", reZh:"回收是很好的第一步。" },
{ t:"regular", zh:"定期的", ph:"ˈrɛgjulɚ", ex:"Regular exercise keeps both your body and mind healthy.", exZh:"規律運動讓身心都保持健康。", re:"I jog three times a week.", reZh:"我每週慢跑三次。" },
{ t:"relative", zh:"親戚", ph:"ˈrɛlətɪv", ex:"A relative from Canada is visiting us this week.", exZh:"一位加拿大的親戚這週來拜訪我們。", re:"How long will they stay here?", reZh:"他們會待多久？" }
] },
{ level: 7, words: [
{ t:"remove", zh:"移除", ph:"rɪˈmuv", ex:"Please remove your shoes before you enter the house.", exZh:"進屋前請把鞋子脫掉。", re:"Of course, where should I put them?", reZh:"當然，我該把鞋放哪裡？" },
{ t:"report", zh:"報告", ph:"rɪˈpɔrt", ex:"I have to finish my science report by Friday.", exZh:"我必須在星期五前完成自然科報告。", re:"You had better start working now.", reZh:"你最好現在就開始寫。" },
{ t:"responsible", zh:"負責任的", ph:"rɪˈspɑnsəbəl", ex:"Each student is responsible for cleaning the classroom today.", exZh:"今天每位學生都要負責打掃教室。", re:"Teamwork makes the job easier.", reZh:"分工合作讓工作更輕鬆。" },
{ t:"rob", zh:"搶劫", ph:"rɑb", ex:"Two men tried to rob the bank last night.", exZh:"昨晚有兩名男子企圖搶劫銀行。", re:"I hope the police caught them.", reZh:"希望警察抓到他們了。" },
{ t:"role", zh:"角色", ph:"rol", ex:"She played the leading role in the school play.", exZh:"她在學校戲劇中擔任主角。", re:"Her acting was truly wonderful.", reZh:"她的演技真的很棒。" },
{ t:"royal", zh:"皇家的", ph:"ˈrɔɪəl", ex:"The royal family will visit our city next month.", exZh:"皇室下個月將訪問我們的城市。", re:"The streets will be so crowded.", reZh:"街上一定會很擁擠。" },
{ t:"rubber", zh:"橡膠", ph:"ˈrʌbɚ", ex:"These boots are made of rubber, so they are waterproof.", exZh:"這雙靴子是橡膠做的，所以防水。", re:"Perfect for the rainy season.", reZh:"很適合雨季穿。" },
{ t:"runner", zh:"跑步者", ph:"ˈrʌnɚ", ex:"The fastest runner in our class won the race.", exZh:"我們班跑最快的人贏了比賽。", re:"He trains hard every single day.", reZh:"他每天都努力訓練。" },
{ t:"sailor", zh:"水手", ph:"ˈselɚ", ex:"My uncle was a sailor who traveled around the world.", exZh:"我叔叔曾是環遊世界的水手。", re:"He must have amazing stories.", reZh:"他一定有很多精彩的故事。" },
{ t:"sauce", zh:"醬汁", ph:"sɔs", ex:"This pasta tastes better with some tomato sauce.", exZh:"這義大利麵加點番茄醬汁更好吃。", re:"I will add a little more.", reZh:"我會再加一點。" },
{ t:"scenery", zh:"風景", ph:"ˈsinɚi", ex:"The scenery along the coast took my breath away.", exZh:"沿海的風景美得讓我屏息。", re:"You should take some photos.", reZh:"你應該拍些照片。" },
{ t:"scientist", zh:"科學家", ph:"ˈsaɪəntɪst", ex:"The scientist spent ten years studying the deep ocean.", exZh:"這位科學家花了十年研究深海。", re:"That takes a lot of patience.", reZh:"那需要很大的耐心。" },
{ t:"screen", zh:"螢幕", ph:"skrin", ex:"Looking at a screen too long hurts your eyes.", exZh:"盯著螢幕太久會傷眼睛。", re:"I should take more breaks.", reZh:"我應該多休息。" },
{ t:"search", zh:"搜尋", ph:"sɝtʃ", ex:"We had to search the whole house for the keys.", exZh:"我們必須找遍整間屋子找鑰匙。", re:"Where did you finally find them?", reZh:"你們最後在哪找到的？" },
{ t:"selfish", zh:"自私的", ph:"ˈsɛlfɪʃ", ex:"It is selfish to keep all the snacks yourself.", exZh:"把零食全留給自己很自私。", re:"You are right, I will share.", reZh:"你說得對，我會分享。" },
{ t:"sense", zh:"感官", ph:"sɛns", ex:"Wearing a coat in this cold weather makes sense.", exZh:"這麼冷的天穿外套很合理。", re:"I will grab mine right now.", reZh:"我現在就去拿外套。" },
{ t:"serious", zh:"嚴肅的", ph:"ˈsɪriəs", ex:"He is very serious about practicing the piano daily.", exZh:"他非常認真地每天練鋼琴。", re:"His hard work will pay off.", reZh:"他的努力會有回報的。" },
{ t:"service", zh:"服務", ph:"ˈsɝvɪs", ex:"The service at this restaurant is fast and friendly.", exZh:"這家餐廳的服務快速又親切。", re:"That is why I keep coming back.", reZh:"這就是我常來的原因。" },
{ t:"shadow", zh:"陰影", ph:"ˈʃædo", ex:"The tree cast a long shadow across the yard.", exZh:"樹在院子裡投下長長的影子。", re:"It gives us nice cool shade.", reZh:"它給我們涼爽的樹蔭。" },
{ t:"sheet", zh:"床單", ph:"ʃit", ex:"I put a clean sheet on the bed this morning.", exZh:"我今天早上鋪了乾淨的床單。", re:"Fresh sheets always feel so nice.", reZh:"乾淨的床單總是很舒服。" },
{ t:"shell", zh:"殼", ph:"ʃɛl", ex:"She found a beautiful shell on the beach today.", exZh:"她今天在海灘上找到一個漂亮的貝殼。", re:"Can I see it later?", reZh:"待會可以給我看看嗎？" },
{ t:"shorts", zh:"短褲", ph:"ʃɔrts", ex:"I wear shorts when the weather gets too hot.", exZh:"天氣太熱時我會穿短褲。", re:"Summer clothes are so comfortable.", reZh:"夏天的衣服真舒服。" },
{ t:"shrimp", zh:"蝦", ph:"ʃrɪmp", ex:"Mom cooked fried rice with shrimp for dinner tonight.", exZh:"媽媽今晚煮了蝦仁炒飯當晚餐。", re:"That is my favorite dish!", reZh:"那是我最愛的菜！" },
{ t:"sight", zh:"視力", ph:"saɪt", ex:"The fireworks were a beautiful sight last night.", exZh:"昨晚的煙火景象非常美麗。", re:"I wish I had seen them.", reZh:"真希望我也看到了。" },
{ t:"silent", zh:"無聲的", ph:"ˈsaɪlənt", ex:"The classroom fell silent when the teacher walked in.", exZh:"老師走進來時教室變得安靜。", re:"Everyone respects her a lot.", reZh:"大家都很尊敬她。" },
{ t:"silly", zh:"傻的", ph:"ˈsɪli", ex:"He told a silly joke that made everyone laugh.", exZh:"他講了一個傻笑話，大家都笑了。", re:"I love his sense of humor.", reZh:"我喜歡他的幽默感。" },
{ t:"simply", zh:"簡單地", ph:"ˈsɪmpli", ex:"You can solve this problem simply by reading carefully.", exZh:"只要仔細閱讀就能簡單解決這個問題。", re:"Thanks, I will try that now.", reZh:"謝謝，我現在就試試。" },
{ t:"single", zh:"單一的", ph:"ˈsɪŋgəl", ex:"There is not a single cloud in the sky today.", exZh:"今天天空中沒有一朵雲。", re:"Perfect weather for a picnic.", reZh:"是野餐的完美天氣。" },
{ t:"situation", zh:"情況", ph:"ˌsɪtʃuˈeʃən", ex:"The situation got better after we talked it over.", exZh:"我們談開之後情況好轉了。", re:"Communication really solves many problems.", reZh:"溝通真的能解決很多問題。" },
{ t:"skin", zh:"皮膚", ph:"skɪn", ex:"Too much sun can damage your skin very badly.", exZh:"曬太多太陽會嚴重傷害皮膚。", re:"I always wear sunscreen outside.", reZh:"我在外面都會擦防曬。" },
{ t:"slender", zh:"苗條的", ph:"ˈslɛndɚ", ex:"The dancer has a slender figure and moves gracefully.", exZh:"那位舞者身材苗條，動作優雅。", re:"She practices ballet every day.", reZh:"她每天練芭蕾。" },
{ t:"slim", zh:"瘦的", ph:"slɪm", ex:"He stayed slim by jogging every single morning.", exZh:"他每天早上慢跑保持苗條。", re:"I should start exercising too.", reZh:"我也該開始運動了。" },
{ t:"slipper", zh:"拖鞋", ph:"ˈslɪpɚ", ex:"I lost one slipper somewhere under the big bed.", exZh:"我的一隻拖鞋掉在大床底下某處。", re:"Let me help you look for it.", reZh:"我幫你找找。" },
{ t:"snail", zh:"蝸牛", ph:"snel", ex:"A snail crawled slowly across the garden path.", exZh:"一隻蝸牛慢慢爬過花園小徑。", re:"They always take their time.", reZh:"牠們總是慢條斯理。" },
{ t:"snowman", zh:"雪人", ph:"ˈsnoˌmæn", ex:"The kids built a huge snowman in the park.", exZh:"孩子們在公園裡堆了一個大雪人。", re:"Winter is so much fun.", reZh:"冬天真好玩。" },
{ t:"social", zh:"社會的", ph:"ˈsoʃəl", ex:"School clubs are great for building social skills.", exZh:"學校社團很適合培養社交能力。", re:"I just joined the drama club.", reZh:"我剛加入戲劇社。" },
{ t:"solve", zh:"解決", ph:"sɑlv", ex:"Let us work together to solve this math problem.", exZh:"我們一起合作解這道數學題吧。", re:"Two heads are better than one.", reZh:"兩個人一起想比較快。" },
{ t:"sort", zh:"種類", ph:"sɔrt", ex:"Please sort these books by size on the shelf.", exZh:"請把這些書按大小排在架上。", re:"I will finish it in ten minutes.", reZh:"我十分鐘內會弄好。" },
{ t:"speaker", zh:"發言人", ph:"ˈspikɚ", ex:"The speaker gave a touching speech at the ceremony.", exZh:"演講者在典禮上發表了感人的演說。", re:"Many people were moved to tears.", reZh:"很多人感動到流淚。" },
{ t:"speed", zh:"速度", ph:"spid", ex:"The new train travels at a very high speed.", exZh:"這列新火車以非常高的速度行駛。", re:"We will arrive in no time.", reZh:"我們很快就會到。" },
{ t:"spot", zh:"地點", ph:"spɑt", ex:"We found a quiet spot for our family picnic.", exZh:"我們找到一個安靜的地點野餐。", re:"It sounds like a perfect place.", reZh:"聽起來是完美的地方。" },
{ t:"stadium", zh:"體育場", ph:"ˈstediəm", ex:"Thousands of fans filled the stadium for the game.", exZh:"數千名球迷擠滿體育場看比賽。", re:"The atmosphere must have been exciting.", reZh:"氣氛一定很熱烈。" },
{ t:"standard", zh:"標準", ph:"ˈstændɚd", ex:"Her writing meets the standard for the national contest.", exZh:"她的寫作符合全國比賽的標準。", re:"I believe she will win.", reZh:"我相信她會獲勝。" },
{ t:"statue", zh:"雕像", ph:"ˈstætʃu", ex:"There is an old statue in the city square.", exZh:"市區廣場上有一座古老的雕像。", re:"Who does the statue honor?", reZh:"那座雕像紀念誰？" },
{ t:"steal", zh:"偷竊", ph:"stil", ex:"It is wrong to steal things from other people.", exZh:"偷別人的東西是不對的。", re:"Honesty is always the best choice.", reZh:"誠實永遠是最好的選擇。" },
{ t:"storm", zh:"風暴", ph:"stɔrm", ex:"The storm knocked down several trees on our street.", exZh:"暴風雨吹倒了我們街上好幾棵樹。", re:"I am glad no one was hurt.", reZh:"還好沒有人受傷。" },
{ t:"straight", zh:"直的", ph:"stret", ex:"Go straight for two blocks and then turn left.", exZh:"直走兩個街區然後左轉。", re:"Thank you for the clear directions.", reZh:"謝謝你清楚的指引。" },
{ t:"stress", zh:"壓力", ph:"strɛs", ex:"Listening to music helps me deal with my stress.", exZh:"聽音樂幫助我釋放壓力。", re:"I do the same thing too.", reZh:"我也是這樣做。" },
{ t:"string", zh:"繩子", ph:"strɪŋ", ex:"She tied the balloon with a long piece of string.", exZh:"她用一條長繩子綁住氣球。", re:"Now it will not fly away.", reZh:"這樣它就不會飛走了。" },
{ t:"studio", zh:"工作室", ph:"ˈstudio", ex:"The singer recorded her new album in a studio.", exZh:"那位歌手在錄音室錄製新專輯。", re:"I cannot wait to hear it.", reZh:"我等不及想聽了。" }
] },
{ level: 8, words: [
{ t:"subject", zh:"科目", ph:"ˈsʌbdʒɛkt", ex:"English is my favorite subject at school this year.", exZh:"英文是我今年在學校最喜歡的科目。", re:"I like history the most.", reZh:"我最喜歡歷史。" },
{ t:"subway", zh:"地下鐵", ph:"ˈsʌbˌwe", ex:"We took the subway to the museum this morning.", exZh:"我們今天早上搭地鐵去博物館。", re:"It is much faster than the bus.", reZh:"它比公車快多了。" },
{ t:"success", zh:"成功", ph:"səkˈsɛs", ex:"Her success came from many years of hard work.", exZh:"她的成功來自多年的努力。", re:"She really deserves all of it.", reZh:"她真的值得這一切。" },
{ t:"suddenly", zh:"突然", ph:"ˈsʌdənli", ex:"The rain started suddenly while we were walking home.", exZh:"我們走路回家時突然下起雨。", re:"I hope you did not get wet.", reZh:"希望你們沒有淋濕。" },
{ t:"suggest", zh:"建議", ph:"səgˈdʒɛst", ex:"I suggest that we leave a little earlier tomorrow.", exZh:"我建議我們明天早一點出發。", re:"Good idea, traffic is always heavy.", reZh:"好主意，交通總是很擁擠。" },
{ t:"sum", zh:"總和", ph:"sʌm", ex:"We paid a large sum of money for the trip.", exZh:"我們為這趟旅行付了一大筆錢。", re:"I hope it was worth it.", reZh:"希望這錢花得值得。" },
{ t:"sunset", zh:"日落", ph:"ˈsʌnˌsɛt", ex:"We watched the sunset together on the beach yesterday.", exZh:"我們昨天在海灘上一起看日落。", re:"That sounds really romantic to me.", reZh:"那聽起來真浪漫。" },
{ t:"surf", zh:"衝浪", ph:"sɝf", ex:"My cousin taught me how to surf last summer.", exZh:"我表哥去年夏天教我衝浪。", re:"Was it hard to learn?", reZh:"很難學嗎？" },
{ t:"swallow", zh:"吞下", ph:"ˈswɑlo", ex:"This pill is too big for me to swallow.", exZh:"這顆藥太大，我吞不下去。", re:"Try taking it with more water.", reZh:"試著配多一點水吞。" },
{ t:"sweep", zh:"掃", ph:"swip", ex:"Please sweep the floor before our guests arrive tonight.", exZh:"請在今晚客人到之前把地板掃乾淨。", re:"Sure, I will do it now.", reZh:"好，我現在就去掃。" },
{ t:"tale", zh:"故事", ph:"tel", ex:"Grandma told us a fairy tale before bed.", exZh:"奶奶睡前跟我們講了一個童話故事。", re:"Which one did she tell?", reZh:"她講了哪一個？" },
{ t:"tank", zh:"儲存槽", ph:"tæŋk", ex:"The fish tank in the living room needs cleaning.", exZh:"客廳的魚缸需要清理了。", re:"I will clean it this weekend.", reZh:"我這個週末會清理。" },
{ t:"tasty", zh:"好吃的", ph:"ˈtesti", ex:"The soup you made last night was really tasty.", exZh:"你昨晚煮的湯真的很好喝。", re:"Thanks, I found a new recipe.", reZh:"謝謝，我找到一個新食譜。" },
{ t:"tear", zh:"撕", ph:"tɛr", ex:"Be careful not to tear the pages of the book.", exZh:"小心別把書頁撕破了。", re:"Do not worry, I will be gentle.", reZh:"別擔心，我會很小心。" },
{ t:"term", zh:"學期", ph:"tɝm", ex:"We have two big exams at the end of this term.", exZh:"這學期末我們有兩場大考。", re:"We should start studying early.", reZh:"我們應該早點開始準備。" },
{ t:"thief", zh:"小偷", ph:"θif", ex:"The police caught the thief at the train station.", exZh:"警察在火車站抓到了小偷。", re:"That is a big relief.", reZh:"那真是鬆了一口氣。" },
{ t:"thumb", zh:"大拇指", ph:"θʌm", ex:"I hurt my thumb while I was cutting vegetables.", exZh:"我切菜時弄傷了大拇指。", re:"You should put a bandage on it.", reZh:"你應該包紮一下。" },
{ t:"tiny", zh:"微小的", ph:"ˈtaɪni", ex:"The puppy is so tiny that it fits in my hand.", exZh:"這隻小狗小到可以放在我手裡。", re:"Oh, that sounds so cute!", reZh:"喔，聽起來好可愛！" },
{ t:"ton", zh:"噸", ph:"tʌn", ex:"That old truck can carry over a ton of sand.", exZh:"那輛舊卡車能載超過一噸的沙子。", re:"Wow, that is really heavy.", reZh:"哇，那真的很重。" },
{ t:"tool", zh:"工具", ph:"tul", ex:"A hammer is a useful tool for fixing things.", exZh:"鐵鎚是修理東西的好用工具。", re:"Every home should have one.", reZh:"每個家裡都該有一支。" },
{ t:"total", zh:"總共", ph:"ˈtotəl", ex:"The total cost of our dinner was thirty dollars.", exZh:"我們晚餐的總花費是三十元。", re:"Let us split the bill evenly.", reZh:"我們平分帳單吧。" },
{ t:"tourist", zh:"遊客", ph:"ˈtʊrɪst", ex:"Every tourist wants to visit that famous night market.", exZh:"每個觀光客都想去那個有名的夜市。", re:"The food there is amazing.", reZh:"那裡的食物很棒。" },
{ t:"trade", zh:"交易", ph:"tred", ex:"The two countries trade goods with each other often.", exZh:"這兩個國家經常互相貿易商品。", re:"Trade helps both sides grow.", reZh:"貿易幫助雙方成長。" },
{ t:"traditional", zh:"傳統的", ph:"trəˈdɪʃənəl", ex:"My family cooks traditional food during Chinese New Year.", exZh:"我們家在農曆新年會煮傳統食物。", re:"That must taste really good.", reZh:"那一定很好吃。" },
{ t:"tray", zh:"托盤", ph:"tre", ex:"The waiter carried our drinks on a silver tray.", exZh:"服務生用銀色托盤端我們的飲料。", re:"He balanced it so well.", reZh:"他平衡得真好。" },
{ t:"triangle", zh:"三角形", ph:"ˈtraɪˌæŋgəl", ex:"We learned how to draw a triangle in class.", exZh:"我們在課堂上學了怎麼畫三角形。", re:"Geometry is fun for me.", reZh:"我覺得幾何很有趣。" },
{ t:"truth", zh:"真實", ph:"truθ", ex:"You should always tell the truth to your friends.", exZh:"你應該永遠對朋友說實話。", re:"Honesty keeps a friendship strong.", reZh:"誠實讓友誼更堅固。" },
{ t:"tutor", zh:"導師", ph:"ˈtutɚ", ex:"My tutor helps me with math twice a week.", exZh:"我的家教每週幫我補兩次數學。", re:"Has your grade improved yet?", reZh:"你的成績進步了嗎？" },
{ t:"unhappy", zh:"不快樂的", ph:"ʌnˈhæpi", ex:"She looked unhappy after reading the test results.", exZh:"她看完考試結果後看起來悶悶不樂。", re:"Maybe we should cheer her up.", reZh:"也許我們該讓她開心一下。" },
{ t:"universe", zh:"宇宙", ph:"ˈjunɪˌvɝs", ex:"Scientists are still learning secrets about the universe.", exZh:"科學家仍在探索宇宙的祕密。", re:"Space is full of mysteries.", reZh:"太空充滿了謎團。" },
{ t:"upon", zh:"在...上", ph:"əˈpɑn", ex:"Once upon a time, a king lived in this castle.", exZh:"很久以前，有位國王住在這座城堡裡。", re:"I love stories that start like that.", reZh:"我喜歡這樣開頭的故事。" },
{ t:"usual", zh:"通常的", ph:"ˈjuʒuəl", ex:"I met her at the usual place after school.", exZh:"放學後我在老地方跟她見面。", re:"You two meet there every day.", reZh:"你們兩個每天都在那見面。" },
{ t:"valley", zh:"山坳", ph:"ˈvæli", ex:"A small river runs through the green valley below.", exZh:"一條小河流經下方翠綠的山坳。", re:"The view must be beautiful.", reZh:"景色一定很美。" },
{ t:"value", zh:"價值", ph:"ˈvælju", ex:"We should value the time we spend with family.", exZh:"我們應該珍惜與家人相處的時光。", re:"Family always comes first for me.", reZh:"對我而言家人永遠是第一位。" },
{ t:"vocabulary", zh:"詞彙", ph:"voˈkæbjəˌlɛri", ex:"Reading English novels helps me build my vocabulary fast.", exZh:"讀英文小說幫助我快速累積詞彙。", re:"I should try that method too.", reZh:"我也該試試這個方法。" },
{ t:"volunteer", zh:"志願者", ph:"ˌvɑlənˈtɪr", ex:"My sister works as a volunteer at the hospital.", exZh:"我姊姊在醫院當志工。", re:"She has such a kind heart.", reZh:"她的心地真善良。" },
{ t:"warn", zh:"警告", ph:"wɔrn", ex:"The teacher had to warn us about the deadline.", exZh:"老師必須警告我們注意截止日期。", re:"I almost forgot about it.", reZh:"我差點忘了這件事。" },
{ t:"wealthy", zh:"富有的", ph:"ˈwɛlθi", ex:"That wealthy man gave a lot of money to charity.", exZh:"那位富有的人捐了很多錢給慈善機構。", re:"That is very generous of him.", reZh:"他非常慷慨。" },
{ t:"website", zh:"網站", ph:"ˈwɛbˌsaɪt", ex:"Our school built a new website for the students.", exZh:"我們學校為學生建了新網站。", re:"I will check it out tonight.", reZh:"我今晚會去看看。" },
{ t:"weigh", zh:"稱重", ph:"we", ex:"The doctor asked me to weigh myself every morning.", exZh:"醫生要我每天早上量體重。", re:"That is a healthy habit.", reZh:"那是健康的習慣。" },
{ t:"western", zh:"西方的", ph:"ˈwɛstɚn", ex:"We watched an old western movie with my grandfather.", exZh:"我們和爺爺看了一部老西部電影。", re:"Those classic films never get old.", reZh:"那些經典電影永不退流行。" },
{ t:"whenever", zh:"無論何時", ph:"wɛnˈɛvɚ", ex:"You can call me whenever you need any help.", exZh:"你需要幫忙時隨時可以打給我。", re:"Thanks, that means a lot.", reZh:"謝謝，這對我意義重大。" },
{ t:"whisper", zh:"低聲說", ph:"ˈwɪspɚ", ex:"Please whisper because the baby is sleeping next door.", exZh:"請小聲說話，因為寶寶在隔壁睡覺。", re:"Sorry, I will keep it down.", reZh:"抱歉，我會小聲一點。" },
{ t:"willing", zh:"願意的", ph:"ˈwɪlɪŋ", ex:"He is always willing to help his classmates study.", exZh:"他總是願意幫助同學讀書。", re:"Everyone likes him for that.", reZh:"大家都因此喜歡他。" },
{ t:"wink", zh:"眨眼", ph:"wɪŋk", ex:"He gave me a friendly wink across the room.", exZh:"他從房間另一頭友善地對我眨眼。", re:"He must have a plan.", reZh:"他一定有什麼計畫。" },
{ t:"wire", zh:"電線", ph:"ˈwaɪɚ", ex:"Do not touch that wire because it is dangerous.", exZh:"別碰那條電線，因為很危險。", re:"Thanks for the warning, I will not.", reZh:"謝謝提醒，我不會碰。" },
{ t:"wonder", zh:"想知道", ph:"ˈwʌndɚ", ex:"I wonder what the weather will be like tomorrow.", exZh:"我想知道明天天氣會如何。", re:"The news said it might rain.", reZh:"新聞說可能會下雨。" },
{ t:"wool", zh:"羊毛", ph:"wʊl", ex:"This sweater is made of soft wool from sheep.", exZh:"這件毛衣是用綿羊柔軟的羊毛做的。", re:"It must feel very warm.", reZh:"穿起來一定很暖和。" },
{ t:"wound", zh:"傷口", ph:"wund", ex:"The nurse cleaned the wound on my knee carefully.", exZh:"護理師仔細清理我膝蓋上的傷口。", re:"I hope it heals quickly.", reZh:"希望它快點癒合。" },
{ t:"yell", zh:"大喊", ph:"jɛl", ex:"Please do not yell at your little brother again.", exZh:"請不要再對你弟弟大吼了。", re:"Sorry, I lost my temper.", reZh:"抱歉，我發脾氣了。" }
] }
];
