// 內建國小單字包 — 6 級 × 50 字，每字附例句＋回覆句（國小程度生活日常對話）
// 欄位：t=單字 zh=中文 ph=音標 ex=例句 exZh=例句中文 re=回覆句 reZh=回覆句中文
const STARTER_PACK = [
{ level: 1, words: [
{ t:"I", zh:"我", ph:"aɪ", ex:"I am a student.", exZh:"我是學生。", re:"Nice to meet you.", reZh:"很高興認識你。" },
{ t:"you", zh:"你", ph:"ju", ex:"You are my friend.", exZh:"你是我的朋友。", re:"Yes, we are good friends.", reZh:"對，我們是好朋友。" },
{ t:"he", zh:"他", ph:"hi", ex:"He is my brother.", exZh:"他是我哥哥。", re:"He is very tall.", reZh:"他很高。" },
{ t:"she", zh:"她", ph:"ʃi", ex:"She is my teacher.", exZh:"她是我的老師。", re:"She is very nice.", reZh:"她人很好。" },
{ t:"it", zh:"它；牠", ph:"ɪt", ex:"It is a cat.", exZh:"牠是一隻貓。", re:"It is so cute.", reZh:"牠好可愛。" },
{ t:"we", zh:"我們", ph:"wi", ex:"We go to school together.", exZh:"我們一起上學。", re:"That sounds fun.", reZh:"聽起來很好玩。" },
{ t:"they", zh:"他們", ph:"ðe", ex:"They are playing outside.", exZh:"他們在外面玩。", re:"Let's join them.", reZh:"我們去加入他們吧。" },
{ t:"am", zh:"是（我）", ph:"æm", ex:"I am happy today.", exZh:"我今天很開心。", re:"That is great to hear.", reZh:"聽到這個真好。" },
{ t:"is", zh:"是（他/她/它）", ph:"ɪz", ex:"This is my book.", exZh:"這是我的書。", re:"It looks interesting.", reZh:"看起來很有趣。" },
{ t:"are", zh:"是（你/我們/他們）", ph:"ɑr", ex:"You are very kind.", exZh:"你人很好。", re:"Thank you so much.", reZh:"非常謝謝你。" },
{ t:"yes", zh:"是的", ph:"jɛs", ex:"Yes, I like ice cream.", exZh:"是的，我喜歡冰淇淋。", re:"Me too!", reZh:"我也是！" },
{ t:"no", zh:"不；不是", ph:"no", ex:"No, I am not tired.", exZh:"不，我不累。", re:"Good, let's keep going.", reZh:"好，那我們繼續。" },
{ t:"hello", zh:"你好", ph:"hɛˈlo", ex:"Hello, how are you?", exZh:"你好，你好嗎？", re:"I am fine, thank you.", reZh:"我很好，謝謝。" },
{ t:"hi", zh:"嗨", ph:"haɪ", ex:"Hi, my name is Amy.", exZh:"嗨，我叫艾美。", re:"Hi Amy, I am Tom.", reZh:"嗨艾美，我是湯姆。" },
{ t:"bye", zh:"再見", ph:"baɪ", ex:"Bye, see you tomorrow.", exZh:"再見，明天見。", re:"Bye, take care.", reZh:"再見，保重。" },
{ t:"good", zh:"好的", ph:"ɡʊd", ex:"This cake is very good.", exZh:"這個蛋糕很好吃。", re:"My mom made it.", reZh:"是我媽媽做的。" },
{ t:"bad", zh:"壞的", ph:"bæd", ex:"The weather is bad today.", exZh:"今天天氣很糟。", re:"Let's stay at home.", reZh:"那我們待在家吧。" },
{ t:"big", zh:"大的", ph:"bɪɡ", ex:"That is a big dog.", exZh:"那是一隻大狗。", re:"Yes, but it is friendly.", reZh:"對，但牠很友善。" },
{ t:"small", zh:"小的", ph:"smɔl", ex:"I have a small bag.", exZh:"我有一個小包包。", re:"It is very cute.", reZh:"它很可愛。" },
{ t:"cat", zh:"貓", ph:"kæt", ex:"My cat likes to sleep.", exZh:"我的貓喜歡睡覺。", re:"Cats sleep a lot.", reZh:"貓咪都睡很多。" },
{ t:"dog", zh:"狗", ph:"dɔɡ", ex:"I walk my dog every day.", exZh:"我每天遛狗。", re:"Your dog is lucky.", reZh:"你的狗真幸福。" },
{ t:"apple", zh:"蘋果", ph:"ˈæpl", ex:"I eat an apple every morning.", exZh:"我每天早上吃一顆蘋果。", re:"Apples are good for you.", reZh:"蘋果對你很好。" },
{ t:"book", zh:"書", ph:"bʊk", ex:"This book is fun to read.", exZh:"這本書讀起來很有趣。", re:"Can I read it too?", reZh:"我也可以讀嗎？" },
{ t:"pen", zh:"筆", ph:"pɛn", ex:"May I use your pen?", exZh:"我可以借你的筆嗎？", re:"Sure, here you are.", reZh:"當然，給你。" },
{ t:"boy", zh:"男孩", ph:"bɔɪ", ex:"The boy is running fast.", exZh:"那個男孩跑得很快。", re:"He runs every day.", reZh:"他每天都跑步。" },
{ t:"girl", zh:"女孩", ph:"ɡɝl", ex:"The girl is singing a song.", exZh:"那個女孩在唱歌。", re:"Her voice is beautiful.", reZh:"她的聲音很好聽。" },
{ t:"man", zh:"男人", ph:"mæn", ex:"That man is my father.", exZh:"那位男士是我爸爸。", re:"He looks very kind.", reZh:"他看起來人很好。" },
{ t:"woman", zh:"女人", ph:"ˈwʊmən", ex:"The woman is a doctor.", exZh:"那位女士是醫生。", re:"She helps many people.", reZh:"她幫助很多人。" },
{ t:"mom", zh:"媽媽", ph:"mɑm", ex:"My mom cooks dinner for us.", exZh:"我媽媽為我們煮晚餐。", re:"Her food must be yummy.", reZh:"她煮的東西一定很好吃。" },
{ t:"dad", zh:"爸爸", ph:"dæd", ex:"My dad drives me to school.", exZh:"我爸爸開車送我上學。", re:"That is very nice of him.", reZh:"他人真好。" },
{ t:"one", zh:"一", ph:"wʌn", ex:"I have one little sister.", exZh:"我有一個妹妹。", re:"I have one too.", reZh:"我也有一個。" },
{ t:"two", zh:"二", ph:"tu", ex:"I need two eggs for the cake.", exZh:"做蛋糕我需要兩顆蛋。", re:"Here are two eggs.", reZh:"這裡有兩顆蛋。" },
{ t:"three", zh:"三", ph:"θri", ex:"There are three birds in the tree.", exZh:"樹上有三隻鳥。", re:"They are singing.", reZh:"牠們在唱歌。" },
{ t:"four", zh:"四", ph:"fɔr", ex:"A dog has four legs.", exZh:"狗有四條腿。", re:"Yes, and it runs fast.", reZh:"對，而且跑得很快。" },
{ t:"five", zh:"五", ph:"faɪv", ex:"School ends at five o'clock.", exZh:"學校五點放學。", re:"See you at five.", reZh:"五點見。" },
{ t:"six", zh:"六", ph:"sɪks", ex:"I wake up at six every day.", exZh:"我每天六點起床。", re:"That is very early.", reZh:"那很早耶。" },
{ t:"seven", zh:"七", ph:"ˈsɛvən", ex:"My little brother is seven years old.", exZh:"我弟弟七歲。", re:"He is a big boy now.", reZh:"他是大男孩了。" },
{ t:"eight", zh:"八", ph:"et", ex:"Dinner is at eight tonight.", exZh:"今晚八點吃晚餐。", re:"I will be there.", reZh:"我會到。" },
{ t:"nine", zh:"九", ph:"naɪn", ex:"I go to bed at nine.", exZh:"我九點上床睡覺。", re:"Good night!", reZh:"晚安！" },
{ t:"ten", zh:"十", ph:"tɛn", ex:"I can count from one to ten.", exZh:"我會從一數到十。", re:"Great job!", reZh:"做得好！" },
{ t:"red", zh:"紅色", ph:"rɛd", ex:"I like your red hat.", exZh:"我喜歡你的紅帽子。", re:"Thank you, it is new.", reZh:"謝謝，這是新的。" },
{ t:"blue", zh:"藍色", ph:"blu", ex:"The sky is blue today.", exZh:"今天天空很藍。", re:"It is a beautiful day.", reZh:"今天天氣真好。" },
{ t:"green", zh:"綠色", ph:"ɡrin", ex:"The grass is green in spring.", exZh:"春天的草是綠色的。", re:"I love spring.", reZh:"我喜歡春天。" },
{ t:"yellow", zh:"黃色", ph:"ˈjɛlo", ex:"Bananas are yellow.", exZh:"香蕉是黃色的。", re:"And they are sweet.", reZh:"而且很甜。" },
{ t:"black", zh:"黑色", ph:"blæk", ex:"My cat is black and white.", exZh:"我的貓是黑白色的。", re:"It sounds lovely.", reZh:"聽起來很可愛。" },
{ t:"white", zh:"白色", ph:"waɪt", ex:"The snow is white and soft.", exZh:"雪是白色的，而且很鬆軟。", re:"Let's make a snowman.", reZh:"我們來堆雪人吧。" },
{ t:"happy", zh:"開心的", ph:"ˈhæpi", ex:"I am happy to see you.", exZh:"見到你我很開心。", re:"I am happy too.", reZh:"我也很開心。" },
{ t:"sad", zh:"難過的", ph:"sæd", ex:"She is sad because she lost her pen.", exZh:"她很難過，因為弄丟了筆。", re:"I can give her one.", reZh:"我可以給她一枝。" },
{ t:"love", zh:"愛", ph:"lʌv", ex:"I love my family.", exZh:"我愛我的家人。", re:"They love you too.", reZh:"他們也愛你。" },
{ t:"like", zh:"喜歡", ph:"laɪk", ex:"I like to play basketball.", exZh:"我喜歡打籃球。", re:"Let's play together.", reZh:"我們一起打吧。" }
]},
{ level: 2, words: [
{ t:"family", zh:"家庭；家人", ph:"ˈfæməli", ex:"There are four people in my family.", exZh:"我家有四個人。", re:"My family has five.", reZh:"我家有五個人。" },
{ t:"father", zh:"父親", ph:"ˈfɑðɚ", ex:"My father works in a bank.", exZh:"我父親在銀行工作。", re:"He must be very busy.", reZh:"他一定很忙。" },
{ t:"mother", zh:"母親", ph:"ˈmʌðɚ", ex:"My mother tells me stories at night.", exZh:"我母親晚上講故事給我聽。", re:"That is so warm.", reZh:"好溫馨喔。" },
{ t:"brother", zh:"兄弟", ph:"ˈbrʌðɚ", ex:"My brother and I play games together.", exZh:"我和我哥哥一起玩遊戲。", re:"That sounds fun.", reZh:"聽起來很好玩。" },
{ t:"sister", zh:"姊妹", ph:"ˈsɪstɚ", ex:"My sister helps me with my homework.", exZh:"我姊姊幫我做功課。", re:"You are lucky.", reZh:"你真幸運。" },
{ t:"baby", zh:"嬰兒", ph:"ˈbebi", ex:"The baby is sleeping now.", exZh:"寶寶正在睡覺。", re:"Let's be quiet.", reZh:"我們安靜一點。" },
{ t:"friend", zh:"朋友", ph:"frɛnd", ex:"Tom is my best friend.", exZh:"湯姆是我最好的朋友。", re:"Good friends are important.", reZh:"好朋友很重要。" },
{ t:"teacher", zh:"老師", ph:"ˈtitʃɚ", ex:"Our teacher is very kind.", exZh:"我們的老師人很好。", re:"You are lucky to have her.", reZh:"有她當老師真幸運。" },
{ t:"student", zh:"學生", ph:"ˈstudnt", ex:"I am a student at this school.", exZh:"我是這所學校的學生。", re:"Do you like your school?", reZh:"你喜歡你的學校嗎？" },
{ t:"school", zh:"學校", ph:"skul", ex:"I go to school by bus.", exZh:"我搭公車上學。", re:"I walk to school.", reZh:"我走路上學。" },
{ t:"class", zh:"班級；課", ph:"klæs", ex:"We have English class today.", exZh:"我們今天有英文課。", re:"English is my favorite.", reZh:"英文是我的最愛。" },
{ t:"desk", zh:"書桌", ph:"dɛsk", ex:"My books are on the desk.", exZh:"我的書在書桌上。", re:"Your desk is very clean.", reZh:"你的書桌很整齊。" },
{ t:"chair", zh:"椅子", ph:"tʃɛr", ex:"Please sit on this chair.", exZh:"請坐在這張椅子上。", re:"Thank you very much.", reZh:"非常謝謝你。" },
{ t:"bag", zh:"袋子；書包", ph:"bæɡ", ex:"My bag is heavy today.", exZh:"我的書包今天很重。", re:"Let me help you.", reZh:"我來幫你。" },
{ t:"pencil", zh:"鉛筆", ph:"ˈpɛnsl", ex:"I write with a pencil.", exZh:"我用鉛筆寫字。", re:"I like pencils too.", reZh:"我也喜歡用鉛筆。" },
{ t:"eraser", zh:"橡皮擦", ph:"ɪˈresɚ", ex:"Can I borrow your eraser?", exZh:"我可以借你的橡皮擦嗎？", re:"Sure, here it is.", reZh:"當然，在這裡。" },
{ t:"ruler", zh:"尺", ph:"ˈrulɚ", ex:"I draw a line with a ruler.", exZh:"我用尺畫線。", re:"Your line is very straight.", reZh:"你的線畫得很直。" },
{ t:"eye", zh:"眼睛", ph:"aɪ", ex:"Close your eyes and rest.", exZh:"閉上眼睛休息一下。", re:"I feel better now.", reZh:"我覺得好多了。" },
{ t:"ear", zh:"耳朵", ph:"ɪr", ex:"Rabbits have long ears.", exZh:"兔子有長耳朵。", re:"They hear very well.", reZh:"牠們聽力很好。" },
{ t:"nose", zh:"鼻子", ph:"noz", ex:"The dog smells with its nose.", exZh:"狗用鼻子聞味道。", re:"Dogs have good noses.", reZh:"狗的鼻子很靈。" },
{ t:"mouth", zh:"嘴巴", ph:"maʊθ", ex:"Open your mouth, please.", exZh:"請張開嘴巴。", re:"Ah, like this?", reZh:"啊，像這樣嗎？" },
{ t:"hand", zh:"手", ph:"hænd", ex:"Wash your hands before dinner.", exZh:"晚餐前要洗手。", re:"OK, I will.", reZh:"好，我會的。" },
{ t:"foot", zh:"腳", ph:"fʊt", ex:"My foot hurts a little.", exZh:"我的腳有點痛。", re:"You should rest.", reZh:"你應該休息一下。" },
{ t:"head", zh:"頭", ph:"hɛd", ex:"Put on your hat to keep your head warm.", exZh:"戴上帽子讓頭保暖。", re:"Good idea, it is cold.", reZh:"好主意，天氣很冷。" },
{ t:"hair", zh:"頭髮", ph:"hɛr", ex:"Her hair is long and black.", exZh:"她的頭髮又長又黑。", re:"It is very pretty.", reZh:"很漂亮。" },
{ t:"face", zh:"臉", ph:"fes", ex:"Wash your face in the morning.", exZh:"早上要洗臉。", re:"I do it every day.", reZh:"我每天都有洗。" },
{ t:"arm", zh:"手臂", ph:"ɑrm", ex:"He can lift the box with one arm.", exZh:"他一隻手臂就能舉起箱子。", re:"He is so strong.", reZh:"他好強壯。" },
{ t:"leg", zh:"腿", ph:"lɛɡ", ex:"I run fast with my long legs.", exZh:"我用長腿跑得很快。", re:"Let's race then.", reZh:"那我們來比賽吧。" },
{ t:"water", zh:"水", ph:"ˈwɔtɚ", ex:"Drink more water every day.", exZh:"每天要多喝水。", re:"Water is good for us.", reZh:"水對我們很好。" },
{ t:"milk", zh:"牛奶", ph:"mɪlk", ex:"I drink milk for breakfast.", exZh:"我早餐喝牛奶。", re:"Milk makes you strong.", reZh:"牛奶讓你強壯。" },
{ t:"tea", zh:"茶", ph:"ti", ex:"My grandma likes hot tea.", exZh:"我奶奶喜歡喝熱茶。", re:"Tea is good in winter.", reZh:"冬天喝茶很棒。" },
{ t:"juice", zh:"果汁", ph:"dʒus", ex:"Can I have some orange juice?", exZh:"我可以喝一點柳橙汁嗎？", re:"Sure, here you go.", reZh:"當然，給你。" },
{ t:"egg", zh:"蛋", ph:"ɛɡ", ex:"I eat an egg every morning.", exZh:"我每天早上吃一顆蛋。", re:"Eggs are healthy.", reZh:"蛋很健康。" },
{ t:"rice", zh:"米飯", ph:"raɪs", ex:"We eat rice for dinner.", exZh:"我們晚餐吃飯。", re:"I love rice with fish.", reZh:"我喜歡魚配飯。" },
{ t:"bread", zh:"麵包", ph:"brɛd", ex:"This bread smells so good.", exZh:"這麵包聞起來好香。", re:"It is fresh from the oven.", reZh:"這是剛出爐的。" },
{ t:"cake", zh:"蛋糕", ph:"kek", ex:"We have cake on my birthday.", exZh:"我生日時我們吃蛋糕。", re:"Happy birthday to you!", reZh:"祝你生日快樂！" },
{ t:"fish", zh:"魚", ph:"fɪʃ", ex:"There are many fish in the river.", exZh:"河裡有很多魚。", re:"Let's go and see them.", reZh:"我們去看看吧。" },
{ t:"chicken", zh:"雞；雞肉", ph:"ˈtʃɪkɪn", ex:"Mom cooks chicken soup for me.", exZh:"媽媽煮雞湯給我喝。", re:"Chicken soup is warm and good.", reZh:"雞湯又暖又好喝。" },
{ t:"banana", zh:"香蕉", ph:"bəˈnænə", ex:"Monkeys love bananas.", exZh:"猴子最愛香蕉。", re:"I love bananas too.", reZh:"我也愛香蕉。" },
{ t:"orange", zh:"柳橙；橘色", ph:"ˈɔrɪndʒ", ex:"This orange is sweet and juicy.", exZh:"這顆柳橙又甜又多汁。", re:"Can I have one?", reZh:"我可以吃一顆嗎？" },
{ t:"grape", zh:"葡萄", ph:"ɡrep", ex:"I like purple grapes.", exZh:"我喜歡紫色的葡萄。", re:"Grapes are my favorite fruit.", reZh:"葡萄是我最愛的水果。" },
{ t:"this", zh:"這個", ph:"ðɪs", ex:"This is my new toy.", exZh:"這是我的新玩具。", re:"Wow, it looks cool.", reZh:"哇，看起來好酷。" },
{ t:"that", zh:"那個", ph:"ðæt", ex:"That is our classroom.", exZh:"那是我們的教室。", re:"It is big and bright.", reZh:"又大又明亮。" },
{ t:"my", zh:"我的", ph:"maɪ", ex:"My favorite color is blue.", exZh:"我最喜歡的顏色是藍色。", re:"Mine is green.", reZh:"我的是綠色。" },
{ t:"your", zh:"你的", ph:"jʊr", ex:"Is this your notebook?", exZh:"這是你的筆記本嗎？", re:"Yes, thank you for finding it.", reZh:"是的，謝謝你找到它。" },
{ t:"his", zh:"他的", ph:"hɪz", ex:"His bike is red.", exZh:"他的腳踏車是紅色的。", re:"It looks very fast.", reZh:"看起來跑很快。" },
{ t:"her", zh:"她的", ph:"hɝ", ex:"Her dress is very pretty.", exZh:"她的洋裝很漂亮。", re:"She wears it to the party.", reZh:"她穿去參加派對。" },
{ t:"name", zh:"名字", ph:"nem", ex:"What is your name?", exZh:"你叫什麼名字？", re:"My name is Kevin.", reZh:"我叫凱文。" },
{ t:"old", zh:"老的；舊的", ph:"old", ex:"How old are you?", exZh:"你幾歲？", re:"I am ten years old.", reZh:"我十歲。" },
{ t:"new", zh:"新的", ph:"nu", ex:"I have new shoes today.", exZh:"我今天穿新鞋。", re:"They look great on you.", reZh:"你穿起來很好看。" }
]},
{ level: 3, words: [
{ t:"eat", zh:"吃", ph:"it", ex:"Let's eat lunch together.", exZh:"我們一起吃午餐吧。", re:"Great, I am hungry.", reZh:"太好了，我餓了。" },
{ t:"drink", zh:"喝", ph:"drɪŋk", ex:"Drink some water after running.", exZh:"跑完步要喝點水。", re:"OK, I am very thirsty.", reZh:"好，我好渴。" },
{ t:"go", zh:"去", ph:"ɡo", ex:"Let's go to the park.", exZh:"我們去公園吧。", re:"Yes, let's go now.", reZh:"好，現在就走。" },
{ t:"come", zh:"來", ph:"kʌm", ex:"Please come to my house.", exZh:"請來我家。", re:"I will come at three.", reZh:"我三點會到。" },
{ t:"run", zh:"跑", ph:"rʌn", ex:"I run in the park every morning.", exZh:"我每天早上在公園跑步。", re:"Running is good for you.", reZh:"跑步對你很好。" },
{ t:"walk", zh:"走路", ph:"wɔk", ex:"We walk to school together.", exZh:"我們一起走路上學。", re:"Walking is fun with friends.", reZh:"和朋友一起走很開心。" },
{ t:"jump", zh:"跳", ph:"dʒʌmp", ex:"The cat can jump very high.", exZh:"這隻貓可以跳很高。", re:"Wow, that is amazing.", reZh:"哇，太厲害了。" },
{ t:"sit", zh:"坐", ph:"sɪt", ex:"Please sit down and rest.", exZh:"請坐下休息。", re:"Thank you, my legs are tired.", reZh:"謝謝，我的腿好痠。" },
{ t:"stand", zh:"站", ph:"stænd", ex:"Please stand up and say your name.", exZh:"請站起來說你的名字。", re:"OK, my name is Lily.", reZh:"好，我叫莉莉。" },
{ t:"sleep", zh:"睡覺", ph:"slip", ex:"I sleep eight hours every night.", exZh:"我每晚睡八小時。", re:"That is a good habit.", reZh:"這是好習慣。" },
{ t:"wake", zh:"醒來", ph:"wek", ex:"I wake up at six thirty.", exZh:"我六點半起床。", re:"You wake up early.", reZh:"你起得真早。" },
{ t:"open", zh:"打開", ph:"ˈopən", ex:"Please open the window.", exZh:"請打開窗戶。", re:"Sure, it is hot in here.", reZh:"好，這裡好熱。" },
{ t:"close", zh:"關上", ph:"kloz", ex:"Close the door, please.", exZh:"請關門。", re:"OK, it is windy outside.", reZh:"好，外面風很大。" },
{ t:"read", zh:"閱讀", ph:"rid", ex:"I read a story before bed.", exZh:"我睡前讀一個故事。", re:"What story is it?", reZh:"是什麼故事呢？" },
{ t:"write", zh:"寫", ph:"raɪt", ex:"I write my name on the paper.", exZh:"我在紙上寫我的名字。", re:"Your writing is neat.", reZh:"你的字很工整。" },
{ t:"draw", zh:"畫畫", ph:"drɔ", ex:"I like to draw animals.", exZh:"我喜歡畫動物。", re:"Can you draw a cat for me?", reZh:"你可以幫我畫隻貓嗎？" },
{ t:"sing", zh:"唱歌", ph:"sɪŋ", ex:"We sing songs in music class.", exZh:"我們在音樂課唱歌。", re:"Singing makes me happy.", reZh:"唱歌讓我很開心。" },
{ t:"dance", zh:"跳舞", ph:"dæns", ex:"She dances very well.", exZh:"她舞跳得很好。", re:"She practices every day.", reZh:"她每天都練習。" },
{ t:"play", zh:"玩；打（球）", ph:"ple", ex:"Let's play a game after school.", exZh:"放學後我們玩個遊戲吧。", re:"Sure, what game?", reZh:"好啊，玩什麼遊戲？" },
{ t:"look", zh:"看", ph:"lʊk", ex:"Look at the rainbow!", exZh:"你看那道彩虹！", re:"Wow, it is so pretty.", reZh:"哇，好漂亮。" },
{ t:"see", zh:"看見", ph:"si", ex:"I can see a bird in the tree.", exZh:"我看見樹上有一隻鳥。", re:"I see it too.", reZh:"我也看到了。" },
{ t:"hear", zh:"聽見", ph:"hɪr", ex:"Do you hear the music?", exZh:"你聽見音樂了嗎？", re:"Yes, it is very nice.", reZh:"有，很好聽。" },
{ t:"listen", zh:"聽", ph:"ˈlɪsn", ex:"Listen to the teacher carefully.", exZh:"仔細聽老師說。", re:"I always do.", reZh:"我一直都有。" },
{ t:"speak", zh:"說（語言）", ph:"spik", ex:"Can you speak English?", exZh:"你會說英文嗎？", re:"Yes, a little.", reZh:"會一點點。" },
{ t:"say", zh:"說", ph:"se", ex:"Say hello to your mom for me.", exZh:"替我向你媽媽問好。", re:"I will, thank you.", reZh:"我會的，謝謝。" },
{ t:"talk", zh:"說話；聊天", ph:"tɔk", ex:"We talk about movies at lunch.", exZh:"我們午餐時聊電影。", re:"That sounds fun.", reZh:"聽起來很有趣。" },
{ t:"ask", zh:"問；請求", ph:"æsk", ex:"You can ask me any question.", exZh:"你可以問我任何問題。", re:"OK, what is this word?", reZh:"好，這個字是什麼？" },
{ t:"answer", zh:"回答", ph:"ˈænsɚ", ex:"I know the answer to this question.", exZh:"我知道這題的答案。", re:"Please tell us.", reZh:"請告訴我們。" },
{ t:"help", zh:"幫忙", ph:"hɛlp", ex:"Can you help me carry this box?", exZh:"你可以幫我搬這個箱子嗎？", re:"Sure, no problem.", reZh:"當然，沒問題。" },
{ t:"give", zh:"給", ph:"ɡɪv", ex:"Please give this book to Tom.", exZh:"請把這本書拿給湯姆。", re:"OK, I will give it to him.", reZh:"好，我會拿給他。" },
{ t:"take", zh:"拿；帶", ph:"tek", ex:"Take your umbrella, it may rain.", exZh:"帶著雨傘，可能會下雨。", re:"Good idea, thanks.", reZh:"好主意，謝謝。" },
{ t:"make", zh:"做；製作", ph:"mek", ex:"Let's make a card for Mom.", exZh:"我們做一張卡片給媽媽吧。", re:"She will love it.", reZh:"她一定會很喜歡。" },
{ t:"do", zh:"做", ph:"du", ex:"I do my homework after dinner.", exZh:"我晚餐後做功課。", re:"You are a good student.", reZh:"你是好學生。" },
{ t:"have", zh:"有", ph:"hæv", ex:"I have two tickets for the movie.", exZh:"我有兩張電影票。", re:"Can I go with you?", reZh:"我可以跟你去嗎？" },
{ t:"want", zh:"想要", ph:"wɑnt", ex:"I want a glass of water.", exZh:"我想要一杯水。", re:"Here you are.", reZh:"給你。" },
{ t:"need", zh:"需要", ph:"nid", ex:"I need a new notebook.", exZh:"我需要一本新筆記本。", re:"Let's buy one after school.", reZh:"放學後去買一本吧。" },
{ t:"buy", zh:"買", ph:"baɪ", ex:"Mom buys fruit at the market.", exZh:"媽媽在市場買水果。", re:"The fruit there is fresh.", reZh:"那裡的水果很新鮮。" },
{ t:"wash", zh:"洗", ph:"wɑʃ", ex:"I wash the dishes after dinner.", exZh:"我晚餐後洗碗。", re:"You are a big help.", reZh:"你幫了大忙。" },
{ t:"clean", zh:"打掃；乾淨的", ph:"klin", ex:"We clean the classroom together.", exZh:"我們一起打掃教室。", re:"Many hands make light work.", reZh:"人多好辦事。" },
{ t:"cook", zh:"煮飯", ph:"kʊk", ex:"Dad cooks noodles on Sunday.", exZh:"爸爸星期天煮麵。", re:"His noodles are the best.", reZh:"他煮的麵最好吃。" },
{ t:"cut", zh:"切；剪", ph:"kʌt", ex:"Be careful when you cut the paper.", exZh:"剪紙的時候要小心。", re:"I will be careful.", reZh:"我會小心的。" },
{ t:"put", zh:"放", ph:"pʊt", ex:"Put your toys back in the box.", exZh:"把玩具放回箱子裡。", re:"OK, I am doing it now.", reZh:"好，我現在就收。" },
{ t:"get", zh:"得到；拿", ph:"ɡɛt", ex:"I get a gift on my birthday.", exZh:"我生日時收到禮物。", re:"What did you get?", reZh:"你收到什麼？" },
{ t:"find", zh:"找到", ph:"faɪnd", ex:"I can not find my key.", exZh:"我找不到我的鑰匙。", re:"Let me help you look.", reZh:"我幫你找。" },
{ t:"know", zh:"知道", ph:"no", ex:"Do you know her name?", exZh:"你知道她的名字嗎？", re:"Yes, her name is Amy.", reZh:"知道，她叫艾美。" },
{ t:"think", zh:"想；認為", ph:"θɪŋk", ex:"I think it will rain today.", exZh:"我想今天會下雨。", re:"Then take an umbrella.", reZh:"那就帶把傘吧。" },
{ t:"learn", zh:"學習", ph:"lɝn", ex:"I learn English every day.", exZh:"我每天學英文。", re:"Practice makes perfect.", reZh:"熟能生巧。" },
{ t:"teach", zh:"教", ph:"titʃ", ex:"My teacher teaches us a new song.", exZh:"老師教我們一首新歌。", re:"Can you sing it for me?", reZh:"你可以唱給我聽嗎？" },
{ t:"work", zh:"工作", ph:"wɝk", ex:"My dad works very hard.", exZh:"我爸爸工作很努力。", re:"He does it for the family.", reZh:"他是為了家人。" },
{ t:"study", zh:"讀書；學習", ph:"ˈstʌdi", ex:"I study for the test tonight.", exZh:"我今晚為考試讀書。", re:"Good luck on your test!", reZh:"祝你考試順利！" }
]},
{ level: 4, words: [
{ t:"hot", zh:"熱的", ph:"hɑt", ex:"It is very hot today.", exZh:"今天非常熱。", re:"Let's drink something cold.", reZh:"我們喝點冰的吧。" },
{ t:"cold", zh:"冷的", ph:"kold", ex:"The water is too cold.", exZh:"水太冰了。", re:"Add some hot water.", reZh:"加點熱水吧。" },
{ t:"warm", zh:"溫暖的", ph:"wɔrm", ex:"This jacket keeps me warm.", exZh:"這件外套讓我很保暖。", re:"It looks warm and soft.", reZh:"看起來又暖又軟。" },
{ t:"cool", zh:"涼的；酷的", ph:"kul", ex:"The wind is cool tonight.", exZh:"今晚的風很涼。", re:"Perfect for a walk.", reZh:"很適合散步。" },
{ t:"sunny", zh:"晴朗的", ph:"ˈsʌni", ex:"It is sunny, let's go outside.", exZh:"天氣晴朗，我們出去吧。", re:"Yes, let's go to the park.", reZh:"好，去公園吧。" },
{ t:"rainy", zh:"下雨的", ph:"ˈreni", ex:"It is a rainy day.", exZh:"今天是下雨天。", re:"Let's play inside.", reZh:"那我們在室內玩。" },
{ t:"cloudy", zh:"多雲的", ph:"ˈklaʊdi", ex:"The sky is cloudy this morning.", exZh:"今天早上天空多雲。", re:"It may rain later.", reZh:"等等可能會下雨。" },
{ t:"windy", zh:"颳風的", ph:"ˈwɪndi", ex:"It is windy, hold your hat.", exZh:"風很大，抓好你的帽子。", re:"Thanks, it almost flew away.", reZh:"謝謝，它差點飛走。" },
{ t:"snow", zh:"雪", ph:"sno", ex:"Look, it is starting to snow!", exZh:"你看，開始下雪了！", re:"Let's go outside and play.", reZh:"我們出去玩吧。" },
{ t:"rain", zh:"雨；下雨", ph:"ren", ex:"The rain is very heavy now.", exZh:"現在雨下得很大。", re:"Stay inside and wait.", reZh:"待在裡面等等吧。" },
{ t:"sun", zh:"太陽", ph:"sʌn", ex:"The sun rises in the east.", exZh:"太陽從東邊升起。", re:"And it sets in the west.", reZh:"然後從西邊落下。" },
{ t:"moon", zh:"月亮", ph:"mun", ex:"The moon is bright tonight.", exZh:"今晚的月亮很亮。", re:"It is a full moon.", reZh:"今天是滿月。" },
{ t:"star", zh:"星星", ph:"stɑr", ex:"I can see many stars tonight.", exZh:"今晚我看得到好多星星。", re:"Let's count them together.", reZh:"我們一起數吧。" },
{ t:"sky", zh:"天空", ph:"skaɪ", ex:"There is a rainbow in the sky.", exZh:"天空中有一道彩虹。", re:"It has seven colors.", reZh:"它有七種顏色。" },
{ t:"day", zh:"白天；日子", ph:"de", ex:"Have a nice day!", exZh:"祝你有美好的一天！", re:"You too, see you later.", reZh:"你也是，待會見。" },
{ t:"night", zh:"夜晚", ph:"naɪt", ex:"Good night, sweet dreams.", exZh:"晚安，祝你有個好夢。", re:"Good night, see you tomorrow.", reZh:"晚安，明天見。" },
{ t:"morning", zh:"早上", ph:"ˈmɔrnɪŋ", ex:"Good morning, did you sleep well?", exZh:"早安，你睡得好嗎？", re:"Yes, I slept very well.", reZh:"有，我睡得很好。" },
{ t:"afternoon", zh:"下午", ph:"ˌæftɚˈnun", ex:"We play basketball in the afternoon.", exZh:"我們下午打籃球。", re:"Count me in!", reZh:"算我一份！" },
{ t:"evening", zh:"傍晚", ph:"ˈivnɪŋ", ex:"We take a walk in the evening.", exZh:"我們傍晚去散步。", re:"The air is nice then.", reZh:"那時候空氣很好。" },
{ t:"today", zh:"今天", ph:"təˈde", ex:"Today is my birthday.", exZh:"今天是我的生日。", re:"Happy birthday!", reZh:"生日快樂！" },
{ t:"tomorrow", zh:"明天", ph:"təˈmɔro", ex:"We have a test tomorrow.", exZh:"我們明天有考試。", re:"Let's study together tonight.", reZh:"今晚一起讀書吧。" },
{ t:"yesterday", zh:"昨天", ph:"ˈjɛstɚde", ex:"I saw a movie yesterday.", exZh:"我昨天看了一部電影。", re:"Was it good?", reZh:"好看嗎？" },
{ t:"week", zh:"星期；週", ph:"wik", ex:"There are seven days in a week.", exZh:"一週有七天。", re:"And Sunday is my favorite.", reZh:"星期天是我的最愛。" },
{ t:"month", zh:"月份", ph:"mʌnθ", ex:"My birthday is next month.", exZh:"我的生日在下個月。", re:"What day is it?", reZh:"是哪一天呢？" },
{ t:"year", zh:"年", ph:"jɪr", ex:"Happy New Year!", exZh:"新年快樂！", re:"Happy New Year to you too!", reZh:"也祝你新年快樂！" },
{ t:"time", zh:"時間", ph:"taɪm", ex:"What time is it now?", exZh:"現在幾點？", re:"It is three o'clock.", reZh:"三點整。" },
{ t:"clock", zh:"時鐘", ph:"klɑk", ex:"The clock on the wall is slow.", exZh:"牆上的時鐘慢了。", re:"Let's fix the time.", reZh:"我們把時間調好吧。" },
{ t:"watch", zh:"手錶；看", ph:"wɑtʃ", ex:"I got a new watch from Dad.", exZh:"爸爸送我一支新手錶。", re:"It looks really nice.", reZh:"看起來真好看。" },
{ t:"early", zh:"早的", ph:"ˈɝli", ex:"I go to bed early on school days.", exZh:"上學日我很早睡。", re:"That is why you are not tired.", reZh:"難怪你都不會累。" },
{ t:"late", zh:"遲的；晚的", ph:"let", ex:"Hurry up, we are late!", exZh:"快一點，我們遲到了！", re:"OK, I am coming.", reZh:"好，我來了。" },
{ t:"fast", zh:"快的", ph:"fæst", ex:"The train is very fast.", exZh:"火車非常快。", re:"It is faster than a bus.", reZh:"它比公車快。" },
{ t:"slow", zh:"慢的", ph:"slo", ex:"The turtle walks very slow.", exZh:"烏龜走得很慢。", re:"But it never gives up.", reZh:"但牠從不放棄。" },
{ t:"long", zh:"長的", ph:"lɔŋ", ex:"The river is very long.", exZh:"這條河很長。", re:"Where does it go?", reZh:"它流向哪裡呢？" },
{ t:"short", zh:"短的；矮的", ph:"ʃɔrt", ex:"My hair is short now.", exZh:"我的頭髮現在很短。", re:"It looks neat and cool.", reZh:"看起來清爽又帥氣。" },
{ t:"tall", zh:"高的", ph:"tɔl", ex:"My brother is very tall.", exZh:"我哥哥很高。", re:"He can play basketball well.", reZh:"他籃球一定打得好。" },
{ t:"high", zh:"高的（高度）", ph:"haɪ", ex:"The kite flies high in the sky.", exZh:"風箏在天上飛得很高。", re:"It almost touches the clouds.", reZh:"它快碰到雲了。" },
{ t:"low", zh:"低的", ph:"lo", ex:"The bird flies low over the water.", exZh:"鳥在水面上低飛。", re:"It is looking for fish.", reZh:"牠在找魚。" },
{ t:"many", zh:"許多（可數）", ph:"ˈmɛni", ex:"There are many books in the library.", exZh:"圖書館裡有很多書。", re:"I want to read them all.", reZh:"我想全部讀完。" },
{ t:"much", zh:"許多（不可數）", ph:"mʌtʃ", ex:"Thank you so much for your help.", exZh:"非常感謝你的幫忙。", re:"You are welcome.", reZh:"不客氣。" },
{ t:"few", zh:"很少的", ph:"fju", ex:"There are few people in the park today.", exZh:"今天公園裡人很少。", re:"It is quiet and nice.", reZh:"很安靜很舒服。" },
{ t:"little", zh:"小的；一點點", ph:"ˈlɪtl", ex:"The little bird is learning to fly.", exZh:"小鳥正在學飛。", re:"It will fly high one day.", reZh:"牠總有一天會飛得很高。" },
{ t:"easy", zh:"容易的", ph:"ˈizi", ex:"This question is easy for me.", exZh:"這題對我來說很簡單。", re:"Then please teach me.", reZh:"那請你教我。" },
{ t:"hard", zh:"困難的；努力地", ph:"hɑrd", ex:"This math problem is hard.", exZh:"這題數學很難。", re:"Let's solve it together.", reZh:"我們一起解吧。" },
{ t:"right", zh:"正確的；右邊", ph:"raɪt", ex:"Your answer is right!", exZh:"你的答案是對的！", re:"Yay, I studied hard.", reZh:"耶，我有認真讀書。" },
{ t:"wrong", zh:"錯誤的", ph:"rɔŋ", ex:"I took the wrong bus this morning.", exZh:"我今天早上搭錯公車。", re:"Oh no, were you late?", reZh:"糟糕，你遲到了嗎？" },
{ t:"same", zh:"相同的", ph:"sem", ex:"We have the same school bag.", exZh:"我們有一樣的書包。", re:"What a fun surprise!", reZh:"好有趣的巧合！" },
{ t:"different", zh:"不同的", ph:"ˈdɪfərənt", ex:"Our shoes are different colors.", exZh:"我們的鞋子顏色不同。", re:"Yours is blue, mine is red.", reZh:"你的是藍色，我的是紅色。" },
{ t:"dirty", zh:"髒的", ph:"ˈdɝti", ex:"My shoes are dirty after the rain.", exZh:"下雨後我的鞋子髒了。", re:"Let's clean them together.", reZh:"我們一起把它刷乾淨。" },
{ t:"beautiful", zh:"美麗的", ph:"ˈbjutəfəl", ex:"The flowers in the garden are beautiful.", exZh:"花園裡的花很美。", re:"Let's take a picture.", reZh:"我們來拍張照吧。" },
{ t:"nice", zh:"好的；親切的", ph:"naɪs", ex:"It is nice to meet you.", exZh:"很高興認識你。", re:"Nice to meet you too.", reZh:"我也很高興認識你。" }
]},
{ level: 5, words: [
{ t:"home", zh:"家", ph:"hom", ex:"I go home after school.", exZh:"我放學後回家。", re:"See you tomorrow then.", reZh:"那明天見囉。" },
{ t:"house", zh:"房子", ph:"haʊs", ex:"Their house has a big garden.", exZh:"他們的房子有個大花園。", re:"I want to see it.", reZh:"我想去看看。" },
{ t:"room", zh:"房間", ph:"rum", ex:"My room is small but clean.", exZh:"我的房間小但很乾淨。", re:"Clean rooms feel good.", reZh:"乾淨的房間讓人舒服。" },
{ t:"bed", zh:"床", ph:"bɛd", ex:"The cat is sleeping on my bed.", exZh:"貓在我的床上睡覺。", re:"It looks so comfortable.", reZh:"牠看起來好舒服。" },
{ t:"door", zh:"門", ph:"dɔr", ex:"Someone is knocking at the door.", exZh:"有人在敲門。", re:"I will open it.", reZh:"我去開門。" },
{ t:"window", zh:"窗戶", ph:"ˈwɪndo", ex:"Open the window for some fresh air.", exZh:"打開窗戶透透氣。", re:"The air feels great.", reZh:"空氣真舒服。" },
{ t:"table", zh:"桌子", ph:"ˈtebl", ex:"Dinner is on the table.", exZh:"晚餐在桌上了。", re:"I am coming!", reZh:"我來了！" },
{ t:"kitchen", zh:"廚房", ph:"ˈkɪtʃɪn", ex:"Mom is cooking in the kitchen.", exZh:"媽媽在廚房煮飯。", re:"It smells so good.", reZh:"聞起來好香。" },
{ t:"bathroom", zh:"浴室；廁所", ph:"ˈbæθrum", ex:"May I use the bathroom?", exZh:"我可以用一下廁所嗎？", re:"Sure, it is over there.", reZh:"當然，在那邊。" },
{ t:"park", zh:"公園", ph:"pɑrk", ex:"We fly kites in the park.", exZh:"我們在公園放風箏。", re:"That is my favorite thing.", reZh:"那是我最愛做的事。" },
{ t:"store", zh:"商店", ph:"stɔr", ex:"The store opens at nine.", exZh:"這家店九點開門。", re:"Let's go at ten.", reZh:"我們十點去吧。" },
{ t:"shop", zh:"商店；購物", ph:"ʃɑp", ex:"There is a toy shop near my home.", exZh:"我家附近有一間玩具店。", re:"Can we go this weekend?", reZh:"這週末可以去嗎？" },
{ t:"market", zh:"市場", ph:"ˈmɑrkɪt", ex:"The market is busy in the morning.", exZh:"市場早上很熱鬧。", re:"Everything there is fresh.", reZh:"那裡的東西都很新鮮。" },
{ t:"hospital", zh:"醫院", ph:"ˈhɑspɪtl", ex:"My aunt works at the hospital.", exZh:"我阿姨在醫院工作。", re:"Is she a nurse?", reZh:"她是護理師嗎？" },
{ t:"library", zh:"圖書館", ph:"ˈlaɪbrɛri", ex:"Please be quiet in the library.", exZh:"在圖書館請保持安靜。", re:"OK, I will whisper.", reZh:"好，我會小聲說話。" },
{ t:"zoo", zh:"動物園", ph:"zu", ex:"We saw lions at the zoo.", exZh:"我們在動物園看到獅子。", re:"Were they sleeping?", reZh:"牠們在睡覺嗎？" },
{ t:"farm", zh:"農場", ph:"fɑrm", ex:"There are cows and pigs on the farm.", exZh:"農場裡有牛和豬。", re:"I want to visit the farm.", reZh:"我想去農場看看。" },
{ t:"city", zh:"城市", ph:"ˈsɪti", ex:"The city is bright at night.", exZh:"城市夜晚燈火通明。", re:"The lights are beautiful.", reZh:"燈光很美。" },
{ t:"road", zh:"道路", ph:"rod", ex:"Look both ways before crossing the road.", exZh:"過馬路前要左右看。", re:"Safety first!", reZh:"安全第一！" },
{ t:"street", zh:"街道", ph:"strit", ex:"My school is on this street.", exZh:"我的學校在這條街上。", re:"It is very close.", reZh:"很近耶。" },
{ t:"car", zh:"汽車", ph:"kɑr", ex:"Dad washes the car on Sunday.", exZh:"爸爸星期天洗車。", re:"I like to help him.", reZh:"我喜歡幫他的忙。" },
{ t:"bus", zh:"公車", ph:"bʌs", ex:"The bus is coming, let's run!", exZh:"公車來了，快跑！", re:"Wait for me!", reZh:"等等我！" },
{ t:"train", zh:"火車", ph:"tren", ex:"We take the train to see Grandma.", exZh:"我們搭火車去看奶奶。", re:"Train rides are fun.", reZh:"搭火車很好玩。" },
{ t:"bike", zh:"腳踏車", ph:"baɪk", ex:"I ride my bike to the park.", exZh:"我騎腳踏車去公園。", re:"Wear your helmet.", reZh:"要戴安全帽喔。" },
{ t:"plane", zh:"飛機", ph:"plen", ex:"The plane flies above the clouds.", exZh:"飛機在雲上飛。", re:"I want to fly one day.", reZh:"我希望有天也能搭飛機。" },
{ t:"boat", zh:"船", ph:"bot", ex:"We row a boat on the lake.", exZh:"我們在湖上划船。", re:"The lake is so calm.", reZh:"湖面好平靜。" },
{ t:"phone", zh:"電話；手機", ph:"fon", ex:"Mom is talking on the phone.", exZh:"媽媽正在講電話。", re:"Let's wait a moment.", reZh:"我們等一下吧。" },
{ t:"computer", zh:"電腦", ph:"kəmˈpjutɚ", ex:"I use the computer to do homework.", exZh:"我用電腦做作業。", re:"Computers are very useful.", reZh:"電腦很有用。" },
{ t:"television", zh:"電視", ph:"ˈtɛləvɪʒən", ex:"We watch television after dinner.", exZh:"我們晚餐後看電視。", re:"What show do you like?", reZh:"你喜歡看什麼節目？" },
{ t:"radio", zh:"收音機", ph:"ˈredio", ex:"Grandpa listens to the radio every morning.", exZh:"爺爺每天早上聽收音機。", re:"He likes the news.", reZh:"他喜歡聽新聞。" },
{ t:"music", zh:"音樂", ph:"ˈmjuzɪk", ex:"I listen to music when I rest.", exZh:"我休息時聽音樂。", re:"Music makes us relax.", reZh:"音樂讓人放鬆。" },
{ t:"movie", zh:"電影", ph:"ˈmuvi", ex:"Let's watch a movie tonight.", exZh:"今晚我們看部電影吧。", re:"I will make popcorn.", reZh:"我來做爆米花。" },
{ t:"game", zh:"遊戲", ph:"ɡem", ex:"This game is fun to play.", exZh:"這個遊戲很好玩。", re:"Teach me how to play.", reZh:"教我怎麼玩。" },
{ t:"toy", zh:"玩具", ph:"tɔɪ", ex:"The baby is playing with a toy.", exZh:"寶寶在玩玩具。", re:"He looks so happy.", reZh:"他看起來好開心。" },
{ t:"ball", zh:"球", ph:"bɔl", ex:"Throw the ball to me!", exZh:"把球丟給我！", re:"Here it comes, catch!", reZh:"來囉，接住！" },
{ t:"doll", zh:"洋娃娃", ph:"dɑl", ex:"My sister sleeps with her doll.", exZh:"我妹妹抱著洋娃娃睡覺。", re:"That is so sweet.", reZh:"好可愛喔。" },
{ t:"kite", zh:"風箏", ph:"kaɪt", ex:"The kite is flying higher and higher.", exZh:"風箏越飛越高。", re:"Hold the string tight!", reZh:"線要抓緊！" },
{ t:"picture", zh:"圖畫；照片", ph:"ˈpɪktʃɚ", ex:"I drew a picture of my family.", exZh:"我畫了一張全家福。", re:"It is a lovely picture.", reZh:"這張畫真溫馨。" },
{ t:"photo", zh:"照片", ph:"ˈfoto", ex:"Let's take a photo together.", exZh:"我們一起拍張照吧。", re:"Say cheese!", reZh:"笑一個！" },
{ t:"letter", zh:"信；字母", ph:"ˈlɛtɚ", ex:"I wrote a letter to my friend.", exZh:"我寫了一封信給朋友。", re:"He will be happy to read it.", reZh:"他讀到一定很開心。" },
{ t:"money", zh:"錢", ph:"ˈmʌni", ex:"I save my money in a piggy bank.", exZh:"我把錢存在小豬撲滿裡。", re:"Saving is a good habit.", reZh:"存錢是好習慣。" },
{ t:"gift", zh:"禮物", ph:"ɡɪft", ex:"This gift is for you.", exZh:"這個禮物送給你。", re:"Thank you, I love it!", reZh:"謝謝你，我好喜歡！" },
{ t:"box", zh:"箱子；盒子", ph:"bɑks", ex:"What is inside the box?", exZh:"箱子裡面是什麼？", re:"Open it and see.", reZh:"打開看看吧。" },
{ t:"cup", zh:"杯子", ph:"kʌp", ex:"I drink milk from this cup.", exZh:"我用這個杯子喝牛奶。", re:"It is a cute cup.", reZh:"這杯子很可愛。" },
{ t:"bowl", zh:"碗", ph:"bol", ex:"I eat a bowl of rice.", exZh:"我吃一碗飯。", re:"Do you want more?", reZh:"還要再來一碗嗎？" },
{ t:"plate", zh:"盤子", ph:"plet", ex:"Put the cake on the plate.", exZh:"把蛋糕放到盤子上。", re:"OK, here it is.", reZh:"好，放好了。" },
{ t:"spoon", zh:"湯匙", ph:"spun", ex:"I eat soup with a spoon.", exZh:"我用湯匙喝湯。", re:"Be careful, it is hot.", reZh:"小心，湯很燙。" },
{ t:"knife", zh:"刀子", ph:"naɪf", ex:"The knife is sharp, be careful.", exZh:"刀子很利，要小心。", re:"I will let Mom use it.", reZh:"我會讓媽媽來用。" },
{ t:"fork", zh:"叉子", ph:"fɔrk", ex:"We eat noodles with a fork.", exZh:"我們用叉子吃麵。", re:"I use chopsticks too.", reZh:"我也會用筷子。" },
{ t:"bottle", zh:"瓶子", ph:"ˈbɑtl", ex:"Bring a bottle of water to school.", exZh:"帶一瓶水去學校。", re:"I never forget it.", reZh:"我從來不會忘記帶。" }
]},
{ level: 6, words: [
{ t:"angry", zh:"生氣的", ph:"ˈæŋɡri", ex:"He is angry because he lost the game.", exZh:"他輸了比賽所以很生氣。", re:"Let's cheer him up.", reZh:"我們去逗他開心吧。" },
{ t:"tired", zh:"累的", ph:"taɪrd", ex:"I am tired after the long walk.", exZh:"走了好久我好累。", re:"Sit down and rest a bit.", reZh:"坐下來休息一下吧。" },
{ t:"hungry", zh:"餓的", ph:"ˈhʌŋɡri", ex:"I am hungry, is dinner ready?", exZh:"我餓了，晚餐好了嗎？", re:"Yes, come and eat.", reZh:"好了，快來吃。" },
{ t:"thirsty", zh:"渴的", ph:"ˈθɝsti", ex:"I am thirsty after playing basketball.", exZh:"打完籃球我好渴。", re:"Here is some cold water.", reZh:"這裡有冰水。" },
{ t:"sick", zh:"生病的", ph:"sɪk", ex:"She is sick and stays at home today.", exZh:"她生病了，今天待在家。", re:"I hope she gets well soon.", reZh:"希望她早日康復。" },
{ t:"fine", zh:"好的；沒事的", ph:"faɪn", ex:"How are you? I am fine.", exZh:"你好嗎？我很好。", re:"Glad to hear that.", reZh:"很高興聽到。" },
{ t:"sorry", zh:"抱歉的", ph:"ˈsɑri", ex:"I am sorry I am late.", exZh:"對不起我遲到了。", re:"It is OK, come in.", reZh:"沒關係，進來吧。" },
{ t:"thank", zh:"感謝", ph:"θæŋk", ex:"Thank you for the nice gift.", exZh:"謝謝你送的好禮物。", re:"I am glad you like it.", reZh:"很高興你喜歡。" },
{ t:"please", zh:"請", ph:"pliz", ex:"Please pass me the salt.", exZh:"請把鹽遞給我。", re:"Here you are.", reZh:"給你。" },
{ t:"welcome", zh:"歡迎；不客氣", ph:"ˈwɛlkəm", ex:"Welcome to my home!", exZh:"歡迎來我家！", re:"Thank you for having me.", reZh:"謝謝你邀請我。" },
{ t:"excuse", zh:"原諒；藉口", ph:"ɪkˈskjuz", ex:"Excuse me, where is the station?", exZh:"不好意思，請問車站在哪裡？", re:"Go straight and turn left.", reZh:"直走然後左轉。" },
{ t:"sure", zh:"當然；確定的", ph:"ʃʊr", ex:"Can you help me? Sure!", exZh:"你能幫我嗎？當然！", re:"You are so kind.", reZh:"你人真好。" },
{ t:"maybe", zh:"也許", ph:"ˈmebi", ex:"Maybe it will be sunny tomorrow.", exZh:"明天也許會放晴。", re:"I hope so.", reZh:"希望如此。" },
{ t:"always", zh:"總是", ph:"ˈɔlwez", ex:"She always smiles at everyone.", exZh:"她總是對每個人微笑。", re:"Her smile is warm.", reZh:"她的笑容很溫暖。" },
{ t:"usually", zh:"通常", ph:"ˈjuʒʊəli", ex:"I usually get up at seven.", exZh:"我通常七點起床。", re:"Me too, same time.", reZh:"我也是，一樣的時間。" },
{ t:"often", zh:"常常", ph:"ˈɔfən", ex:"We often play here after school.", exZh:"我們放學後常在這裡玩。", re:"It is a great spot.", reZh:"這裡是個好地方。" },
{ t:"sometimes", zh:"有時候", ph:"ˈsʌmtaɪmz", ex:"Sometimes I help Mom cook.", exZh:"有時候我幫媽媽煮飯。", re:"That is very sweet.", reZh:"你真貼心。" },
{ t:"never", zh:"從不", ph:"ˈnɛvɚ", ex:"I never give up.", exZh:"我從不放棄。", re:"That is the spirit!", reZh:"就是這種精神！" },
{ t:"here", zh:"這裡", ph:"hɪr", ex:"Come here and look at this.", exZh:"過來這裡看看這個。", re:"Wow, what is it?", reZh:"哇，這是什麼？" },
{ t:"there", zh:"那裡", ph:"ðɛr", ex:"The bus stop is over there.", exZh:"公車站在那邊。", re:"Let's walk there together.", reZh:"我們一起走過去吧。" },
{ t:"where", zh:"哪裡", ph:"hwɛr", ex:"Where is my school bag?", exZh:"我的書包在哪裡？", re:"It is under the chair.", reZh:"在椅子下面。" },
{ t:"what", zh:"什麼", ph:"hwɑt", ex:"What do you want for lunch?", exZh:"你午餐想吃什麼？", re:"I want noodles.", reZh:"我想吃麵。" },
{ t:"who", zh:"誰", ph:"hu", ex:"Who is that tall boy?", exZh:"那個高高的男孩是誰？", re:"He is my cousin.", reZh:"他是我表哥。" },
{ t:"when", zh:"什麼時候", ph:"hwɛn", ex:"When does the movie start?", exZh:"電影什麼時候開始？", re:"It starts at seven.", reZh:"七點開始。" },
{ t:"why", zh:"為什麼", ph:"hwaɪ", ex:"Why are you laughing?", exZh:"你為什麼在笑？", re:"The joke is so funny.", reZh:"這笑話太好笑了。" },
{ t:"how", zh:"如何；怎麼", ph:"haʊ", ex:"How do you go to school?", exZh:"你怎麼去上學？", re:"I go by bike.", reZh:"我騎腳踏車去。" },
{ t:"because", zh:"因為", ph:"bɪˈkɔz", ex:"I am happy because today is Friday.", exZh:"我很開心，因為今天是星期五。", re:"The weekend is coming!", reZh:"週末要來了！" },
{ t:"but", zh:"但是", ph:"bʌt", ex:"I want to play, but I have homework.", exZh:"我想玩，但是我有功課。", re:"Finish it first, then play.", reZh:"先做完再玩吧。" },
{ t:"and", zh:"和", ph:"ænd", ex:"I like apples and bananas.", exZh:"我喜歡蘋果和香蕉。", re:"Both are healthy.", reZh:"兩種都很健康。" },
{ t:"or", zh:"或者", ph:"ɔr", ex:"Do you want tea or juice?", exZh:"你要茶還是果汁？", re:"Juice, please.", reZh:"請給我果汁。" },
{ t:"if", zh:"如果", ph:"ɪf", ex:"If it rains, we will stay home.", exZh:"如果下雨，我們就待在家。", re:"Then let's watch a movie.", reZh:"那我們就看電影吧。" },
{ t:"then", zh:"然後", ph:"ðɛn", ex:"Wash your hands, then eat.", exZh:"先洗手，然後吃飯。", re:"OK, I am done.", reZh:"好，我洗好了。" },
{ t:"very", zh:"非常", ph:"ˈvɛri", ex:"This story is very interesting.", exZh:"這個故事非常有趣。", re:"Please tell me more.", reZh:"請再多說一點。" },
{ t:"too", zh:"也；太", ph:"tu", ex:"I like ice cream too.", exZh:"我也喜歡冰淇淋。", re:"Let's buy some together.", reZh:"我們一起去買吧。" },
{ t:"also", zh:"也", ph:"ˈɔlso", ex:"She can also play the piano.", exZh:"她也會彈鋼琴。", re:"She is talented.", reZh:"她真有才華。" },
{ t:"again", zh:"再一次", ph:"əˈɡɛn", ex:"Can you say that again?", exZh:"你可以再說一次嗎？", re:"Sure, listen carefully.", reZh:"好，仔細聽喔。" },
{ t:"together", zh:"一起", ph:"təˈɡɛðɚ", ex:"Let's do our homework together.", exZh:"我們一起做功課吧。", re:"Good idea, it is faster.", reZh:"好主意，這樣比較快。" },
{ t:"alone", zh:"獨自", ph:"əˈlon", ex:"Do not go out alone at night.", exZh:"晚上不要獨自出門。", re:"I will go with my dad.", reZh:"我會跟爸爸一起去。" },
{ t:"careful", zh:"小心的", ph:"ˈkɛrfəl", ex:"Be careful, the floor is wet.", exZh:"小心，地板是濕的。", re:"Thanks for telling me.", reZh:"謝謝你提醒我。" },
{ t:"quiet", zh:"安靜的", ph:"ˈkwaɪət", ex:"Please be quiet, the baby is sleeping.", exZh:"請安靜，寶寶在睡覺。", re:"Sorry, I will whisper.", reZh:"抱歉，我會小聲一點。" },
{ t:"loud", zh:"大聲的", ph:"laʊd", ex:"The music is too loud.", exZh:"音樂太大聲了。", re:"I will turn it down.", reZh:"我把它關小聲。" },
{ t:"safe", zh:"安全的", ph:"sef", ex:"Wear a helmet to stay safe.", exZh:"戴安全帽保平安。", re:"Safety is important.", reZh:"安全很重要。" },
{ t:"dangerous", zh:"危險的", ph:"ˈdendʒərəs", ex:"Playing on the road is dangerous.", exZh:"在馬路上玩很危險。", re:"Let's play in the park.", reZh:"我們去公園玩吧。" },
{ t:"important", zh:"重要的", ph:"ɪmˈpɔrtnt", ex:"Breakfast is an important meal.", exZh:"早餐是重要的一餐。", re:"I eat it every day.", reZh:"我每天都有吃。" },
{ t:"favorite", zh:"最喜愛的", ph:"ˈfevərɪt", ex:"What is your favorite color?", exZh:"你最喜歡的顏色是什麼？", re:"My favorite is blue.", reZh:"我最喜歡藍色。" },
{ t:"ready", zh:"準備好的", ph:"ˈrɛdi", ex:"Are you ready to go?", exZh:"你準備好出發了嗎？", re:"Yes, let's go!", reZh:"好了，走吧！" },
{ t:"busy", zh:"忙碌的", ph:"ˈbɪzi", ex:"Dad is busy with his work.", exZh:"爸爸忙著工作。", re:"Let's not bother him.", reZh:"我們別吵他。" },
{ t:"free", zh:"有空的；免費的", ph:"fri", ex:"Are you free this Saturday?", exZh:"你這週六有空嗎？", re:"Yes, let's go out!", reZh:"有，我們出去玩吧！" },
{ t:"wait", zh:"等待", ph:"wet", ex:"Please wait for me at the gate.", exZh:"請在大門口等我。", re:"OK, do not be late.", reZh:"好，別遲到喔。" },
{ t:"hope", zh:"希望", ph:"hop", ex:"I hope you have a great day.", exZh:"希望你有美好的一天。", re:"Thank you, you too.", reZh:"謝謝，你也是。" }
]}
];

// 句子音標補充表 — 例句/回覆句用到、但單字包與 PHONETIC_DICT 沒有的字（含變化形）
const SENTENCE_PHONETICS = {
"add":"æd","ah":"ɑ","air":"ɛr","almost":"ˈɔlmost","amazing":"əˈmezɪŋ","amy":"ˈemi","an":"æn","animals":"ˈænəmlz","apples":"ˈæplz","at":"æt","aunt":"ænt","away":"əˈwe",
"bananas":"bəˈnænəz","bank":"bæŋk","basketball":"ˈbæskɪtbɔl","birds":"bɝdz","birthday":"ˈbɝθde","bit":"bɪt","books":"bʊks","borrow":"ˈbɑro","bother":"ˈbɑðɚ","breakfast":"ˈbrɛkfəst","bright":"braɪt","buys":"baɪz",
"calm":"kɑm","carefully":"ˈkɛrfəli","cats":"kæts","cheer":"tʃɪr","cheese":"tʃiz","chopsticks":"ˈtʃɑpstɪks","classroom":"ˈklæsrum","clouds":"klaʊdz","colors":"ˈkʌlɚz","comes":"kʌmz","comfortable":"ˈkʌmfɚtəbl","coming":"ˈkʌmɪŋ","computers":"kəmˈpjutɚz","cooking":"ˈkʊkɪŋ","cooks":"kʊks","count":"kaʊnt","cousin":"ˈkʌzn","cows":"kaʊz","cream":"krim","crossing":"ˈkrɔsɪŋ","cute":"kjut",
"dances":"ˈdænsɪz","days":"dez","did":"dɪd","dishes":"ˈdɪʃɪz","does":"dʌz","dogs":"dɔɡz","doing":"ˈduɪŋ","done":"dʌn","dreams":"drimz","dress":"drɛs","drew":"dru","drives":"draɪvz",
"ears":"ɪrz","east":"ist","eggs":"ɛɡz","ends":"ɛndz","everyone":"ˈɛvriwʌn","everything":"ˈɛvriθɪŋ","eyes":"aɪz",
"faster":"ˈfæstɚ","feels":"filz","finding":"ˈfaɪndɪŋ","fix":"fɪks","flew":"flu","flies":"flaɪz","flowers":"ˈflaʊɚz","flying":"ˈflaɪɪŋ","forget":"fɚˈɡɛt","fresh":"frɛʃ","friday":"ˈfraɪde","friendly":"ˈfrɛndli","friends":"frɛndz","funny":"ˈfʌni",
"games":"ɡemz","gate":"ɡet","gets":"ɡɛts","gives":"ɡɪvz","glad":"ɡlæd","going":"ˈɡoɪŋ","got":"ɡɑt","grandma":"ˈɡrænmɑ","grandpa":"ˈɡrænpɑ","grapes":"ɡreps","grass":"ɡræs",
"habit":"ˈhæbɪt","hands":"hændz","has":"hæz","hat":"hæt","having":"ˈhævɪŋ","healthy":"ˈhɛlθi","heavy":"ˈhɛvi","helmet":"ˈhɛlmɪt","helps":"hɛlps","higher":"ˈhaɪɚ","him":"hɪm","hold":"hold","homework":"ˈhomwɝk","hours":"aʊrz","hurry":"ˈhɝi","hurts":"hɝts",
"ice":"aɪs","inside":"ˌɪnˈsaɪd","its":"ɪts",
"jacket":"ˈdʒækɪt","join":"dʒɔɪn","joke":"dʒok","juicy":"ˈdʒusi",
"keeps":"kips","kevin":"ˈkɛvɪn","kites":"kaɪts","knocking":"ˈnɑkɪŋ",
"lake":"lek","later":"ˈletɚ","laughing":"ˈlæfɪŋ","learning":"ˈlɝnɪŋ","legs":"lɛɡz","let":"lɛt","let's":"lɛts","lift":"lɪft","lights":"laɪts","likes":"laɪks","lily":"ˈlɪli","lions":"ˈlaɪənz","listens":"ˈlɪsnz","looking":"ˈlʊkɪŋ","looks":"lʊks","lost":"lɔst","lot":"lɑt","lovely":"ˈlʌvli","luck":"lʌk","lucky":"ˈlʌki",
"made":"med","makes":"meks","math":"mæθ","me":"mi","meal":"mil","mine":"maɪn","moment":"ˈmomənt","monkeys":"ˈmʌŋkiz","movies":"ˈmuviz",
"neat":"nit","noodles":"ˈnudlz","noses":"ˈnozɪz","notebook":"ˈnotbʊk","nurse":"nɝs",
"o'clock":"əˈklɑk","oh":"o","ok":"ˌoˈke","opens":"ˈopənz","our":"aʊr","outside":"ˌaʊtˈsaɪd","oven":"ˈʌvən",
"pass":"pæs","pencils":"ˈpɛnslz","perfect":"ˈpɝfɪkt","piano":"piˈæno","piggy":"ˈpɪɡi","pigs":"pɪɡz","playing":"ˈpleɪŋ","popcorn":"ˈpɑpkɔrn","practices":"ˈpræktɪsɪz","pretty":"ˈprɪti","purple":"ˈpɝpl",
"rabbits":"ˈræbɪts","race":"res","rainbow":"ˈrenbo","rains":"renz","really":"ˈrɪli","relax":"rɪˈlæks","ride":"raɪd","rides":"raɪdz","rises":"ˈraɪzɪz","rooms":"rumz","row":"ro","running":"ˈrʌnɪŋ","runs":"rʌnz",
"safety":"ˈsefti","salt":"sɔlt","saturday":"ˈsætɚde","save":"sev","saving":"ˈsevɪŋ","saw":"sɔ","sets":"sɛts","sharp":"ʃɑrp","shoes":"ʃuz","should":"ʃʊd","singing":"ˈsɪŋɪŋ","sleeping":"ˈslipɪŋ","sleeps":"slips","slept":"slɛpt","smells":"smɛlz","smiles":"smaɪlz","snowman":"ˈsnomæn","soft":"sɔft","solve":"sɑlv","someone":"ˈsʌmwʌn","something":"ˈsʌmθɪŋ","songs":"sɔŋz","sounds":"saʊndz","soup":"sup","spirit":"ˈspɪrɪt","spot":"spɑt","stars":"stɑrz","starting":"ˈstɑrtɪŋ","starts":"stɑrts","station":"ˈsteʃən","stays":"stez","stories":"ˈstɔriz","straight":"stret","string":"strɪŋ","studied":"ˈstʌdid","sunday":"ˈsʌnde","surprise":"sɚˈpraɪz","sweet":"swit",
"talented":"ˈtæləntɪd","talking":"ˈtɔkɪŋ","teaches":"ˈtitʃɪz","telling":"ˈtɛlɪŋ","tells":"tɛlz","thanks":"θæŋks","thirty":"ˈθɝti","throw":"θro","tickets":"ˈtɪkɪts","tight":"taɪt","tom":"tɑm","took":"tʊk","touches":"ˈtʌtʃɪz","toys":"tɔɪz","turtle":"ˈtɝtl",
"umbrella":"ʌmˈbrɛlə","us":"ʌs","useful":"ˈjusfəl",
"visit":"ˈvɪzɪt","voice":"vɔɪs",
"walking":"ˈwɔkɪŋ","walks":"wɔks","was":"wʌz","washes":"ˈwɑʃɪz","ways":"wez","wears":"wɛrz","weekend":"ˈwikɛnd","were":"wɝ","west":"wɛst","wet":"wɛt","whisper":"ˈhwɪspɚ","will":"wɪl","works":"wɝks","wow":"waʊ","writing":"ˈraɪtɪŋ","wrote":"rot",
"yay":"je","years":"jɪrz","yours":"jʊrz","yummy":"ˈjʌmi"
};
